package com.gotop.jbpm.dao.impl;

import com.gotop.jbpm.dao.ITProcessBusinessDAO;
import com.gotop.jbpm.model.TProcessBusiness;
import com.gotop.jbpm.model.TProcessBusinessExample;
import com.gotop.jbpm.model.TProcessTaskExeConfig;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import oracle.sql.BLOB;

import org.apache.log4j.Logger;

public class TProcessBusinessDAO extends SqlMapClientDao implements ITProcessBusinessDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TProcessBusinessDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_PROCESS_BUSINESS
     *
     * @abatorgenerated 
     */
    public TProcessBusinessDAO() {
        super();
    }

    /**
     * 插入一条新数据.
     * @abatorgenerated
     */
    public void insert(TProcessBusiness record) {
        getSqlMapClientTemplate().insert("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_insert", record);
    }

    /**
     * 通过主键更新一条全部字段内容
     * @abatorgenerated
     */
    public int updateByPrimaryKey(TProcessBusiness record) {
        int rows = getSqlMapClientTemplate().update("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * 通过主键更新部分字段，部分字段说明：当字段为null时不更新，当字段值为''空值是更新为空值
     * @abatorgenerated
     */
    public int updateByPrimaryKeySelective(TProcessBusiness record) {
        int rows = getSqlMapClientTemplate().update("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * 通过查询实例，查询记录
     * @abatorgenerated
     */
    public List selectByExample(TProcessBusinessExample example) {
        List list = queryForList("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * 通过Map方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByMapAndPage(HashMap example) {
        List list = queryForList("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_selectByMapAndPage", example);
        return list;
    }

    /**
     * 通过Bean方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByExampleAndPage(TProcessBusiness record, TProcessBusinessExample example, Page page) {
         UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
         List list = queryForList("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_selectByExampleAndPage",parms,page);
        return list;
    }

    /**
     * 根据查询模板的查询结果扩展一个实例
     * @abatorgenerated
     * @param example 条件
     */
    public TProcessBusiness expandEntityByTemplate(TProcessBusiness example) {
        TProcessBusiness result = (TProcessBusiness)queryForObject("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_expandEntityByTemplate", example);
        return result;
    }

    /**
     * 根据Bean数据模板查询条件查询所有记录
     * @abatorgenerated
     * @param example 条件
     */
    public List queryEntitiesByTemplate(TProcessBusiness example) {
        List<TProcessBusiness> result = (List<TProcessBusiness>)queryForList("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_queryEntitiesByTemplate", example);
        return result;
    }

    /**
     * 根据Bean数据模板分页查询
     * @abatorgenerated
     * @param example 条件
     * @param page 分页信息
     */
    public List queryEntitiesByTemplateWithPage(TProcessBusiness example, Page page) {
        List<TProcessBusiness> result = (List<TProcessBusiness>)queryForList("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_queryEntitiesByTemplate", example,page);
        return result;
    }

    /**
     * 通过主键查询一条记录
     * @abatorgenerated
     */
    public TProcessBusiness selectByPrimaryKey(Long id) {
        TProcessBusiness key = new TProcessBusiness();
        key.setId(id);
        TProcessBusiness record = (TProcessBusiness) queryForObject("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * 通过查询实例，删除数据
     * @abatorgenerated
     */
    public int deleteByExample(TProcessBusinessExample example) {
        int rows = getSqlMapClientTemplate().delete("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * 根据Bean数据模板查询条件更新记录
     * @abatorgenerated
     * @param example 条件
     */
    public int deleteByTemplate(TProcessBusiness example) {
        int rows = getSqlMapClientTemplate().delete("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_deleteByTemplate", example);
        return rows;
    }

    /**
     * 通过主键删除一条记录
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(Long id) {
        TProcessBusiness key = new TProcessBusiness();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * 通过查询实例，统计总数
     * @abatorgenerated
     */
    public int countByExample(TProcessBusinessExample example) {
        Integer count = (Integer)  queryForObject("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * 通过查询Bean数据模板，统计总数
     * @abatorgenerated
     * @param example 条件
     */
    public int countByTemplate(TProcessBusiness example) {
        Integer rows = (Integer)queryForObject("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_countByTemplate", example);
        return rows.intValue();
    }

    /**
     * 通过查询实例，更新非null字段
     * @abatorgenerated
     */
    public int updateByExampleSelective(TProcessBusiness record, TProcessBusinessExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * 通过查询实例，更新全部字段
     * @abatorgenerated
     */
    public int updateByExample(TProcessBusiness record, TProcessBusinessExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * 根据Bean数据模板查询条件更新记录
     * @abatorgenerated
     * @param record 值
     * @param example 条件
     */
    public int updateEntityByTemplate(TProcessBusiness record, TProcessBusiness example) {
        HashMap<String,TProcessBusiness> params = new HashMap<String,TProcessBusiness>();
        params.put("record", record);
        params.put("template", example);
        int rows = getSqlMapClientTemplate().update("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_updateEntityByTemplate", params);
        return rows;
    }

    /**
     * 分页查询信息
     * @abatorgenerated
     */
    public List selectByDynamic(HashMap map, Page page) throws Exception {
        List list = queryForList("T_PROCESS_BUSINESS_SqlMap.abatorgenerated_selectByDynamic", map, page);
        return list;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_PROCESS_BUSINESS
     *
     * @abatorgenerated 
     */
    private static class UpdateByExampleParms extends TProcessBusinessExample {
        private Object record;

        public UpdateByExampleParms(Object record, TProcessBusinessExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public TProcessBusiness findProcessBusiness(Map<String, Object> map) {
		TProcessBusiness processBusiness = null;
		List list = queryForList("T_PROCESS_BUSINESS_SqlMap.findProcessBusiness", map);
		if(list.size() != 0){
			processBusiness = (TProcessBusiness) list.get(0);
		}
        return processBusiness;
	}

	@Override
	public void deleteBusiness(Map<String, Object> map) {
		delete("T_PROCESS_BUSINESS_SqlMap.deleteBusiness", map);
	}

	@Override
	public TProcessBusiness findProcessBusinessFile(Map<String, Object> map) {
		TProcessBusiness processBusiness = null;
		List list = queryForList("T_PROCESS_BUSINESS_SqlMap.findProcessBusinessFile", map);
		if(list.size() != 0){
			processBusiness = (TProcessBusiness) list.get(0);
		}
        return processBusiness;
	}

	@Override
	public void deleteBusinessFile(Map<String, Object> map) {
		delete("T_PROCESS_BUSINESS_SqlMap.deleteBusinessFile", map);
	}

	@Override
	public void toTaskConfig1(String xml, String deploymentId) throws UnsupportedEncodingException {
		Map<String, Object> map = new HashMap<String, Object>();
		byte[] bytes = xml.getBytes("utf-8");
		map.put("xml",bytes);
		map.put("deploymentId", deploymentId);
		update("T_PROCESS_BUSINESS_SqlMap.toTaskConfig1", map);
		
	}

	@Override
	public List<Map<String, Object>> toTaskConfig3(String deploymentId) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("deploymentId", deploymentId);
		List<Map<String, Object>> list = queryForList("T_PROCESS_BUSINESS_SqlMap.toTaskConfig3", map);
		return list;
	}

	@Override
	public void updateJbpm(Map<String, Object> map) {
		update("T_PROCESS_BUSINESS_SqlMap.updateJbpmXml", map);
	}

}