package com.gotop.jbpm.dao.impl;

import com.gotop.jbpm.dao.ITProcessTaskAssigneePersonDAO;
import com.gotop.jbpm.model.TProcessTaskAssigneePerson;
import com.gotop.jbpm.model.TProcessTaskAssigneePersonExample;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.log4j.Logger;

public class TProcessTaskAssigneePersonDAO extends SqlMapClientDao implements ITProcessTaskAssigneePersonDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TProcessTaskAssigneePersonDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_PROCESS_TASK_ASSIGNEE_PERSON
     *
     * @abatorgenerated 
     */
    public TProcessTaskAssigneePersonDAO() {
        super();
    }

    /**
     * 插入一条新数据.
     * @abatorgenerated
     */
    public void insert(TProcessTaskAssigneePerson record) {
        getSqlMapClientTemplate().insert("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_insert", record);
    }
    
    /**
     * 插入一条新数据.
     * @abatorgenerated
     */
    public void insert1(TProcessTaskAssigneePerson record) {
        getSqlMapClientTemplate().insert("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_insert1", record);
    }

    /**
     * 通过主键更新一条全部字段内容
     * @abatorgenerated
     */
    public int updateByPrimaryKey(TProcessTaskAssigneePerson record) {
        int rows = getSqlMapClientTemplate().update("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * 通过主键更新部分字段，部分字段说明：当字段为null时不更新，当字段值为''空值是更新为空值
     * @abatorgenerated
     */
    public int updateByPrimaryKeySelective(TProcessTaskAssigneePerson record) {
        int rows = getSqlMapClientTemplate().update("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * 通过查询实例，查询记录
     * @abatorgenerated
     */
    public List selectByExample(TProcessTaskAssigneePersonExample example) {
        List list = queryForList("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * 通过Map方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByMapAndPage(HashMap example) {
        List list = queryForList("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_selectByMapAndPage", example);
        return list;
    }

    /**
     * 通过Bean方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByExampleAndPage(TProcessTaskAssigneePerson record, TProcessTaskAssigneePersonExample example, Page page) {
         UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
         List list = queryForList("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_selectByExampleAndPage",parms,page);
        return list;
    }

    /**
     * 根据查询模板的查询结果扩展一个实例
     * @abatorgenerated
     * @param example 条件
     */
    public TProcessTaskAssigneePerson expandEntityByTemplate(TProcessTaskAssigneePerson example) {
        TProcessTaskAssigneePerson result = (TProcessTaskAssigneePerson)queryForObject("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_expandEntityByTemplate", example);
        return result;
    }

    /**
     * 根据Bean数据模板查询条件查询所有记录
     * @abatorgenerated
     * @param example 条件
     */
    public List queryEntitiesByTemplate(TProcessTaskAssigneePerson example) {
        List<TProcessTaskAssigneePerson> result = (List<TProcessTaskAssigneePerson>)queryForList("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_queryEntitiesByTemplate", example);
        return result;
    }

    /**
     * 根据Bean数据模板分页查询
     * @abatorgenerated
     * @param example 条件
     * @param page 分页信息
     */
    public List queryEntitiesByTemplateWithPage(TProcessTaskAssigneePerson example, Page page) {
        List<TProcessTaskAssigneePerson> result = (List<TProcessTaskAssigneePerson>)queryForList("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_queryEntitiesByTemplate", example,page);
        return result;
    }

    /**
     * 通过主键查询一条记录
     * @abatorgenerated
     */
    public TProcessTaskAssigneePerson selectByPrimaryKey(Long id) {
        TProcessTaskAssigneePerson key = new TProcessTaskAssigneePerson();
        key.setId(id);
        TProcessTaskAssigneePerson record = (TProcessTaskAssigneePerson) queryForObject("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * 通过查询实例，删除数据
     * @abatorgenerated
     */
    public int deleteByExample(TProcessTaskAssigneePersonExample example) {
        int rows = getSqlMapClientTemplate().delete("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * 根据Bean数据模板查询条件更新记录
     * @abatorgenerated
     * @param example 条件
     */
    public int deleteByTemplate(TProcessTaskAssigneePerson example) {
        int rows = getSqlMapClientTemplate().delete("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_deleteByTemplate", example);
        return rows;
    }

    /**
     * 通过主键删除一条记录
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(Long id) {
        TProcessTaskAssigneePerson key = new TProcessTaskAssigneePerson();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * 通过查询实例，统计总数
     * @abatorgenerated
     */
    public int countByExample(TProcessTaskAssigneePersonExample example) {
        Integer count = (Integer)  queryForObject("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * 通过查询Bean数据模板，统计总数
     * @abatorgenerated
     * @param example 条件
     */
    public int countByTemplate(TProcessTaskAssigneePerson example) {
        Integer rows = (Integer)queryForObject("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_countByTemplate", example);
        return rows.intValue();
    }

    /**
     * 通过查询实例，更新非null字段
     * @abatorgenerated
     */
    public int updateByExampleSelective(TProcessTaskAssigneePerson record, TProcessTaskAssigneePersonExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * 通过查询实例，更新全部字段
     * @abatorgenerated
     */
    public int updateByExample(TProcessTaskAssigneePerson record, TProcessTaskAssigneePersonExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * 根据Bean数据模板查询条件更新记录
     * @abatorgenerated
     * @param record 值
     * @param example 条件
     */
    public int updateEntityByTemplate(TProcessTaskAssigneePerson record, TProcessTaskAssigneePerson example) {
        HashMap<String,TProcessTaskAssigneePerson> params = new HashMap<String,TProcessTaskAssigneePerson>();
        params.put("record", record);
        params.put("template", example);
        int rows = getSqlMapClientTemplate().update("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_updateEntityByTemplate", params);
        return rows;
    }

    /**
     * 分页查询信息
     * @abatorgenerated
     */
    public List selectByDynamic(HashMap map, Page page) throws Exception {
        List list = queryForList("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.abatorgenerated_selectByDynamic", map, page);
        return list;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_PROCESS_TASK_ASSIGNEE_PERSON
     *
     * @abatorgenerated 
     */
    private static class UpdateByExampleParms extends TProcessTaskAssigneePersonExample {
        private Object record;

        public UpdateByExampleParms(Object record, TProcessTaskAssigneePersonExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public void updateTaskAssigneeState(Map<String, Object> map) {
		this.update("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.updateTaskAssigneeState", map);
	}
	/**
	 * 部室内部会签
	 */
	@Override
	public void updateTaskAssigneeState1(Map<String, Object> map) {
		this.update("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.updateTaskAssigneeState1", map);
	}

	@Override
	public List<TProcessTaskAssigneePerson> getUnCompleted(Map<String, Object> map) {
		 List list = queryForList("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.getUnCompleted", map);
	     return list;
	}

	@Override
	public List<TProcessTaskAssigneePerson> getCompleted(Map<String, Object> map) {
		//20140904 复用查询未完成任务的sql
		 List list = queryForList("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.getUnCompleted", map);
	     return list;
	}
	
	@Override
	public List<TProcessTaskAssigneePerson> getBsUnCompleted(Map<String, Object> map) {
		 List list = queryForList("T_PROCESS_TASK_ASSIGNEE_PERSON_SqlMap.getBsUnCompleted", map);
	     return list;
	}

}