package com.gotop.mettingRec.dao.impl;

import com.gotop.mettingApply.model.TMettingApply;
import com.gotop.mettingRec.dao.ITMettingReceiveDAO;
import com.gotop.mettingRec.model.TMettingReceive;
import com.gotop.mettingRec.model.TMettingReceiveExample;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import org.apache.log4j.Logger;

public class TMettingReceiveDAO extends SqlMapClientDao implements ITMettingReceiveDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TMettingReceiveDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_METTING_RECEIVE
     *
     * @abatorgenerated 
     */
    public TMettingReceiveDAO() {
        super();
    }

    /**
     * 插入一条新数据.
     * @abatorgenerated
     */
    public void insert(TMettingReceive record) {
        getSqlMapClientTemplate().insert("T_METTING_RECEIVE_SqlMap.abatorgenerated_insert", record);
    }

    /**
     * 通过主键更新一条全部字段内容
     * @abatorgenerated
     */
    public int updateByPrimaryKey(TMettingReceive record) {
        int rows = getSqlMapClientTemplate().update("T_METTING_RECEIVE_SqlMap.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * 通过主键更新部分字段，部分字段说明：当字段为null时不更新，当字段值为''空值是更新为空值
     * @abatorgenerated
     */
    public int updateByPrimaryKeySelective(TMettingReceive record) {
        int rows = getSqlMapClientTemplate().update("T_METTING_RECEIVE_SqlMap.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * 通过查询实例，查询记录
     * @abatorgenerated
     */
    public List selectByExample(TMettingReceiveExample example) {
        List list = queryForList("T_METTING_RECEIVE_SqlMap.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * 通过Map方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByMapAndPage(HashMap example) {
        List list = queryForList("T_METTING_RECEIVE_SqlMap.abatorgenerated_selectByMapAndPage", example);
        return list;
    }

    /**
     * 通过Bean方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByExampleAndPage(TMettingReceive record, TMettingReceiveExample example, Page page) {
         UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
         List list = queryForList("T_METTING_RECEIVE_SqlMap.abatorgenerated_selectByExampleAndPage",parms,page);
        return list;
    }

    /**
     * 根据查询模板的查询结果扩展一个实例
     * @abatorgenerated
     * @param example 条件
     */
    public TMettingReceive expandEntityByTemplate(TMettingReceive example) {
        TMettingReceive result = (TMettingReceive)queryForObject("T_METTING_RECEIVE_SqlMap.abatorgenerated_expandEntityByTemplate", example);
        return result;
    }

    /**
     * 根据Bean数据模板查询条件查询所有记录
     * @abatorgenerated
     * @param example 条件
     */
    public List queryEntitiesByTemplate(TMettingReceive example) {
        List<TMettingReceive> result = (List<TMettingReceive>)queryForList("T_METTING_RECEIVE_SqlMap.abatorgenerated_queryEntitiesByTemplate", example);
        return result;
    }

    /**
     * 根据Bean数据模板分页查询
     * @abatorgenerated
     * @param example 条件
     * @param page 分页信息
     */
    public List queryEntitiesByTemplateWithPage(TMettingReceive example, Page page) {
        List<TMettingReceive> result = (List<TMettingReceive>)queryForList("T_METTING_RECEIVE_SqlMap.abatorgenerated_queryEntitiesByTemplate", example,page);
        return result;
    }

    /**
     * 通过主键查询一条记录
     * @abatorgenerated
     */
    public TMettingReceive selectByPrimaryKey(Long recId) {
        TMettingReceive key = new TMettingReceive();
        key.setRecId(recId);
        TMettingReceive record = (TMettingReceive) queryForObject("T_METTING_RECEIVE_SqlMap.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * 通过查询实例，删除数据
     * @abatorgenerated
     */
    public int deleteByExample(TMettingReceiveExample example) {
        int rows = getSqlMapClientTemplate().delete("T_METTING_RECEIVE_SqlMap.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * 根据Bean数据模板查询条件更新记录
     * @abatorgenerated
     * @param example 条件
     */
    public int deleteByTemplate(TMettingReceive example) {
        int rows = getSqlMapClientTemplate().delete("T_METTING_RECEIVE_SqlMap.abatorgenerated_deleteByTemplate", example);
        return rows;
    }

    /**
     * 通过主键删除一条记录
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(Long recId) {
        TMettingReceive key = new TMettingReceive();
        key.setRecId(recId);
        int rows = getSqlMapClientTemplate().delete("T_METTING_RECEIVE_SqlMap.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * 通过查询实例，统计总数
     * @abatorgenerated
     */
    public int countByExample(TMettingReceiveExample example) {
        Integer count = (Integer)  queryForObject("T_METTING_RECEIVE_SqlMap.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * 通过查询Bean数据模板，统计总数
     * @abatorgenerated
     * @param example 条件
     */
    public int countByTemplate(TMettingReceive example) {
        Integer rows = (Integer)queryForObject("T_METTING_RECEIVE_SqlMap.abatorgenerated_countByTemplate", example);
        return rows.intValue();
    }

    /**
     * 通过查询实例，更新非null字段
     * @abatorgenerated
     */
    public int updateByExampleSelective(TMettingReceive record, TMettingReceiveExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_METTING_RECEIVE_SqlMap.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * 通过查询实例，更新全部字段
     * @abatorgenerated
     */
    public int updateByExample(TMettingReceive record, TMettingReceiveExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_METTING_RECEIVE_SqlMap.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * 根据Bean数据模板查询条件更新记录
     * @abatorgenerated
     * @param record 值
     * @param example 条件
     */
    public int updateEntityByTemplate(TMettingReceive record, TMettingReceive example) {
        HashMap<String,TMettingReceive> params = new HashMap<String,TMettingReceive>();
        params.put("record", record);
        params.put("template", example);
        int rows = getSqlMapClientTemplate().update("T_METTING_RECEIVE_SqlMap.abatorgenerated_updateEntityByTemplate", params);
        return rows;
    }

    /**
     * 分页查询信息
     * @abatorgenerated
     */
    public List selectByDynamic(HashMap map, Page page) throws Exception {
        List list = queryForList("T_METTING_RECEIVE_SqlMap.abatorgenerated_selectByDynamic", map, page);
        return list;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_METTING_RECEIVE
     *
     * @abatorgenerated 
     */
    private static class UpdateByExampleParms extends TMettingReceiveExample {
        private Object record;

        public UpdateByExampleParms(Object record, TMettingReceiveExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public void updateMettingRecvInfo(TMettingApply record) {
		getSqlMapClientTemplate().update("T_METTING_RECEIVE_SqlMap.update_meet_receive_status", record);
	}
}