package com.gotop.vo.subsystem;

/**
 * TxtdmId generated by MyEclipse Persistence Tools
 */

public class TxtdmId implements java.io.Serializable {

	// Fields

	private String fldm;

	private Integer szbm;

	// Constructors

	/** default constructor */
	public TxtdmId() {
	}

	/** full constructor */
	public TxtdmId(String fldm, Integer szbm) {
		this.fldm = fldm;
		this.szbm = szbm;
	}

	// Property accessors

	public String getFldm() {
		return this.fldm;
	}

	public void setFldm(String fldm) {
		this.fldm = fldm;
	}

	public Integer getSzbm() {
		return szbm;
	}

	public void setSzbm(Integer szbm) {
		this.szbm = szbm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TxtdmId))
			return false;
		TxtdmId castOther = (TxtdmId) other;

		return ((this.getFldm() == castOther.getFldm()) || (this.getFldm() != null
				&& castOther.getFldm() != null && this.getFldm().equals(
				castOther.getFldm())))
				&& ((this.getSzbm() == castOther.getSzbm()) || (this.getSzbm() != null
						&& castOther.getSzbm() != null && this.getSzbm()
						.equals(castOther.getSzbm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFldm() == null ? 0 : this.getFldm().hashCode());
		result = 37 * result
				+ (getSzbm() == null ? 0 : this.getSzbm().hashCode());
		return result;
	}

}