package com.gotop.opinion.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TApproveOpninionExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TApproveOpninionExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public TApproveOpninionExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected TApproveOpninionExample(TApproveOpninionExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_APPROVE_OPNINION
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andRecIdIsNull() {
            addCriterion("REC_ID is null");
            return this;
        }

        public Criteria andRecIdIsNotNull() {
            addCriterion("REC_ID is not null");
            return this;
        }

        public Criteria andRecIdEqualTo(Long value) {
            addCriterion("REC_ID =", value, "recId");
            return this;
        }

        public Criteria andRecIdNotEqualTo(Long value) {
            addCriterion("REC_ID <>", value, "recId");
            return this;
        }

        public Criteria andRecIdGreaterThan(Long value) {
            addCriterion("REC_ID >", value, "recId");
            return this;
        }

        public Criteria andRecIdGreaterThanOrEqualTo(Long value) {
            addCriterion("REC_ID >=", value, "recId");
            return this;
        }

        public Criteria andRecIdLessThan(Long value) {
            addCriterion("REC_ID <", value, "recId");
            return this;
        }

        public Criteria andRecIdLessThanOrEqualTo(Long value) {
            addCriterion("REC_ID <=", value, "recId");
            return this;
        }

        public Criteria andRecIdIn(List values) {
            addCriterion("REC_ID in", values, "recId");
            return this;
        }

        public Criteria andRecIdNotIn(List values) {
            addCriterion("REC_ID not in", values, "recId");
            return this;
        }

        public Criteria andRecIdBetween(Long value1, Long value2) {
            addCriterion("REC_ID between", value1, value2, "recId");
            return this;
        }

        public Criteria andRecIdNotBetween(Long value1, Long value2) {
            addCriterion("REC_ID not between", value1, value2, "recId");
            return this;
        }

        public Criteria andResourceIdIsNull() {
            addCriterion("RESOURCE_ID is null");
            return this;
        }

        public Criteria andResourceIdIsNotNull() {
            addCriterion("RESOURCE_ID is not null");
            return this;
        }

        public Criteria andResourceIdEqualTo(Long value) {
            addCriterion("RESOURCE_ID =", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdNotEqualTo(Long value) {
            addCriterion("RESOURCE_ID <>", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdGreaterThan(Long value) {
            addCriterion("RESOURCE_ID >", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("RESOURCE_ID >=", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdLessThan(Long value) {
            addCriterion("RESOURCE_ID <", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdLessThanOrEqualTo(Long value) {
            addCriterion("RESOURCE_ID <=", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdIn(List values) {
            addCriterion("RESOURCE_ID in", values, "resourceId");
            return this;
        }

        public Criteria andResourceIdNotIn(List values) {
            addCriterion("RESOURCE_ID not in", values, "resourceId");
            return this;
        }

        public Criteria andResourceIdBetween(Long value1, Long value2) {
            addCriterion("RESOURCE_ID between", value1, value2, "resourceId");
            return this;
        }

        public Criteria andResourceIdNotBetween(Long value1, Long value2) {
            addCriterion("RESOURCE_ID not between", value1, value2, "resourceId");
            return this;
        }

        public Criteria andResourceTypeIsNull() {
            addCriterion("RESOURCE_TYPE is null");
            return this;
        }

        public Criteria andResourceTypeIsNotNull() {
            addCriterion("RESOURCE_TYPE is not null");
            return this;
        }

        public Criteria andResourceTypeEqualTo(String value) {
            addCriterion("RESOURCE_TYPE =", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeNotEqualTo(String value) {
            addCriterion("RESOURCE_TYPE <>", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeGreaterThan(String value) {
            addCriterion("RESOURCE_TYPE >", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("RESOURCE_TYPE >=", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeLessThan(String value) {
            addCriterion("RESOURCE_TYPE <", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeLessThanOrEqualTo(String value) {
            addCriterion("RESOURCE_TYPE <=", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeLike(String value) {
            addCriterion("RESOURCE_TYPE like", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeNotLike(String value) {
            addCriterion("RESOURCE_TYPE not like", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeIn(List values) {
            addCriterion("RESOURCE_TYPE in", values, "resourceType");
            return this;
        }

        public Criteria andResourceTypeNotIn(List values) {
            addCriterion("RESOURCE_TYPE not in", values, "resourceType");
            return this;
        }

        public Criteria andResourceTypeBetween(String value1, String value2) {
            addCriterion("RESOURCE_TYPE between", value1, value2, "resourceType");
            return this;
        }

        public Criteria andResourceTypeNotBetween(String value1, String value2) {
            addCriterion("RESOURCE_TYPE not between", value1, value2, "resourceType");
            return this;
        }

        public Criteria andOpninionContentIsNull() {
            addCriterion("OPNINION_CONTENT is null");
            return this;
        }

        public Criteria andOpninionContentIsNotNull() {
            addCriterion("OPNINION_CONTENT is not null");
            return this;
        }

        public Criteria andOpninionContentEqualTo(String value) {
            addCriterion("OPNINION_CONTENT =", value, "opninionContent");
            return this;
        }

        public Criteria andOpninionContentNotEqualTo(String value) {
            addCriterion("OPNINION_CONTENT <>", value, "opninionContent");
            return this;
        }

        public Criteria andOpninionContentGreaterThan(String value) {
            addCriterion("OPNINION_CONTENT >", value, "opninionContent");
            return this;
        }

        public Criteria andOpninionContentGreaterThanOrEqualTo(String value) {
            addCriterion("OPNINION_CONTENT >=", value, "opninionContent");
            return this;
        }

        public Criteria andOpninionContentLessThan(String value) {
            addCriterion("OPNINION_CONTENT <", value, "opninionContent");
            return this;
        }

        public Criteria andOpninionContentLessThanOrEqualTo(String value) {
            addCriterion("OPNINION_CONTENT <=", value, "opninionContent");
            return this;
        }

        public Criteria andOpninionContentLike(String value) {
            addCriterion("OPNINION_CONTENT like", value, "opninionContent");
            return this;
        }

        public Criteria andOpninionContentNotLike(String value) {
            addCriterion("OPNINION_CONTENT not like", value, "opninionContent");
            return this;
        }

        public Criteria andOpninionContentIn(List values) {
            addCriterion("OPNINION_CONTENT in", values, "opninionContent");
            return this;
        }

        public Criteria andOpninionContentNotIn(List values) {
            addCriterion("OPNINION_CONTENT not in", values, "opninionContent");
            return this;
        }

        public Criteria andOpninionContentBetween(String value1, String value2) {
            addCriterion("OPNINION_CONTENT between", value1, value2, "opninionContent");
            return this;
        }

        public Criteria andOpninionContentNotBetween(String value1, String value2) {
            addCriterion("OPNINION_CONTENT not between", value1, value2, "opninionContent");
            return this;
        }

        public Criteria andOperatorTypeIsNull() {
            addCriterion("OPERATOR_TYPE is null");
            return this;
        }

        public Criteria andOperatorTypeIsNotNull() {
            addCriterion("OPERATOR_TYPE is not null");
            return this;
        }

        public Criteria andOperatorTypeEqualTo(String value) {
            addCriterion("OPERATOR_TYPE =", value, "operatorType");
            return this;
        }

        public Criteria andOperatorTypeNotEqualTo(String value) {
            addCriterion("OPERATOR_TYPE <>", value, "operatorType");
            return this;
        }

        public Criteria andOperatorTypeGreaterThan(String value) {
            addCriterion("OPERATOR_TYPE >", value, "operatorType");
            return this;
        }

        public Criteria andOperatorTypeGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATOR_TYPE >=", value, "operatorType");
            return this;
        }

        public Criteria andOperatorTypeLessThan(String value) {
            addCriterion("OPERATOR_TYPE <", value, "operatorType");
            return this;
        }

        public Criteria andOperatorTypeLessThanOrEqualTo(String value) {
            addCriterion("OPERATOR_TYPE <=", value, "operatorType");
            return this;
        }

        public Criteria andOperatorTypeLike(String value) {
            addCriterion("OPERATOR_TYPE like", value, "operatorType");
            return this;
        }

        public Criteria andOperatorTypeNotLike(String value) {
            addCriterion("OPERATOR_TYPE not like", value, "operatorType");
            return this;
        }

        public Criteria andOperatorTypeIn(List values) {
            addCriterion("OPERATOR_TYPE in", values, "operatorType");
            return this;
        }

        public Criteria andOperatorTypeNotIn(List values) {
            addCriterion("OPERATOR_TYPE not in", values, "operatorType");
            return this;
        }

        public Criteria andOperatorTypeBetween(String value1, String value2) {
            addCriterion("OPERATOR_TYPE between", value1, value2, "operatorType");
            return this;
        }

        public Criteria andOperatorTypeNotBetween(String value1, String value2) {
            addCriterion("OPERATOR_TYPE not between", value1, value2, "operatorType");
            return this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("OPERATOR is null");
            return this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("OPERATOR is not null");
            return this;
        }

        public Criteria andOperatorEqualTo(Long value) {
            addCriterion("OPERATOR =", value, "operator");
            return this;
        }

        public Criteria andOperatorNotEqualTo(Long value) {
            addCriterion("OPERATOR <>", value, "operator");
            return this;
        }

        public Criteria andOperatorGreaterThan(Long value) {
            addCriterion("OPERATOR >", value, "operator");
            return this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(Long value) {
            addCriterion("OPERATOR >=", value, "operator");
            return this;
        }

        public Criteria andOperatorLessThan(Long value) {
            addCriterion("OPERATOR <", value, "operator");
            return this;
        }

        public Criteria andOperatorLessThanOrEqualTo(Long value) {
            addCriterion("OPERATOR <=", value, "operator");
            return this;
        }

        public Criteria andOperatorIn(List values) {
            addCriterion("OPERATOR in", values, "operator");
            return this;
        }

        public Criteria andOperatorNotIn(List values) {
            addCriterion("OPERATOR not in", values, "operator");
            return this;
        }

        public Criteria andOperatorBetween(Long value1, Long value2) {
            addCriterion("OPERATOR between", value1, value2, "operator");
            return this;
        }

        public Criteria andOperatorNotBetween(Long value1, Long value2) {
            addCriterion("OPERATOR not between", value1, value2, "operator");
            return this;
        }

        public Criteria andOperaterDateIsNull() {
            addCriterion("OPERATER_DATE is null");
            return this;
        }

        public Criteria andOperaterDateIsNotNull() {
            addCriterion("OPERATER_DATE is not null");
            return this;
        }

        public Criteria andOperaterDateEqualTo(String value) {
            addCriterion("OPERATER_DATE =", value, "operaterDate");
            return this;
        }

        public Criteria andOperaterDateNotEqualTo(String value) {
            addCriterion("OPERATER_DATE <>", value, "operaterDate");
            return this;
        }

        public Criteria andOperaterDateGreaterThan(String value) {
            addCriterion("OPERATER_DATE >", value, "operaterDate");
            return this;
        }

        public Criteria andOperaterDateGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATER_DATE >=", value, "operaterDate");
            return this;
        }

        public Criteria andOperaterDateLessThan(String value) {
            addCriterion("OPERATER_DATE <", value, "operaterDate");
            return this;
        }

        public Criteria andOperaterDateLessThanOrEqualTo(String value) {
            addCriterion("OPERATER_DATE <=", value, "operaterDate");
            return this;
        }

        public Criteria andOperaterDateLike(String value) {
            addCriterion("OPERATER_DATE like", value, "operaterDate");
            return this;
        }

        public Criteria andOperaterDateNotLike(String value) {
            addCriterion("OPERATER_DATE not like", value, "operaterDate");
            return this;
        }

        public Criteria andOperaterDateIn(List values) {
            addCriterion("OPERATER_DATE in", values, "operaterDate");
            return this;
        }

        public Criteria andOperaterDateNotIn(List values) {
            addCriterion("OPERATER_DATE not in", values, "operaterDate");
            return this;
        }

        public Criteria andOperaterDateBetween(String value1, String value2) {
            addCriterion("OPERATER_DATE between", value1, value2, "operaterDate");
            return this;
        }

        public Criteria andOperaterDateNotBetween(String value1, String value2) {
            addCriterion("OPERATER_DATE not between", value1, value2, "operaterDate");
            return this;
        }

        public Criteria andOperaterTimeIsNull() {
            addCriterion("OPERATER_TIME is null");
            return this;
        }

        public Criteria andOperaterTimeIsNotNull() {
            addCriterion("OPERATER_TIME is not null");
            return this;
        }

        public Criteria andOperaterTimeEqualTo(String value) {
            addCriterion("OPERATER_TIME =", value, "operaterTime");
            return this;
        }

        public Criteria andOperaterTimeNotEqualTo(String value) {
            addCriterion("OPERATER_TIME <>", value, "operaterTime");
            return this;
        }

        public Criteria andOperaterTimeGreaterThan(String value) {
            addCriterion("OPERATER_TIME >", value, "operaterTime");
            return this;
        }

        public Criteria andOperaterTimeGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATER_TIME >=", value, "operaterTime");
            return this;
        }

        public Criteria andOperaterTimeLessThan(String value) {
            addCriterion("OPERATER_TIME <", value, "operaterTime");
            return this;
        }

        public Criteria andOperaterTimeLessThanOrEqualTo(String value) {
            addCriterion("OPERATER_TIME <=", value, "operaterTime");
            return this;
        }

        public Criteria andOperaterTimeLike(String value) {
            addCriterion("OPERATER_TIME like", value, "operaterTime");
            return this;
        }

        public Criteria andOperaterTimeNotLike(String value) {
            addCriterion("OPERATER_TIME not like", value, "operaterTime");
            return this;
        }

        public Criteria andOperaterTimeIn(List values) {
            addCriterion("OPERATER_TIME in", values, "operaterTime");
            return this;
        }

        public Criteria andOperaterTimeNotIn(List values) {
            addCriterion("OPERATER_TIME not in", values, "operaterTime");
            return this;
        }

        public Criteria andOperaterTimeBetween(String value1, String value2) {
            addCriterion("OPERATER_TIME between", value1, value2, "operaterTime");
            return this;
        }

        public Criteria andOperaterTimeNotBetween(String value1, String value2) {
            addCriterion("OPERATER_TIME not between", value1, value2, "operaterTime");
            return this;
        }

        public Criteria andNodeIdIsNull() {
            addCriterion("NODE_ID is null");
            return this;
        }

        public Criteria andNodeIdIsNotNull() {
            addCriterion("NODE_ID is not null");
            return this;
        }

        public Criteria andNodeIdEqualTo(String value) {
            addCriterion("NODE_ID =", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdNotEqualTo(String value) {
            addCriterion("NODE_ID <>", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdGreaterThan(String value) {
            addCriterion("NODE_ID >", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdGreaterThanOrEqualTo(String value) {
            addCriterion("NODE_ID >=", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdLessThan(String value) {
            addCriterion("NODE_ID <", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdLessThanOrEqualTo(String value) {
            addCriterion("NODE_ID <=", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdLike(String value) {
            addCriterion("NODE_ID like", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdNotLike(String value) {
            addCriterion("NODE_ID not like", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdIn(List values) {
            addCriterion("NODE_ID in", values, "nodeId");
            return this;
        }

        public Criteria andNodeIdNotIn(List values) {
            addCriterion("NODE_ID not in", values, "nodeId");
            return this;
        }

        public Criteria andNodeIdBetween(String value1, String value2) {
            addCriterion("NODE_ID between", value1, value2, "nodeId");
            return this;
        }

        public Criteria andNodeIdNotBetween(String value1, String value2) {
            addCriterion("NODE_ID not between", value1, value2, "nodeId");
            return this;
        }

        public Criteria andOrgcodeIsNull() {
            addCriterion("ORGCODE is null");
            return this;
        }

        public Criteria andOrgcodeIsNotNull() {
            addCriterion("ORGCODE is not null");
            return this;
        }

        public Criteria andOrgcodeEqualTo(String value) {
            addCriterion("ORGCODE =", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotEqualTo(String value) {
            addCriterion("ORGCODE <>", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeGreaterThan(String value) {
            addCriterion("ORGCODE >", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORGCODE >=", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeLessThan(String value) {
            addCriterion("ORGCODE <", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeLessThanOrEqualTo(String value) {
            addCriterion("ORGCODE <=", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeLike(String value) {
            addCriterion("ORGCODE like", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotLike(String value) {
            addCriterion("ORGCODE not like", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeIn(List values) {
            addCriterion("ORGCODE in", values, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotIn(List values) {
            addCriterion("ORGCODE not in", values, "orgcode");
            return this;
        }

        public Criteria andOrgcodeBetween(String value1, String value2) {
            addCriterion("ORGCODE between", value1, value2, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotBetween(String value1, String value2) {
            addCriterion("ORGCODE not between", value1, value2, "orgcode");
            return this;
        }

        public Criteria andNodeNameIsNull() {
            addCriterion("NODE_NAME is null");
            return this;
        }

        public Criteria andNodeNameIsNotNull() {
            addCriterion("NODE_NAME is not null");
            return this;
        }

        public Criteria andNodeNameEqualTo(String value) {
            addCriterion("NODE_NAME =", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameNotEqualTo(String value) {
            addCriterion("NODE_NAME <>", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameGreaterThan(String value) {
            addCriterion("NODE_NAME >", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameGreaterThanOrEqualTo(String value) {
            addCriterion("NODE_NAME >=", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameLessThan(String value) {
            addCriterion("NODE_NAME <", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameLessThanOrEqualTo(String value) {
            addCriterion("NODE_NAME <=", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameLike(String value) {
            addCriterion("NODE_NAME like", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameNotLike(String value) {
            addCriterion("NODE_NAME not like", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameIn(List values) {
            addCriterion("NODE_NAME in", values, "nodeName");
            return this;
        }

        public Criteria andNodeNameNotIn(List values) {
            addCriterion("NODE_NAME not in", values, "nodeName");
            return this;
        }

        public Criteria andNodeNameBetween(String value1, String value2) {
            addCriterion("NODE_NAME between", value1, value2, "nodeName");
            return this;
        }

        public Criteria andNodeNameNotBetween(String value1, String value2) {
            addCriterion("NODE_NAME not between", value1, value2, "nodeName");
            return this;
        }
    }
}