package com.gotop.vo.util;

/**
 * TxtbxxId generated by MyEclipse Persistence Tools
 */

public class TxtbxxId implements java.io.Serializable {

	// Fields

	private String zdm;

	private String bm;

	// Constructors

	/** default constructor */
	public TxtbxxId() {
	}

	/** full constructor */
	public TxtbxxId(String zdm, String bm) {
		this.zdm = zdm;
		this.bm = bm;
	}

	// Property accessors

	public String getZdm() {
		return this.zdm;
	}

	public void setZdm(String zdm) {
		this.zdm = zdm;
	}

	public String getBm() {
		return this.bm;
	}

	public void setBm(String bm) {
		this.bm = bm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TxtbxxId))
			return false;
		TxtbxxId castOther = (TxtbxxId) other;

		return ((this.getZdm() == castOther.getZdm()) || (this.getZdm() != null
				&& castOther.getZdm() != null && this.getZdm().equals(
				castOther.getZdm())))
				&& ((this.getBm() == castOther.getBm()) || (this.getBm() != null
						&& castOther.getBm() != null && this.getBm().equals(
						castOther.getBm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getZdm() == null ? 0 : this.getZdm().hashCode());
		result = 37 * result + (getBm() == null ? 0 : this.getBm().hashCode());
		return result;
	}

}