package com.gotop.vo.system;

import java.util.Date;

/**
 * TmoduleAuthRu generated by MyEclipse Persistence Tools
 */

public class TmoduleAuthRu implements java.io.Serializable {

	// Fields

	private TmoduleAuthRuId id;

	private Date sqsj;

	private Integer sqr;

	// Constructors

	/** default constructor */
	public TmoduleAuthRu() {
	}

	/** minimal constructor */
	public TmoduleAuthRu(TmoduleAuthRuId id) {
		this.id = id;
	}

	/** full constructor */
	public TmoduleAuthRu(TmoduleAuthRuId id, Date sqsj, Integer sqr) {
		this.id = id;
		this.sqsj = sqsj;
		this.sqr = sqr;
	}

	// Property accessors

	public TmoduleAuthRuId getId() {
		return this.id;
	}

	public void setId(TmoduleAuthRuId id) {
		this.id = id;
	}

	public Date getSqsj() {
		return this.sqsj;
	}

	public void setSqsj(Date sqsj) {
		this.sqsj = sqsj;
	}

	public Integer getSqr() {
		return this.sqr;
	}

	public void setSqr(Integer sqr) {
		this.sqr = sqr;
	}

}