package com.gotop.vo.system;

import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * Tonline generated by MyEclipse Persistence Tools
 */

public class Tonline implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	// Fields

	private Integer id;

	private Integer usid;

	private Date dlsj;

	private Date zhczsj;

	private String ip;

	private String yhmc;

	private String orgid;

	private String rolelevel;

	private String[] rolealias;
	
	private Set<String> rolealiasList;

	// Constructors

	public String getRolelevel()
	{
		return rolelevel;
	}

	public void setRolelevel(String rolelevel)
	{
		this.rolelevel = rolelevel;
	}

	/** default constructor */
	public Tonline()
	{
	}

	/** minimal constructor */
	public Tonline(Integer usid, Date dlsj, String yhmc)
	{
		this.usid = usid;
		this.dlsj = dlsj;
		this.yhmc = yhmc;
	}

	/** full constructor */
	public Tonline(Integer usid, Date dlsj, Date zhczsj, String ip,
			String yhmc, String orgid, String rolelevel)
	{
		this.usid = usid;
		this.dlsj = dlsj;
		this.zhczsj = zhczsj;
		this.ip = ip;
		this.yhmc = yhmc;
		this.orgid = orgid;
		this.rolelevel = rolelevel;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getUsid()
	{
		return this.usid;
	}

	public void setUsid(Integer usid)
	{
		this.usid = usid;
	}

	public Date getDlsj()
	{
		return this.dlsj;
	}

	public void setDlsj(Date dlsj)
	{
		this.dlsj = dlsj;
	}

	public Date getZhczsj()
	{
		return this.zhczsj;
	}

	public void setZhczsj(Date zhczsj)
	{
		this.zhczsj = zhczsj;
	}

	public String getIp()
	{
		return this.ip;
	}

	public void setIp(String ip)
	{
		this.ip = ip;
	}

	public String getYhmc()
	{
		return this.yhmc;
	}

	public void setYhmc(String yhmc)
	{
		this.yhmc = yhmc;
	}

	public String getOrgid()
	{
		return orgid;
	}

	public void setOrgid(String orgid)
	{
		this.orgid = orgid;
	}

	public String[] getRolealias()
	{
		return rolealias;
	}

	public void setRolealias(String[] rolealias)
	{
		this.rolealias = rolealias;
	}

	public Set<String> getRolealiasList() {
		return rolealiasList;
	}

	public void setRolealiasList(Set<String> rolealiasList) {
		this.rolealiasList = rolealiasList;
	}

}