package com.gotop.vo.system;

import java.util.Date;

/**
 * Trole2user generated by MyEclipse Persistence Tools
 */

public class Trole2user implements java.io.Serializable {

	// Fields

	private Trole2userId id;

	private Date sqsj;

	private Integer sqr;

	// Constructors

	/** default constructor */
	public Trole2user() {
	}

	/** full constructor */
	public Trole2user(Trole2userId id, Date sqsj, Integer sqr) {
		this.id = id;
		this.sqsj = sqsj;
		this.sqr = sqr;
	}

	// Property accessors

	public Trole2userId getId() {
		return this.id;
	}

	public void setId(Trole2userId id) {
		this.id = id;
	}

	public Date getSqsj() {
		return this.sqsj;
	}

	public void setSqsj(Date sqsj) {
		this.sqsj = sqsj;
	}

	public Integer getSqr() {
		return this.sqr;
	}

	public void setSqr(Integer sqr) {
		this.sqr = sqr;
	}

}