package com.gotop.messagePublish.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TMessagePublishExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TMessagePublishExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** */
    public TMessagePublishExample() {
        oredCriteria = new ArrayList();
    }

    /** */
    protected TMessagePublishExample(TMessagePublishExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** */
    /** */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table XMZHPT.T_MESSAGE_PUBLISH
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andMessageIdIsNull() {
            addCriterion("MESSAGE_ID is null");
            return this;
        }

        public Criteria andMessageIdIsNotNull() {
            addCriterion("MESSAGE_ID is not null");
            return this;
        }

        public Criteria andMessageIdEqualTo(Long value) {
            addCriterion("MESSAGE_ID =", value, "messageId");
            return this;
        }

        public Criteria andMessageIdNotEqualTo(Long value) {
            addCriterion("MESSAGE_ID <>", value, "messageId");
            return this;
        }

        public Criteria andMessageIdGreaterThan(Long value) {
            addCriterion("MESSAGE_ID >", value, "messageId");
            return this;
        }

        public Criteria andMessageIdGreaterThanOrEqualTo(Long value) {
            addCriterion("MESSAGE_ID >=", value, "messageId");
            return this;
        }

        public Criteria andMessageIdLessThan(Long value) {
            addCriterion("MESSAGE_ID <", value, "messageId");
            return this;
        }

        public Criteria andMessageIdLessThanOrEqualTo(Long value) {
            addCriterion("MESSAGE_ID <=", value, "messageId");
            return this;
        }

        public Criteria andMessageIdIn(List values) {
            addCriterion("MESSAGE_ID in", values, "messageId");
            return this;
        }

        public Criteria andMessageIdNotIn(List values) {
            addCriterion("MESSAGE_ID not in", values, "messageId");
            return this;
        }

        public Criteria andMessageIdBetween(Long value1, Long value2) {
            addCriterion("MESSAGE_ID between", value1, value2, "messageId");
            return this;
        }

        public Criteria andMessageIdNotBetween(Long value1, Long value2) {
            addCriterion("MESSAGE_ID not between", value1, value2, "messageId");
            return this;
        }

        public Criteria andFlowIdIsNull() {
            addCriterion("FLOW_ID is null");
            return this;
        }

        public Criteria andFlowIdIsNotNull() {
            addCriterion("FLOW_ID is not null");
            return this;
        }

        public Criteria andFlowIdEqualTo(String value) {
            addCriterion("FLOW_ID =", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotEqualTo(String value) {
            addCriterion("FLOW_ID <>", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThan(String value) {
            addCriterion("FLOW_ID >", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThanOrEqualTo(String value) {
            addCriterion("FLOW_ID >=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThan(String value) {
            addCriterion("FLOW_ID <", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThanOrEqualTo(String value) {
            addCriterion("FLOW_ID <=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLike(String value) {
            addCriterion("FLOW_ID like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotLike(String value) {
            addCriterion("FLOW_ID not like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdIn(List values) {
            addCriterion("FLOW_ID in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdNotIn(List values) {
            addCriterion("FLOW_ID not in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdBetween(String value1, String value2) {
            addCriterion("FLOW_ID between", value1, value2, "flowId");
            return this;
        }

        public Criteria andFlowIdNotBetween(String value1, String value2) {
            addCriterion("FLOW_ID not between", value1, value2, "flowId");
            return this;
        }

        public Criteria andMessageTitleIsNull() {
            addCriterion("MESSAGE_TITLE is null");
            return this;
        }

        public Criteria andMessageTitleIsNotNull() {
            addCriterion("MESSAGE_TITLE is not null");
            return this;
        }

        public Criteria andMessageTitleEqualTo(String value) {
            addCriterion("MESSAGE_TITLE =", value, "messageTitle");
            return this;
        }

        public Criteria andMessageTitleNotEqualTo(String value) {
            addCriterion("MESSAGE_TITLE <>", value, "messageTitle");
            return this;
        }

        public Criteria andMessageTitleGreaterThan(String value) {
            addCriterion("MESSAGE_TITLE >", value, "messageTitle");
            return this;
        }

        public Criteria andMessageTitleGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGE_TITLE >=", value, "messageTitle");
            return this;
        }

        public Criteria andMessageTitleLessThan(String value) {
            addCriterion("MESSAGE_TITLE <", value, "messageTitle");
            return this;
        }

        public Criteria andMessageTitleLessThanOrEqualTo(String value) {
            addCriterion("MESSAGE_TITLE <=", value, "messageTitle");
            return this;
        }

        public Criteria andMessageTitleLike(String value) {
            addCriterion("MESSAGE_TITLE like", value, "messageTitle");
            return this;
        }

        public Criteria andMessageTitleNotLike(String value) {
            addCriterion("MESSAGE_TITLE not like", value, "messageTitle");
            return this;
        }

        public Criteria andMessageTitleIn(List values) {
            addCriterion("MESSAGE_TITLE in", values, "messageTitle");
            return this;
        }

        public Criteria andMessageTitleNotIn(List values) {
            addCriterion("MESSAGE_TITLE not in", values, "messageTitle");
            return this;
        }

        public Criteria andMessageTitleBetween(String value1, String value2) {
            addCriterion("MESSAGE_TITLE between", value1, value2, "messageTitle");
            return this;
        }

        public Criteria andMessageTitleNotBetween(String value1, String value2) {
            addCriterion("MESSAGE_TITLE not between", value1, value2, "messageTitle");
            return this;
        }

        public Criteria andMessageTypeIsNull() {
            addCriterion("MESSAGE_TYPE is null");
            return this;
        }

        public Criteria andMessageTypeIsNotNull() {
            addCriterion("MESSAGE_TYPE is not null");
            return this;
        }

        public Criteria andMessageTypeEqualTo(String value) {
            addCriterion("MESSAGE_TYPE =", value, "messageType");
            return this;
        }

        public Criteria andMessageTypeNotEqualTo(String value) {
            addCriterion("MESSAGE_TYPE <>", value, "messageType");
            return this;
        }

        public Criteria andMessageTypeGreaterThan(String value) {
            addCriterion("MESSAGE_TYPE >", value, "messageType");
            return this;
        }

        public Criteria andMessageTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGE_TYPE >=", value, "messageType");
            return this;
        }

        public Criteria andMessageTypeLessThan(String value) {
            addCriterion("MESSAGE_TYPE <", value, "messageType");
            return this;
        }

        public Criteria andMessageTypeLessThanOrEqualTo(String value) {
            addCriterion("MESSAGE_TYPE <=", value, "messageType");
            return this;
        }

        public Criteria andMessageTypeLike(String value) {
            addCriterion("MESSAGE_TYPE like", value, "messageType");
            return this;
        }

        public Criteria andMessageTypeNotLike(String value) {
            addCriterion("MESSAGE_TYPE not like", value, "messageType");
            return this;
        }

        public Criteria andMessageTypeIn(List values) {
            addCriterion("MESSAGE_TYPE in", values, "messageType");
            return this;
        }

        public Criteria andMessageTypeNotIn(List values) {
            addCriterion("MESSAGE_TYPE not in", values, "messageType");
            return this;
        }

        public Criteria andMessageTypeBetween(String value1, String value2) {
            addCriterion("MESSAGE_TYPE between", value1, value2, "messageType");
            return this;
        }

        public Criteria andMessageTypeNotBetween(String value1, String value2) {
            addCriterion("MESSAGE_TYPE not between", value1, value2, "messageType");
            return this;
        }

        public Criteria andContentIsNull() {
            addCriterion("CONTENT is null");
            return this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("CONTENT is not null");
            return this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("CONTENT =", value, "content");
            return this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("CONTENT <>", value, "content");
            return this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("CONTENT >", value, "content");
            return this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT >=", value, "content");
            return this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("CONTENT <", value, "content");
            return this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("CONTENT <=", value, "content");
            return this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("CONTENT like", value, "content");
            return this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("CONTENT not like", value, "content");
            return this;
        }

        public Criteria andContentIn(List values) {
            addCriterion("CONTENT in", values, "content");
            return this;
        }

        public Criteria andContentNotIn(List values) {
            addCriterion("CONTENT not in", values, "content");
            return this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("CONTENT between", value1, value2, "content");
            return this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("CONTENT not between", value1, value2, "content");
            return this;
        }

        public Criteria andPublishTypeIsNull() {
            addCriterion("PUBLISH_TYPE is null");
            return this;
        }

        public Criteria andPublishTypeIsNotNull() {
            addCriterion("PUBLISH_TYPE is not null");
            return this;
        }

        public Criteria andPublishTypeEqualTo(String value) {
            addCriterion("PUBLISH_TYPE =", value, "publishType");
            return this;
        }

        public Criteria andPublishTypeNotEqualTo(String value) {
            addCriterion("PUBLISH_TYPE <>", value, "publishType");
            return this;
        }

        public Criteria andPublishTypeGreaterThan(String value) {
            addCriterion("PUBLISH_TYPE >", value, "publishType");
            return this;
        }

        public Criteria andPublishTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLISH_TYPE >=", value, "publishType");
            return this;
        }

        public Criteria andPublishTypeLessThan(String value) {
            addCriterion("PUBLISH_TYPE <", value, "publishType");
            return this;
        }

        public Criteria andPublishTypeLessThanOrEqualTo(String value) {
            addCriterion("PUBLISH_TYPE <=", value, "publishType");
            return this;
        }

        public Criteria andPublishTypeLike(String value) {
            addCriterion("PUBLISH_TYPE like", value, "publishType");
            return this;
        }

        public Criteria andPublishTypeNotLike(String value) {
            addCriterion("PUBLISH_TYPE not like", value, "publishType");
            return this;
        }

        public Criteria andPublishTypeIn(List values) {
            addCriterion("PUBLISH_TYPE in", values, "publishType");
            return this;
        }

        public Criteria andPublishTypeNotIn(List values) {
            addCriterion("PUBLISH_TYPE not in", values, "publishType");
            return this;
        }

        public Criteria andPublishTypeBetween(String value1, String value2) {
            addCriterion("PUBLISH_TYPE between", value1, value2, "publishType");
            return this;
        }

        public Criteria andPublishTypeNotBetween(String value1, String value2) {
            addCriterion("PUBLISH_TYPE not between", value1, value2, "publishType");
            return this;
        }

        public Criteria andPublishRangeIsNull() {
            addCriterion("PUBLISH_RANGE is null");
            return this;
        }

        public Criteria andPublishRangeIsNotNull() {
            addCriterion("PUBLISH_RANGE is not null");
            return this;
        }

        public Criteria andPublishRangeEqualTo(String value) {
            addCriterion("PUBLISH_RANGE =", value, "publishRange");
            return this;
        }

        public Criteria andPublishRangeNotEqualTo(String value) {
            addCriterion("PUBLISH_RANGE <>", value, "publishRange");
            return this;
        }

        public Criteria andPublishRangeGreaterThan(String value) {
            addCriterion("PUBLISH_RANGE >", value, "publishRange");
            return this;
        }

        public Criteria andPublishRangeGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLISH_RANGE >=", value, "publishRange");
            return this;
        }

        public Criteria andPublishRangeLessThan(String value) {
            addCriterion("PUBLISH_RANGE <", value, "publishRange");
            return this;
        }

        public Criteria andPublishRangeLessThanOrEqualTo(String value) {
            addCriterion("PUBLISH_RANGE <=", value, "publishRange");
            return this;
        }

        public Criteria andPublishRangeLike(String value) {
            addCriterion("PUBLISH_RANGE like", value, "publishRange");
            return this;
        }

        public Criteria andPublishRangeNotLike(String value) {
            addCriterion("PUBLISH_RANGE not like", value, "publishRange");
            return this;
        }

        public Criteria andPublishRangeIn(List values) {
            addCriterion("PUBLISH_RANGE in", values, "publishRange");
            return this;
        }

        public Criteria andPublishRangeNotIn(List values) {
            addCriterion("PUBLISH_RANGE not in", values, "publishRange");
            return this;
        }

        public Criteria andPublishRangeBetween(String value1, String value2) {
            addCriterion("PUBLISH_RANGE between", value1, value2, "publishRange");
            return this;
        }

        public Criteria andPublishRangeNotBetween(String value1, String value2) {
            addCriterion("PUBLISH_RANGE not between", value1, value2, "publishRange");
            return this;
        }

        public Criteria andObjOrgcodeIsNull() {
            addCriterion("OBJ_ORGCODE is null");
            return this;
        }

        public Criteria andObjOrgcodeIsNotNull() {
            addCriterion("OBJ_ORGCODE is not null");
            return this;
        }

        public Criteria andObjOrgcodeEqualTo(String value) {
            addCriterion("OBJ_ORGCODE =", value, "objOrgcode");
            return this;
        }

        public Criteria andObjOrgcodeNotEqualTo(String value) {
            addCriterion("OBJ_ORGCODE <>", value, "objOrgcode");
            return this;
        }

        public Criteria andObjOrgcodeGreaterThan(String value) {
            addCriterion("OBJ_ORGCODE >", value, "objOrgcode");
            return this;
        }

        public Criteria andObjOrgcodeGreaterThanOrEqualTo(String value) {
            addCriterion("OBJ_ORGCODE >=", value, "objOrgcode");
            return this;
        }

        public Criteria andObjOrgcodeLessThan(String value) {
            addCriterion("OBJ_ORGCODE <", value, "objOrgcode");
            return this;
        }

        public Criteria andObjOrgcodeLessThanOrEqualTo(String value) {
            addCriterion("OBJ_ORGCODE <=", value, "objOrgcode");
            return this;
        }

        public Criteria andObjOrgcodeLike(String value) {
            addCriterion("OBJ_ORGCODE like", value, "objOrgcode");
            return this;
        }

        public Criteria andObjOrgcodeNotLike(String value) {
            addCriterion("OBJ_ORGCODE not like", value, "objOrgcode");
            return this;
        }

        public Criteria andObjOrgcodeIn(List values) {
            addCriterion("OBJ_ORGCODE in", values, "objOrgcode");
            return this;
        }

        public Criteria andObjOrgcodeNotIn(List values) {
            addCriterion("OBJ_ORGCODE not in", values, "objOrgcode");
            return this;
        }

        public Criteria andObjOrgcodeBetween(String value1, String value2) {
            addCriterion("OBJ_ORGCODE between", value1, value2, "objOrgcode");
            return this;
        }

        public Criteria andObjOrgcodeNotBetween(String value1, String value2) {
            addCriterion("OBJ_ORGCODE not between", value1, value2, "objOrgcode");
            return this;
        }

        public Criteria andOrgcodeIsNull() {
            addCriterion("ORGCODE is null");
            return this;
        }

        public Criteria andOrgcodeIsNotNull() {
            addCriterion("ORGCODE is not null");
            return this;
        }

        public Criteria andOrgcodeEqualTo(String value) {
            addCriterion("ORGCODE =", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotEqualTo(String value) {
            addCriterion("ORGCODE <>", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeGreaterThan(String value) {
            addCriterion("ORGCODE >", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORGCODE >=", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeLessThan(String value) {
            addCriterion("ORGCODE <", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeLessThanOrEqualTo(String value) {
            addCriterion("ORGCODE <=", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeLike(String value) {
            addCriterion("ORGCODE like", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotLike(String value) {
            addCriterion("ORGCODE not like", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeIn(List values) {
            addCriterion("ORGCODE in", values, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotIn(List values) {
            addCriterion("ORGCODE not in", values, "orgcode");
            return this;
        }

        public Criteria andOrgcodeBetween(String value1, String value2) {
            addCriterion("ORGCODE between", value1, value2, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotBetween(String value1, String value2) {
            addCriterion("ORGCODE not between", value1, value2, "orgcode");
            return this;
        }

        public Criteria andCreateEmpidIsNull() {
            addCriterion("CREATE_EMPID is null");
            return this;
        }

        public Criteria andCreateEmpidIsNotNull() {
            addCriterion("CREATE_EMPID is not null");
            return this;
        }

        public Criteria andCreateEmpidEqualTo(Long value) {
            addCriterion("CREATE_EMPID =", value, "createEmpid");
            return this;
        }

        public Criteria andCreateEmpidNotEqualTo(Long value) {
            addCriterion("CREATE_EMPID <>", value, "createEmpid");
            return this;
        }

        public Criteria andCreateEmpidGreaterThan(Long value) {
            addCriterion("CREATE_EMPID >", value, "createEmpid");
            return this;
        }

        public Criteria andCreateEmpidGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_EMPID >=", value, "createEmpid");
            return this;
        }

        public Criteria andCreateEmpidLessThan(Long value) {
            addCriterion("CREATE_EMPID <", value, "createEmpid");
            return this;
        }

        public Criteria andCreateEmpidLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_EMPID <=", value, "createEmpid");
            return this;
        }

        public Criteria andCreateEmpidIn(List values) {
            addCriterion("CREATE_EMPID in", values, "createEmpid");
            return this;
        }

        public Criteria andCreateEmpidNotIn(List values) {
            addCriterion("CREATE_EMPID not in", values, "createEmpid");
            return this;
        }

        public Criteria andCreateEmpidBetween(Long value1, Long value2) {
            addCriterion("CREATE_EMPID between", value1, value2, "createEmpid");
            return this;
        }

        public Criteria andCreateEmpidNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_EMPID not between", value1, value2, "createEmpid");
            return this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateIn(List values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateNotIn(List values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }
    }
}