package com.gotop.opinion.dao.impl;

import com.gotop.opinion.dao.ITApproveOpninionDAO;
import com.gotop.opinion.model.TApproveOpninion;
import com.gotop.opinion.model.TApproveOpninionExample;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import org.apache.log4j.Logger;

public class TApproveOpninionDAO extends SqlMapClientDao implements ITApproveOpninionDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TApproveOpninionDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_APPROVE_OPNINION
     *
     * @abatorgenerated 
     */
    public TApproveOpninionDAO() {
        super();
    }

    /**
     * 插入一条新数据.
     * @abatorgenerated
     */
    public Long insert(TApproveOpninion record) {
        return (Long) getSqlMapClientTemplate().insert("T_APPROVE_OPNINION_SqlMap.abatorgenerated_insert", record);
    }

    /**
     * 通过主键更新一条全部字段内容
     * @abatorgenerated
     */
    public int updateByPrimaryKey(TApproveOpninion record) {
        int rows = getSqlMapClientTemplate().update("T_APPROVE_OPNINION_SqlMap.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * 通过主键更新部分字段，部分字段说明：当字段为null时不更新，当字段值为''空值是更新为空值
     * @abatorgenerated
     */
    public int updateByPrimaryKeySelective(TApproveOpninion record) {
        int rows = getSqlMapClientTemplate().update("T_APPROVE_OPNINION_SqlMap.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * 通过查询实例，查询记录
     * @abatorgenerated
     */
    public List selectByExample(TApproveOpninionExample example) {
        List list = queryForList("T_APPROVE_OPNINION_SqlMap.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * 通过Map方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByMapAndPage(HashMap example) {
        List list = queryForList("T_APPROVE_OPNINION_SqlMap.abatorgenerated_selectByMapAndPage", example);
        return list;
    }

    /**
     * 通过Bean方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByExampleAndPage(TApproveOpninion record, TApproveOpninionExample example, Page page) {
         UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
         List list = queryForList("T_APPROVE_OPNINION_SqlMap.abatorgenerated_selectByExampleAndPage",parms,page);
        return list;
    }

    /**
     * 根据查询模板的查询结果扩展一个实例
     * @abatorgenerated
     * @param example 条件
     */
    public TApproveOpninion expandEntityByTemplate(TApproveOpninion example) {
        TApproveOpninion result = (TApproveOpninion)queryForObject("T_APPROVE_OPNINION_SqlMap.abatorgenerated_expandEntityByTemplate", example);
        return result;
    }

    /**
     * 根据Bean数据模板查询条件查询所有记录
     * @abatorgenerated
     * @param example 条件
     */
    public List queryEntitiesByTemplate(TApproveOpninion example) {
        List<TApproveOpninion> result = (List<TApproveOpninion>)queryForList("T_APPROVE_OPNINION_SqlMap.abatorgenerated_queryEntitiesByTemplate", example);
        return result;
    }

    /**
     * 根据Bean数据模板分页查询
     * @abatorgenerated
     * @param example 条件
     * @param page 分页信息
     */
    public List queryEntitiesByTemplateWithPage(TApproveOpninion example, Page page) {
        List<TApproveOpninion> result = (List<TApproveOpninion>)queryForList("T_APPROVE_OPNINION_SqlMap.abatorgenerated_queryEntitiesByTemplate", example,page);
        return result;
    }

    /**
     * 通过主键查询一条记录
     * @abatorgenerated
     */
    public TApproveOpninion selectByPrimaryKey(Long recId) {
        TApproveOpninion key = new TApproveOpninion();
        key.setRecId(recId);
        TApproveOpninion record = (TApproveOpninion) queryForObject("T_APPROVE_OPNINION_SqlMap.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * 通过查询实例，删除数据
     * @abatorgenerated
     */
    public int deleteByExample(TApproveOpninionExample example) {
        int rows = getSqlMapClientTemplate().delete("T_APPROVE_OPNINION_SqlMap.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * 根据Bean数据模板查询条件更新记录
     * @abatorgenerated
     * @param example 条件
     */
    public int deleteByTemplate(TApproveOpninion example) {
        int rows = getSqlMapClientTemplate().delete("T_APPROVE_OPNINION_SqlMap.abatorgenerated_deleteByTemplate", example);
        return rows;
    }

    /**
     * 通过主键删除一条记录
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(Long recId) {
        TApproveOpninion key = new TApproveOpninion();
        key.setRecId(recId);
        int rows = getSqlMapClientTemplate().delete("T_APPROVE_OPNINION_SqlMap.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * 通过查询实例，统计总数
     * @abatorgenerated
     */
    public int countByExample(TApproveOpninionExample example) {
        Integer count = (Integer)  queryForObject("T_APPROVE_OPNINION_SqlMap.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * 通过查询Bean数据模板，统计总数
     * @abatorgenerated
     * @param example 条件
     */
    public int countByTemplate(TApproveOpninion example) {
        Integer rows = (Integer)queryForObject("T_APPROVE_OPNINION_SqlMap.abatorgenerated_countByTemplate", example);
        return rows.intValue();
    }

    /**
     * 通过查询实例，更新非null字段
     * @abatorgenerated
     */
    public int updateByExampleSelective(TApproveOpninion record, TApproveOpninionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_APPROVE_OPNINION_SqlMap.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * 通过查询实例，更新全部字段
     * @abatorgenerated
     */
    public int updateByExample(TApproveOpninion record, TApproveOpninionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_APPROVE_OPNINION_SqlMap.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * 根据Bean数据模板查询条件更新记录
     * @abatorgenerated
     * @param record 值
     * @param example 条件
     */
    public int updateEntityByTemplate(TApproveOpninion record, TApproveOpninion example) {
        HashMap<String,TApproveOpninion> params = new HashMap<String,TApproveOpninion>();
        params.put("record", record);
        params.put("template", example);
        int rows = getSqlMapClientTemplate().update("T_APPROVE_OPNINION_SqlMap.abatorgenerated_updateEntityByTemplate", params);
        return rows;
    }

    /**
     * 分页查询信息
     * @abatorgenerated
     */
    public List selectByDynamic(HashMap map, Page page) throws Exception {
        List list = queryForList("T_APPROVE_OPNINION_SqlMap.abatorgenerated_selectByDynamic", map, page);
        return list;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_APPROVE_OPNINION
     *
     * @abatorgenerated 
     */
    private static class UpdateByExampleParms extends TApproveOpninionExample {
        private Object record;

        public UpdateByExampleParms(Object record, TApproveOpninionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
	@Override
	public List<TApproveOpninion> queryOpninions(HashMap hm, Page page) {
        List<TApproveOpninion> list = null;
		if(page == null){
	        list = queryForList("T_APPROVE_OPNINION_SqlMap.queryOpninions",hm);
		}
		else{
	        list = queryForList("T_APPROVE_OPNINION_SqlMap.queryOpninions",hm,page);
		}
       return list;
	}

	@Override
	public String receiveResourceId(HashMap map) {
		String resourceId = (String) queryForObject("T_APPROVE_OPNINION_SqlMap.receiveResourceId", map);
		return resourceId;
	}
}