package com.gotop.leave.dao.impl;

import com.gotop.leave.dao.ITApplyLeaveDAO;
import com.gotop.leave.model.TApplyLeave;
import com.gotop.leave.model.TApplyLeaveExample;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import org.apache.log4j.Logger;

public class TApplyLeaveDAO extends SqlMapClientDao implements ITApplyLeaveDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TApplyLeaveDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_APPLY_LEAVE
     *
     * @abatorgenerated 
     */
    public TApplyLeaveDAO() {
        super();
    }

    /**
     * 插入一条新数据.
     * @return 
     * @abatorgenerated
     */
    @Override
    public Long insert(TApplyLeave record) throws Exception {
        Long lvId = (Long) getSqlMapClientTemplate().insert("T_APPLY_LEAVE_SqlMap.abatorgenerated_insert", record);
        return lvId;
    }

    
    /*
     * My
     * */
	@Override
	public List selectAllLeave(Page page) throws Exception {
		HashMap<String, Object> map = new HashMap<String, Object>();
		map.put("oracleStart", page.getBegin());
		map.put("oracleEnd", page.getBegin()+page.getLength());
		List leaveList = queryForList("T_APPLY_LEAVE_SqlMap.queryAllLeave", map,page);
		return leaveList;
	}

	@Override
	public List queryByMap(Page page, HashMap<String,Object> map) throws Exception {
		map.put("oracleStart", page.getBegin());
		map.put("oracleEnd", page.getBegin()+page.getLength());
		List leaveList = queryForList("T_APPLY_LEAVE_SqlMap.queryByMap", map,page);
		return leaveList;
	}

	@Override
	public TApplyLeave getLeaveById(Long id) throws Exception {
		TApplyLeave leave = (TApplyLeave) queryForObject("T_APPLY_LEAVE_SqlMap.getLeaveById", id);
		return leave;
	}

	@Override
	public void update(TApplyLeave obj) throws Exception {
		// TODO 自动生成的方法存根
		update("T_APPLY_LEAVE_SqlMap.uodateLeaveById", obj);
		
	}

	@Override
	public TApplyLeave getLeaveByFlowId(String executionId) throws Exception {
		TApplyLeave leave = (TApplyLeave) queryForObject("T_APPLY_LEAVE_SqlMap.getLeaveByFlowId", executionId);
		return leave;
	}
}