package com.gotop.supervise.dao.impl;

import com.gotop.supervise.dao.ITSuperviseTableDAO;
import com.gotop.supervise.model.TSuperviseTable;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.util.HashMap;
import java.util.List;
import org.apache.log4j.Logger;

public class TSuperviseTableDAO extends SqlMapClientDao implements ITSuperviseTableDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TSuperviseTableDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_SUPERVISE_TABLE
     *
     * @abatorgenerated 
     */
    public TSuperviseTableDAO() {
        super();
    }

    /**
     * 新增
     */
	@Override
	public void insertSuperviseTable(TSuperviseTable sup) throws Exception {
		insert("T_SUPERVISE_TABLE_SqlMap.insert_supervise_info", sup);
		
	}

	/**
	 * 查询
	 */
	@Override
	public TSuperviseTable querySuperviseTable(TSuperviseTable sup)
			throws Exception {
	return	(TSuperviseTable) queryForObject("T_SUPERVISE_TABLE_SqlMap.query_supervise_info", sup);
		
	}
	
	/**
	 * 查询
	 */
	@Override
	public TSuperviseTable querySuperviseTable1(TSuperviseTable sup)
			throws Exception {
	return	(TSuperviseTable) queryForObject("T_SUPERVISE_TABLE_SqlMap.query_supervise_info1", sup);
		
	}

	/**
	 * 修改
	 */
	@Override
	public void updateSuperviseTable(TSuperviseTable sup) throws Exception {
		update("T_SUPERVISE_TABLE_SqlMap.update_supervise_info", sup);
		
	}

	@Override
	public List<TSuperviseTable> querySuperviseTables(TSuperviseTable sup,Page page)
			throws Exception {
		
		return queryForList("T_SUPERVISE_TABLE_SqlMap.query_supervise_infos", sup, page);
	}

	@Override
	public void updateSuperviseStatus(TSuperviseTable sup) throws Exception {
	    update("T_SUPERVISE_TABLE_SqlMap.update_supervise_receive_status", sup);
		
	}

	@Override
	public List<TSuperviseTable> queryTaskAssignPerson(
			HashMap<String, Object> hmp) throws Exception {
		return queryForList("T_SUPERVISE_TABLE_SqlMap.queryBushiPerson", hmp);
	}

	
	@Override
	public TSuperviseTable queryTaskAssignZyPerson(
			HashMap<String, Object> hmp) throws Exception {
		List<TSuperviseTable> list=queryForList("T_SUPERVISE_TABLE_SqlMap.queryBushiImpPs", hmp);
		if(list.size()>0){
			return list.get(0);
		}else{
			return null;
		}
	}

	@Override
	public List<TSuperviseTable> queryLeader(HashMap<String, Object> hmp) {
		return queryForList("T_SUPERVISE_TABLE_SqlMap.queryLeader", hmp);
	}

}