package com.gotop.supervise.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TSuperviseTableExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TSuperviseTableExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** */
    public TSuperviseTableExample() {
        oredCriteria = new ArrayList();
    }

    /** */
    protected TSuperviseTableExample(TSuperviseTableExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** */
    /** */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_SUPERVISE_TABLE
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSuperviseIdIsNull() {
            addCriterion("SUPERVISE_ID is null");
            return this;
        }

        public Criteria andSuperviseIdIsNotNull() {
            addCriterion("SUPERVISE_ID is not null");
            return this;
        }

        public Criteria andSuperviseIdEqualTo(Long value) {
            addCriterion("SUPERVISE_ID =", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdNotEqualTo(Long value) {
            addCriterion("SUPERVISE_ID <>", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdGreaterThan(Long value) {
            addCriterion("SUPERVISE_ID >", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SUPERVISE_ID >=", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdLessThan(Long value) {
            addCriterion("SUPERVISE_ID <", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdLessThanOrEqualTo(Long value) {
            addCriterion("SUPERVISE_ID <=", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdIn(List values) {
            addCriterion("SUPERVISE_ID in", values, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdNotIn(List values) {
            addCriterion("SUPERVISE_ID not in", values, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdBetween(Long value1, Long value2) {
            addCriterion("SUPERVISE_ID between", value1, value2, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdNotBetween(Long value1, Long value2) {
            addCriterion("SUPERVISE_ID not between", value1, value2, "superviseId");
            return this;
        }

        public Criteria andFlowIdIsNull() {
            addCriterion("FLOW_ID is null");
            return this;
        }

        public Criteria andFlowIdIsNotNull() {
            addCriterion("FLOW_ID is not null");
            return this;
        }

        public Criteria andFlowIdEqualTo(String value) {
            addCriterion("FLOW_ID =", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotEqualTo(String value) {
            addCriterion("FLOW_ID <>", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThan(String value) {
            addCriterion("FLOW_ID >", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThanOrEqualTo(String value) {
            addCriterion("FLOW_ID >=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThan(String value) {
            addCriterion("FLOW_ID <", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThanOrEqualTo(String value) {
            addCriterion("FLOW_ID <=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLike(String value) {
            addCriterion("FLOW_ID like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotLike(String value) {
            addCriterion("FLOW_ID not like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdIn(List values) {
            addCriterion("FLOW_ID in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdNotIn(List values) {
            addCriterion("FLOW_ID not in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdBetween(String value1, String value2) {
            addCriterion("FLOW_ID between", value1, value2, "flowId");
            return this;
        }

        public Criteria andFlowIdNotBetween(String value1, String value2) {
            addCriterion("FLOW_ID not between", value1, value2, "flowId");
            return this;
        }

        public Criteria andSuperviseItemIsNull() {
            addCriterion("SUPERVISE_ITEM is null");
            return this;
        }

        public Criteria andSuperviseItemIsNotNull() {
            addCriterion("SUPERVISE_ITEM is not null");
            return this;
        }

        public Criteria andSuperviseItemEqualTo(String value) {
            addCriterion("SUPERVISE_ITEM =", value, "superviseItem");
            return this;
        }

        public Criteria andSuperviseItemNotEqualTo(String value) {
            addCriterion("SUPERVISE_ITEM <>", value, "superviseItem");
            return this;
        }

        public Criteria andSuperviseItemGreaterThan(String value) {
            addCriterion("SUPERVISE_ITEM >", value, "superviseItem");
            return this;
        }

        public Criteria andSuperviseItemGreaterThanOrEqualTo(String value) {
            addCriterion("SUPERVISE_ITEM >=", value, "superviseItem");
            return this;
        }

        public Criteria andSuperviseItemLessThan(String value) {
            addCriterion("SUPERVISE_ITEM <", value, "superviseItem");
            return this;
        }

        public Criteria andSuperviseItemLessThanOrEqualTo(String value) {
            addCriterion("SUPERVISE_ITEM <=", value, "superviseItem");
            return this;
        }

        public Criteria andSuperviseItemLike(String value) {
            addCriterion("SUPERVISE_ITEM like", value, "superviseItem");
            return this;
        }

        public Criteria andSuperviseItemNotLike(String value) {
            addCriterion("SUPERVISE_ITEM not like", value, "superviseItem");
            return this;
        }

        public Criteria andSuperviseItemIn(List values) {
            addCriterion("SUPERVISE_ITEM in", values, "superviseItem");
            return this;
        }

        public Criteria andSuperviseItemNotIn(List values) {
            addCriterion("SUPERVISE_ITEM not in", values, "superviseItem");
            return this;
        }

        public Criteria andSuperviseItemBetween(String value1, String value2) {
            addCriterion("SUPERVISE_ITEM between", value1, value2, "superviseItem");
            return this;
        }

        public Criteria andSuperviseItemNotBetween(String value1, String value2) {
            addCriterion("SUPERVISE_ITEM not between", value1, value2, "superviseItem");
            return this;
        }

        public Criteria andContentIsNull() {
            addCriterion("CONTENT is null");
            return this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("CONTENT is not null");
            return this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("CONTENT =", value, "content");
            return this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("CONTENT <>", value, "content");
            return this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("CONTENT >", value, "content");
            return this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT >=", value, "content");
            return this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("CONTENT <", value, "content");
            return this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("CONTENT <=", value, "content");
            return this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("CONTENT like", value, "content");
            return this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("CONTENT not like", value, "content");
            return this;
        }

        public Criteria andContentIn(List values) {
            addCriterion("CONTENT in", values, "content");
            return this;
        }

        public Criteria andContentNotIn(List values) {
            addCriterion("CONTENT not in", values, "content");
            return this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("CONTENT between", value1, value2, "content");
            return this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("CONTENT not between", value1, value2, "content");
            return this;
        }

        public Criteria andImpUnitIsNull() {
            addCriterion("IMP_UNIT is null");
            return this;
        }

        public Criteria andImpUnitIsNotNull() {
            addCriterion("IMP_UNIT is not null");
            return this;
        }

        public Criteria andImpUnitEqualTo(String value) {
            addCriterion("IMP_UNIT =", value, "impUnit");
            return this;
        }

        public Criteria andImpUnitNotEqualTo(String value) {
            addCriterion("IMP_UNIT <>", value, "impUnit");
            return this;
        }

        public Criteria andImpUnitGreaterThan(String value) {
            addCriterion("IMP_UNIT >", value, "impUnit");
            return this;
        }

        public Criteria andImpUnitGreaterThanOrEqualTo(String value) {
            addCriterion("IMP_UNIT >=", value, "impUnit");
            return this;
        }

        public Criteria andImpUnitLessThan(String value) {
            addCriterion("IMP_UNIT <", value, "impUnit");
            return this;
        }

        public Criteria andImpUnitLessThanOrEqualTo(String value) {
            addCriterion("IMP_UNIT <=", value, "impUnit");
            return this;
        }

        public Criteria andImpUnitLike(String value) {
            addCriterion("IMP_UNIT like", value, "impUnit");
            return this;
        }

        public Criteria andImpUnitNotLike(String value) {
            addCriterion("IMP_UNIT not like", value, "impUnit");
            return this;
        }

        public Criteria andImpUnitIn(List values) {
            addCriterion("IMP_UNIT in", values, "impUnit");
            return this;
        }

        public Criteria andImpUnitNotIn(List values) {
            addCriterion("IMP_UNIT not in", values, "impUnit");
            return this;
        }

        public Criteria andImpUnitBetween(String value1, String value2) {
            addCriterion("IMP_UNIT between", value1, value2, "impUnit");
            return this;
        }

        public Criteria andImpUnitNotBetween(String value1, String value2) {
            addCriterion("IMP_UNIT not between", value1, value2, "impUnit");
            return this;
        }

        public Criteria andCoUnitIsNull() {
            addCriterion("CO_UNIT is null");
            return this;
        }

        public Criteria andCoUnitIsNotNull() {
            addCriterion("CO_UNIT is not null");
            return this;
        }

        public Criteria andCoUnitEqualTo(String value) {
            addCriterion("CO_UNIT =", value, "coUnit");
            return this;
        }

        public Criteria andCoUnitNotEqualTo(String value) {
            addCriterion("CO_UNIT <>", value, "coUnit");
            return this;
        }

        public Criteria andCoUnitGreaterThan(String value) {
            addCriterion("CO_UNIT >", value, "coUnit");
            return this;
        }

        public Criteria andCoUnitGreaterThanOrEqualTo(String value) {
            addCriterion("CO_UNIT >=", value, "coUnit");
            return this;
        }

        public Criteria andCoUnitLessThan(String value) {
            addCriterion("CO_UNIT <", value, "coUnit");
            return this;
        }

        public Criteria andCoUnitLessThanOrEqualTo(String value) {
            addCriterion("CO_UNIT <=", value, "coUnit");
            return this;
        }

        public Criteria andCoUnitLike(String value) {
            addCriterion("CO_UNIT like", value, "coUnit");
            return this;
        }

        public Criteria andCoUnitNotLike(String value) {
            addCriterion("CO_UNIT not like", value, "coUnit");
            return this;
        }

        public Criteria andCoUnitIn(List values) {
            addCriterion("CO_UNIT in", values, "coUnit");
            return this;
        }

        public Criteria andCoUnitNotIn(List values) {
            addCriterion("CO_UNIT not in", values, "coUnit");
            return this;
        }

        public Criteria andCoUnitBetween(String value1, String value2) {
            addCriterion("CO_UNIT between", value1, value2, "coUnit");
            return this;
        }

        public Criteria andCoUnitNotBetween(String value1, String value2) {
            addCriterion("CO_UNIT not between", value1, value2, "coUnit");
            return this;
        }

        public Criteria andCompleteDateIsNull() {
            addCriterion("COMPLETE_DATE is null");
            return this;
        }

        public Criteria andCompleteDateIsNotNull() {
            addCriterion("COMPLETE_DATE is not null");
            return this;
        }

        public Criteria andCompleteDateEqualTo(String value) {
            addCriterion("COMPLETE_DATE =", value, "completeDate");
            return this;
        }

        public Criteria andCompleteDateNotEqualTo(String value) {
            addCriterion("COMPLETE_DATE <>", value, "completeDate");
            return this;
        }

        public Criteria andCompleteDateGreaterThan(String value) {
            addCriterion("COMPLETE_DATE >", value, "completeDate");
            return this;
        }

        public Criteria andCompleteDateGreaterThanOrEqualTo(String value) {
            addCriterion("COMPLETE_DATE >=", value, "completeDate");
            return this;
        }

        public Criteria andCompleteDateLessThan(String value) {
            addCriterion("COMPLETE_DATE <", value, "completeDate");
            return this;
        }

        public Criteria andCompleteDateLessThanOrEqualTo(String value) {
            addCriterion("COMPLETE_DATE <=", value, "completeDate");
            return this;
        }

        public Criteria andCompleteDateLike(String value) {
            addCriterion("COMPLETE_DATE like", value, "completeDate");
            return this;
        }

        public Criteria andCompleteDateNotLike(String value) {
            addCriterion("COMPLETE_DATE not like", value, "completeDate");
            return this;
        }

        public Criteria andCompleteDateIn(List values) {
            addCriterion("COMPLETE_DATE in", values, "completeDate");
            return this;
        }

        public Criteria andCompleteDateNotIn(List values) {
            addCriterion("COMPLETE_DATE not in", values, "completeDate");
            return this;
        }

        public Criteria andCompleteDateBetween(String value1, String value2) {
            addCriterion("COMPLETE_DATE between", value1, value2, "completeDate");
            return this;
        }

        public Criteria andCompleteDateNotBetween(String value1, String value2) {
            addCriterion("COMPLETE_DATE not between", value1, value2, "completeDate");
            return this;
        }

        public Criteria andCreateorIsNull() {
            addCriterion("CREATEOR is null");
            return this;
        }

        public Criteria andCreateorIsNotNull() {
            addCriterion("CREATEOR is not null");
            return this;
        }

        public Criteria andCreateorEqualTo(String value) {
            addCriterion("CREATEOR =", value, "createor");
            return this;
        }

        public Criteria andCreateorNotEqualTo(String value) {
            addCriterion("CREATEOR <>", value, "createor");
            return this;
        }

        public Criteria andCreateorGreaterThan(String value) {
            addCriterion("CREATEOR >", value, "createor");
            return this;
        }

        public Criteria andCreateorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEOR >=", value, "createor");
            return this;
        }

        public Criteria andCreateorLessThan(String value) {
            addCriterion("CREATEOR <", value, "createor");
            return this;
        }

        public Criteria andCreateorLessThanOrEqualTo(String value) {
            addCriterion("CREATEOR <=", value, "createor");
            return this;
        }

        public Criteria andCreateorLike(String value) {
            addCriterion("CREATEOR like", value, "createor");
            return this;
        }

        public Criteria andCreateorNotLike(String value) {
            addCriterion("CREATEOR not like", value, "createor");
            return this;
        }

        public Criteria andCreateorIn(List values) {
            addCriterion("CREATEOR in", values, "createor");
            return this;
        }

        public Criteria andCreateorNotIn(List values) {
            addCriterion("CREATEOR not in", values, "createor");
            return this;
        }

        public Criteria andCreateorBetween(String value1, String value2) {
            addCriterion("CREATEOR between", value1, value2, "createor");
            return this;
        }

        public Criteria andCreateorNotBetween(String value1, String value2) {
            addCriterion("CREATEOR not between", value1, value2, "createor");
            return this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateIn(List values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateNotIn(List values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return this;
        }

        public Criteria andLinkerPhoneIsNull() {
            addCriterion("LINKER_PHONE is null");
            return this;
        }

        public Criteria andLinkerPhoneIsNotNull() {
            addCriterion("LINKER_PHONE is not null");
            return this;
        }

        public Criteria andLinkerPhoneEqualTo(String value) {
            addCriterion("LINKER_PHONE =", value, "linkerPhone");
            return this;
        }

        public Criteria andLinkerPhoneNotEqualTo(String value) {
            addCriterion("LINKER_PHONE <>", value, "linkerPhone");
            return this;
        }

        public Criteria andLinkerPhoneGreaterThan(String value) {
            addCriterion("LINKER_PHONE >", value, "linkerPhone");
            return this;
        }

        public Criteria andLinkerPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("LINKER_PHONE >=", value, "linkerPhone");
            return this;
        }

        public Criteria andLinkerPhoneLessThan(String value) {
            addCriterion("LINKER_PHONE <", value, "linkerPhone");
            return this;
        }

        public Criteria andLinkerPhoneLessThanOrEqualTo(String value) {
            addCriterion("LINKER_PHONE <=", value, "linkerPhone");
            return this;
        }

        public Criteria andLinkerPhoneLike(String value) {
            addCriterion("LINKER_PHONE like", value, "linkerPhone");
            return this;
        }

        public Criteria andLinkerPhoneNotLike(String value) {
            addCriterion("LINKER_PHONE not like", value, "linkerPhone");
            return this;
        }

        public Criteria andLinkerPhoneIn(List values) {
            addCriterion("LINKER_PHONE in", values, "linkerPhone");
            return this;
        }

        public Criteria andLinkerPhoneNotIn(List values) {
            addCriterion("LINKER_PHONE not in", values, "linkerPhone");
            return this;
        }

        public Criteria andLinkerPhoneBetween(String value1, String value2) {
            addCriterion("LINKER_PHONE between", value1, value2, "linkerPhone");
            return this;
        }

        public Criteria andLinkerPhoneNotBetween(String value1, String value2) {
            addCriterion("LINKER_PHONE not between", value1, value2, "linkerPhone");
            return this;
        }

        public Criteria andOrgcodeIsNull() {
            addCriterion("ORGCODE is null");
            return this;
        }

        public Criteria andOrgcodeIsNotNull() {
            addCriterion("ORGCODE is not null");
            return this;
        }

        public Criteria andOrgcodeEqualTo(String value) {
            addCriterion("ORGCODE =", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotEqualTo(String value) {
            addCriterion("ORGCODE <>", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeGreaterThan(String value) {
            addCriterion("ORGCODE >", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORGCODE >=", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeLessThan(String value) {
            addCriterion("ORGCODE <", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeLessThanOrEqualTo(String value) {
            addCriterion("ORGCODE <=", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeLike(String value) {
            addCriterion("ORGCODE like", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotLike(String value) {
            addCriterion("ORGCODE not like", value, "orgcode");
            return this;
        }

        public Criteria andOrgcodeIn(List values) {
            addCriterion("ORGCODE in", values, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotIn(List values) {
            addCriterion("ORGCODE not in", values, "orgcode");
            return this;
        }

        public Criteria andOrgcodeBetween(String value1, String value2) {
            addCriterion("ORGCODE between", value1, value2, "orgcode");
            return this;
        }

        public Criteria andOrgcodeNotBetween(String value1, String value2) {
            addCriterion("ORGCODE not between", value1, value2, "orgcode");
            return this;
        }
    }
}