package com.gotop.home.dao.impl;

import com.gotop.home.dao.IHomeInfoDAO;
import com.gotop.home.model.CurrUserInfo;
import com.gotop.home.model.HomeInfo;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import org.apache.log4j.Logger;

public class HomeInfoDAO extends SqlMapClientDao implements IHomeInfoDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(HomeInfoDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table HOME_INFO
     *
     * @abatorgenerated 
     */
    public HomeInfoDAO() {
        super();
    }

    /*
     * 得到当前登录人员的未办信息
     */
    public List<HomeInfo> getEmpMessHomeInfo(CurrUserInfo curruserinfo) throws Exception{
        List<HomeInfo> list= queryForList("HOME_INFO_SqlMap.abatorgenerated_queryHomeMessByEmp", curruserinfo);
        return list;
    }
}