package com.gotop.dataUser.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TRangeUserExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TRangeUserExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public TRangeUserExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected TRangeUserExample(TRangeUserExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_RANGE_USER
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("USER_ID =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("USER_ID <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("USER_ID >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("USER_ID >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("USER_ID <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("USER_ID <=", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("USER_ID in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("USER_ID not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return this;
        }

        public Criteria andResourceIdIsNull() {
            addCriterion("RESOURCE_ID is null");
            return this;
        }

        public Criteria andResourceIdIsNotNull() {
            addCriterion("RESOURCE_ID is not null");
            return this;
        }

        public Criteria andResourceIdEqualTo(Long value) {
            addCriterion("RESOURCE_ID =", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdNotEqualTo(Long value) {
            addCriterion("RESOURCE_ID <>", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdGreaterThan(Long value) {
            addCriterion("RESOURCE_ID >", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("RESOURCE_ID >=", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdLessThan(Long value) {
            addCriterion("RESOURCE_ID <", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdLessThanOrEqualTo(Long value) {
            addCriterion("RESOURCE_ID <=", value, "resourceId");
            return this;
        }

        public Criteria andResourceIdIn(List values) {
            addCriterion("RESOURCE_ID in", values, "resourceId");
            return this;
        }

        public Criteria andResourceIdNotIn(List values) {
            addCriterion("RESOURCE_ID not in", values, "resourceId");
            return this;
        }

        public Criteria andResourceIdBetween(Long value1, Long value2) {
            addCriterion("RESOURCE_ID between", value1, value2, "resourceId");
            return this;
        }

        public Criteria andResourceIdNotBetween(Long value1, Long value2) {
            addCriterion("RESOURCE_ID not between", value1, value2, "resourceId");
            return this;
        }

        public Criteria andEmpIdIsNull() {
            addCriterion("EMP_ID is null");
            return this;
        }

        public Criteria andEmpIdIsNotNull() {
            addCriterion("EMP_ID is not null");
            return this;
        }

        public Criteria andEmpIdEqualTo(Long value) {
            addCriterion("EMP_ID =", value, "empId");
            return this;
        }

        public Criteria andEmpIdNotEqualTo(Long value) {
            addCriterion("EMP_ID <>", value, "empId");
            return this;
        }

        public Criteria andEmpIdGreaterThan(Long value) {
            addCriterion("EMP_ID >", value, "empId");
            return this;
        }

        public Criteria andEmpIdGreaterThanOrEqualTo(Long value) {
            addCriterion("EMP_ID >=", value, "empId");
            return this;
        }

        public Criteria andEmpIdLessThan(Long value) {
            addCriterion("EMP_ID <", value, "empId");
            return this;
        }

        public Criteria andEmpIdLessThanOrEqualTo(Long value) {
            addCriterion("EMP_ID <=", value, "empId");
            return this;
        }

        public Criteria andEmpIdIn(List values) {
            addCriterion("EMP_ID in", values, "empId");
            return this;
        }

        public Criteria andEmpIdNotIn(List values) {
            addCriterion("EMP_ID not in", values, "empId");
            return this;
        }

        public Criteria andEmpIdBetween(Long value1, Long value2) {
            addCriterion("EMP_ID between", value1, value2, "empId");
            return this;
        }

        public Criteria andEmpIdNotBetween(Long value1, Long value2) {
            addCriterion("EMP_ID not between", value1, value2, "empId");
            return this;
        }

        public Criteria andResourceTypeIsNull() {
            addCriterion("RESOURCE_TYPE is null");
            return this;
        }

        public Criteria andResourceTypeIsNotNull() {
            addCriterion("RESOURCE_TYPE is not null");
            return this;
        }

        public Criteria andResourceTypeEqualTo(String value) {
            addCriterion("RESOURCE_TYPE =", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeNotEqualTo(String value) {
            addCriterion("RESOURCE_TYPE <>", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeGreaterThan(String value) {
            addCriterion("RESOURCE_TYPE >", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("RESOURCE_TYPE >=", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeLessThan(String value) {
            addCriterion("RESOURCE_TYPE <", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeLessThanOrEqualTo(String value) {
            addCriterion("RESOURCE_TYPE <=", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeLike(String value) {
            addCriterion("RESOURCE_TYPE like", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeNotLike(String value) {
            addCriterion("RESOURCE_TYPE not like", value, "resourceType");
            return this;
        }

        public Criteria andResourceTypeIn(List values) {
            addCriterion("RESOURCE_TYPE in", values, "resourceType");
            return this;
        }

        public Criteria andResourceTypeNotIn(List values) {
            addCriterion("RESOURCE_TYPE not in", values, "resourceType");
            return this;
        }

        public Criteria andResourceTypeBetween(String value1, String value2) {
            addCriterion("RESOURCE_TYPE between", value1, value2, "resourceType");
            return this;
        }

        public Criteria andResourceTypeNotBetween(String value1, String value2) {
            addCriterion("RESOURCE_TYPE not between", value1, value2, "resourceType");
            return this;
        }

        public Criteria andDesIdIsNull() {
            addCriterion("DES_ID is null");
            return this;
        }

        public Criteria andDesIdIsNotNull() {
            addCriterion("DES_ID is not null");
            return this;
        }

        public Criteria andDesIdEqualTo(Long value) {
            addCriterion("DES_ID =", value, "desId");
            return this;
        }

        public Criteria andDesIdNotEqualTo(Long value) {
            addCriterion("DES_ID <>", value, "desId");
            return this;
        }

        public Criteria andDesIdGreaterThan(Long value) {
            addCriterion("DES_ID >", value, "desId");
            return this;
        }

        public Criteria andDesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DES_ID >=", value, "desId");
            return this;
        }

        public Criteria andDesIdLessThan(Long value) {
            addCriterion("DES_ID <", value, "desId");
            return this;
        }

        public Criteria andDesIdLessThanOrEqualTo(Long value) {
            addCriterion("DES_ID <=", value, "desId");
            return this;
        }

        public Criteria andDesIdIn(List values) {
            addCriterion("DES_ID in", values, "desId");
            return this;
        }

        public Criteria andDesIdNotIn(List values) {
            addCriterion("DES_ID not in", values, "desId");
            return this;
        }

        public Criteria andDesIdBetween(Long value1, Long value2) {
            addCriterion("DES_ID between", value1, value2, "desId");
            return this;
        }

        public Criteria andDesIdNotBetween(Long value1, Long value2) {
            addCriterion("DES_ID not between", value1, value2, "desId");
            return this;
        }

        public Criteria andDesTimeIsNull() {
            addCriterion("DES_TIME is null");
            return this;
        }

        public Criteria andDesTimeIsNotNull() {
            addCriterion("DES_TIME is not null");
            return this;
        }

        public Criteria andDesTimeEqualTo(String value) {
            addCriterion("DES_TIME =", value, "desTime");
            return this;
        }

        public Criteria andDesTimeNotEqualTo(String value) {
            addCriterion("DES_TIME <>", value, "desTime");
            return this;
        }

        public Criteria andDesTimeGreaterThan(String value) {
            addCriterion("DES_TIME >", value, "desTime");
            return this;
        }

        public Criteria andDesTimeGreaterThanOrEqualTo(String value) {
            addCriterion("DES_TIME >=", value, "desTime");
            return this;
        }

        public Criteria andDesTimeLessThan(String value) {
            addCriterion("DES_TIME <", value, "desTime");
            return this;
        }

        public Criteria andDesTimeLessThanOrEqualTo(String value) {
            addCriterion("DES_TIME <=", value, "desTime");
            return this;
        }

        public Criteria andDesTimeLike(String value) {
            addCriterion("DES_TIME like", value, "desTime");
            return this;
        }

        public Criteria andDesTimeNotLike(String value) {
            addCriterion("DES_TIME not like", value, "desTime");
            return this;
        }

        public Criteria andDesTimeIn(List values) {
            addCriterion("DES_TIME in", values, "desTime");
            return this;
        }

        public Criteria andDesTimeNotIn(List values) {
            addCriterion("DES_TIME not in", values, "desTime");
            return this;
        }

        public Criteria andDesTimeBetween(String value1, String value2) {
            addCriterion("DES_TIME between", value1, value2, "desTime");
            return this;
        }

        public Criteria andDesTimeNotBetween(String value1, String value2) {
            addCriterion("DES_TIME not between", value1, value2, "desTime");
            return this;
        }

        public Criteria andDesDateIsNull() {
            addCriterion("DES_DATE is null");
            return this;
        }

        public Criteria andDesDateIsNotNull() {
            addCriterion("DES_DATE is not null");
            return this;
        }

        public Criteria andDesDateEqualTo(String value) {
            addCriterion("DES_DATE =", value, "desDate");
            return this;
        }

        public Criteria andDesDateNotEqualTo(String value) {
            addCriterion("DES_DATE <>", value, "desDate");
            return this;
        }

        public Criteria andDesDateGreaterThan(String value) {
            addCriterion("DES_DATE >", value, "desDate");
            return this;
        }

        public Criteria andDesDateGreaterThanOrEqualTo(String value) {
            addCriterion("DES_DATE >=", value, "desDate");
            return this;
        }

        public Criteria andDesDateLessThan(String value) {
            addCriterion("DES_DATE <", value, "desDate");
            return this;
        }

        public Criteria andDesDateLessThanOrEqualTo(String value) {
            addCriterion("DES_DATE <=", value, "desDate");
            return this;
        }

        public Criteria andDesDateLike(String value) {
            addCriterion("DES_DATE like", value, "desDate");
            return this;
        }

        public Criteria andDesDateNotLike(String value) {
            addCriterion("DES_DATE not like", value, "desDate");
            return this;
        }

        public Criteria andDesDateIn(List values) {
            addCriterion("DES_DATE in", values, "desDate");
            return this;
        }

        public Criteria andDesDateNotIn(List values) {
            addCriterion("DES_DATE not in", values, "desDate");
            return this;
        }

        public Criteria andDesDateBetween(String value1, String value2) {
            addCriterion("DES_DATE between", value1, value2, "desDate");
            return this;
        }

        public Criteria andDesDateNotBetween(String value1, String value2) {
            addCriterion("DES_DATE not between", value1, value2, "desDate");
            return this;
        }
    }
}