package com.gotop.jbpm.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class Jbpm4ExecutionExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(Jbpm4ExecutionExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public Jbpm4ExecutionExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected Jbpm4ExecutionExample(Jbpm4ExecutionExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table JBPM4_EXECUTION
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andDbidIsNull() {
            addCriterion("DBID_ is null");
            return this;
        }

        public Criteria andDbidIsNotNull() {
            addCriterion("DBID_ is not null");
            return this;
        }

        public Criteria andDbidEqualTo(BigDecimal value) {
            addCriterion("DBID_ =", value, "dbid");
            return this;
        }

        public Criteria andDbidNotEqualTo(BigDecimal value) {
            addCriterion("DBID_ <>", value, "dbid");
            return this;
        }

        public Criteria andDbidGreaterThan(BigDecimal value) {
            addCriterion("DBID_ >", value, "dbid");
            return this;
        }

        public Criteria andDbidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DBID_ >=", value, "dbid");
            return this;
        }

        public Criteria andDbidLessThan(BigDecimal value) {
            addCriterion("DBID_ <", value, "dbid");
            return this;
        }

        public Criteria andDbidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DBID_ <=", value, "dbid");
            return this;
        }

        public Criteria andDbidIn(List values) {
            addCriterion("DBID_ in", values, "dbid");
            return this;
        }

        public Criteria andDbidNotIn(List values) {
            addCriterion("DBID_ not in", values, "dbid");
            return this;
        }

        public Criteria andDbidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DBID_ between", value1, value2, "dbid");
            return this;
        }

        public Criteria andDbidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DBID_ not between", value1, value2, "dbid");
            return this;
        }

        public Criteria andClassIsNull() {
            addCriterion("CLASS_ is null");
            return this;
        }

        public Criteria andClassIsNotNull() {
            addCriterion("CLASS_ is not null");
            return this;
        }

        public Criteria andClassEqualTo(String value) {
            addCriterion("CLASS_ =", value, "class");
            return this;
        }

        public Criteria andClassNotEqualTo(String value) {
            addCriterion("CLASS_ <>", value, "class");
            return this;
        }

        public Criteria andClassGreaterThan(String value) {
            addCriterion("CLASS_ >", value, "class");
            return this;
        }

        public Criteria andClassGreaterThanOrEqualTo(String value) {
            addCriterion("CLASS_ >=", value, "class");
            return this;
        }

        public Criteria andClassLessThan(String value) {
            addCriterion("CLASS_ <", value, "class");
            return this;
        }

        public Criteria andClassLessThanOrEqualTo(String value) {
            addCriterion("CLASS_ <=", value, "class");
            return this;
        }

        public Criteria andClassLike(String value) {
            addCriterion("CLASS_ like", value, "class");
            return this;
        }

        public Criteria andClassNotLike(String value) {
            addCriterion("CLASS_ not like", value, "class");
            return this;
        }

        public Criteria andClassIn(List values) {
            addCriterion("CLASS_ in", values, "class");
            return this;
        }

        public Criteria andClassNotIn(List values) {
            addCriterion("CLASS_ not in", values, "class");
            return this;
        }

        public Criteria andClassBetween(String value1, String value2) {
            addCriterion("CLASS_ between", value1, value2, "class");
            return this;
        }

        public Criteria andClassNotBetween(String value1, String value2) {
            addCriterion("CLASS_ not between", value1, value2, "class");
            return this;
        }

        public Criteria andDbversionIsNull() {
            addCriterion("DBVERSION_ is null");
            return this;
        }

        public Criteria andDbversionIsNotNull() {
            addCriterion("DBVERSION_ is not null");
            return this;
        }

        public Criteria andDbversionEqualTo(Long value) {
            addCriterion("DBVERSION_ =", value, "dbversion");
            return this;
        }

        public Criteria andDbversionNotEqualTo(Long value) {
            addCriterion("DBVERSION_ <>", value, "dbversion");
            return this;
        }

        public Criteria andDbversionGreaterThan(Long value) {
            addCriterion("DBVERSION_ >", value, "dbversion");
            return this;
        }

        public Criteria andDbversionGreaterThanOrEqualTo(Long value) {
            addCriterion("DBVERSION_ >=", value, "dbversion");
            return this;
        }

        public Criteria andDbversionLessThan(Long value) {
            addCriterion("DBVERSION_ <", value, "dbversion");
            return this;
        }

        public Criteria andDbversionLessThanOrEqualTo(Long value) {
            addCriterion("DBVERSION_ <=", value, "dbversion");
            return this;
        }

        public Criteria andDbversionIn(List values) {
            addCriterion("DBVERSION_ in", values, "dbversion");
            return this;
        }

        public Criteria andDbversionNotIn(List values) {
            addCriterion("DBVERSION_ not in", values, "dbversion");
            return this;
        }

        public Criteria andDbversionBetween(Long value1, Long value2) {
            addCriterion("DBVERSION_ between", value1, value2, "dbversion");
            return this;
        }

        public Criteria andDbversionNotBetween(Long value1, Long value2) {
            addCriterion("DBVERSION_ not between", value1, value2, "dbversion");
            return this;
        }

        public Criteria andActivitynameIsNull() {
            addCriterion("ACTIVITYNAME_ is null");
            return this;
        }

        public Criteria andActivitynameIsNotNull() {
            addCriterion("ACTIVITYNAME_ is not null");
            return this;
        }

        public Criteria andActivitynameEqualTo(String value) {
            addCriterion("ACTIVITYNAME_ =", value, "activityname");
            return this;
        }

        public Criteria andActivitynameNotEqualTo(String value) {
            addCriterion("ACTIVITYNAME_ <>", value, "activityname");
            return this;
        }

        public Criteria andActivitynameGreaterThan(String value) {
            addCriterion("ACTIVITYNAME_ >", value, "activityname");
            return this;
        }

        public Criteria andActivitynameGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVITYNAME_ >=", value, "activityname");
            return this;
        }

        public Criteria andActivitynameLessThan(String value) {
            addCriterion("ACTIVITYNAME_ <", value, "activityname");
            return this;
        }

        public Criteria andActivitynameLessThanOrEqualTo(String value) {
            addCriterion("ACTIVITYNAME_ <=", value, "activityname");
            return this;
        }

        public Criteria andActivitynameLike(String value) {
            addCriterion("ACTIVITYNAME_ like", value, "activityname");
            return this;
        }

        public Criteria andActivitynameNotLike(String value) {
            addCriterion("ACTIVITYNAME_ not like", value, "activityname");
            return this;
        }

        public Criteria andActivitynameIn(List values) {
            addCriterion("ACTIVITYNAME_ in", values, "activityname");
            return this;
        }

        public Criteria andActivitynameNotIn(List values) {
            addCriterion("ACTIVITYNAME_ not in", values, "activityname");
            return this;
        }

        public Criteria andActivitynameBetween(String value1, String value2) {
            addCriterion("ACTIVITYNAME_ between", value1, value2, "activityname");
            return this;
        }

        public Criteria andActivitynameNotBetween(String value1, String value2) {
            addCriterion("ACTIVITYNAME_ not between", value1, value2, "activityname");
            return this;
        }

        public Criteria andProcdefidIsNull() {
            addCriterion("PROCDEFID_ is null");
            return this;
        }

        public Criteria andProcdefidIsNotNull() {
            addCriterion("PROCDEFID_ is not null");
            return this;
        }

        public Criteria andProcdefidEqualTo(String value) {
            addCriterion("PROCDEFID_ =", value, "procdefid");
            return this;
        }

        public Criteria andProcdefidNotEqualTo(String value) {
            addCriterion("PROCDEFID_ <>", value, "procdefid");
            return this;
        }

        public Criteria andProcdefidGreaterThan(String value) {
            addCriterion("PROCDEFID_ >", value, "procdefid");
            return this;
        }

        public Criteria andProcdefidGreaterThanOrEqualTo(String value) {
            addCriterion("PROCDEFID_ >=", value, "procdefid");
            return this;
        }

        public Criteria andProcdefidLessThan(String value) {
            addCriterion("PROCDEFID_ <", value, "procdefid");
            return this;
        }

        public Criteria andProcdefidLessThanOrEqualTo(String value) {
            addCriterion("PROCDEFID_ <=", value, "procdefid");
            return this;
        }

        public Criteria andProcdefidLike(String value) {
            addCriterion("PROCDEFID_ like", value, "procdefid");
            return this;
        }

        public Criteria andProcdefidNotLike(String value) {
            addCriterion("PROCDEFID_ not like", value, "procdefid");
            return this;
        }

        public Criteria andProcdefidIn(List values) {
            addCriterion("PROCDEFID_ in", values, "procdefid");
            return this;
        }

        public Criteria andProcdefidNotIn(List values) {
            addCriterion("PROCDEFID_ not in", values, "procdefid");
            return this;
        }

        public Criteria andProcdefidBetween(String value1, String value2) {
            addCriterion("PROCDEFID_ between", value1, value2, "procdefid");
            return this;
        }

        public Criteria andProcdefidNotBetween(String value1, String value2) {
            addCriterion("PROCDEFID_ not between", value1, value2, "procdefid");
            return this;
        }

        public Criteria andHasvarsIsNull() {
            addCriterion("HASVARS_ is null");
            return this;
        }

        public Criteria andHasvarsIsNotNull() {
            addCriterion("HASVARS_ is not null");
            return this;
        }

        public Criteria andHasvarsEqualTo(Integer value) {
            addCriterion("HASVARS_ =", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsNotEqualTo(Integer value) {
            addCriterion("HASVARS_ <>", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsGreaterThan(Integer value) {
            addCriterion("HASVARS_ >", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsGreaterThanOrEqualTo(Integer value) {
            addCriterion("HASVARS_ >=", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsLessThan(Integer value) {
            addCriterion("HASVARS_ <", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsLessThanOrEqualTo(Integer value) {
            addCriterion("HASVARS_ <=", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsIn(List values) {
            addCriterion("HASVARS_ in", values, "hasvars");
            return this;
        }

        public Criteria andHasvarsNotIn(List values) {
            addCriterion("HASVARS_ not in", values, "hasvars");
            return this;
        }

        public Criteria andHasvarsBetween(Integer value1, Integer value2) {
            addCriterion("HASVARS_ between", value1, value2, "hasvars");
            return this;
        }

        public Criteria andHasvarsNotBetween(Integer value1, Integer value2) {
            addCriterion("HASVARS_ not between", value1, value2, "hasvars");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME_ is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME_ is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME_ =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME_ <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME_ >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME_ >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME_ <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME_ <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME_ like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME_ not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("NAME_ in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("NAME_ not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME_ between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME_ not between", value1, value2, "name");
            return this;
        }

        public Criteria andKeyIsNull() {
            addCriterion("KEY_ is null");
            return this;
        }

        public Criteria andKeyIsNotNull() {
            addCriterion("KEY_ is not null");
            return this;
        }

        public Criteria andKeyEqualTo(String value) {
            addCriterion("KEY_ =", value, "key");
            return this;
        }

        public Criteria andKeyNotEqualTo(String value) {
            addCriterion("KEY_ <>", value, "key");
            return this;
        }

        public Criteria andKeyGreaterThan(String value) {
            addCriterion("KEY_ >", value, "key");
            return this;
        }

        public Criteria andKeyGreaterThanOrEqualTo(String value) {
            addCriterion("KEY_ >=", value, "key");
            return this;
        }

        public Criteria andKeyLessThan(String value) {
            addCriterion("KEY_ <", value, "key");
            return this;
        }

        public Criteria andKeyLessThanOrEqualTo(String value) {
            addCriterion("KEY_ <=", value, "key");
            return this;
        }

        public Criteria andKeyLike(String value) {
            addCriterion("KEY_ like", value, "key");
            return this;
        }

        public Criteria andKeyNotLike(String value) {
            addCriterion("KEY_ not like", value, "key");
            return this;
        }

        public Criteria andKeyIn(List values) {
            addCriterion("KEY_ in", values, "key");
            return this;
        }

        public Criteria andKeyNotIn(List values) {
            addCriterion("KEY_ not in", values, "key");
            return this;
        }

        public Criteria andKeyBetween(String value1, String value2) {
            addCriterion("KEY_ between", value1, value2, "key");
            return this;
        }

        public Criteria andKeyNotBetween(String value1, String value2) {
            addCriterion("KEY_ not between", value1, value2, "key");
            return this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID_ is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID_ is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID_ =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID_ <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID_ >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID_ >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID_ <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID_ <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID_ like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID_ not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID_ in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID_ not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID_ between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID_ not between", value1, value2, "id");
            return this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE_ is null");
            return this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE_ is not null");
            return this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE_ =", value, "state");
            return this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE_ <>", value, "state");
            return this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE_ >", value, "state");
            return this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE_ >=", value, "state");
            return this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE_ <", value, "state");
            return this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE_ <=", value, "state");
            return this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE_ like", value, "state");
            return this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE_ not like", value, "state");
            return this;
        }

        public Criteria andStateIn(List values) {
            addCriterion("STATE_ in", values, "state");
            return this;
        }

        public Criteria andStateNotIn(List values) {
            addCriterion("STATE_ not in", values, "state");
            return this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE_ between", value1, value2, "state");
            return this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE_ not between", value1, value2, "state");
            return this;
        }

        public Criteria andSusphiststateIsNull() {
            addCriterion("SUSPHISTSTATE_ is null");
            return this;
        }

        public Criteria andSusphiststateIsNotNull() {
            addCriterion("SUSPHISTSTATE_ is not null");
            return this;
        }

        public Criteria andSusphiststateEqualTo(String value) {
            addCriterion("SUSPHISTSTATE_ =", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateNotEqualTo(String value) {
            addCriterion("SUSPHISTSTATE_ <>", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateGreaterThan(String value) {
            addCriterion("SUSPHISTSTATE_ >", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateGreaterThanOrEqualTo(String value) {
            addCriterion("SUSPHISTSTATE_ >=", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateLessThan(String value) {
            addCriterion("SUSPHISTSTATE_ <", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateLessThanOrEqualTo(String value) {
            addCriterion("SUSPHISTSTATE_ <=", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateLike(String value) {
            addCriterion("SUSPHISTSTATE_ like", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateNotLike(String value) {
            addCriterion("SUSPHISTSTATE_ not like", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateIn(List values) {
            addCriterion("SUSPHISTSTATE_ in", values, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateNotIn(List values) {
            addCriterion("SUSPHISTSTATE_ not in", values, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateBetween(String value1, String value2) {
            addCriterion("SUSPHISTSTATE_ between", value1, value2, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateNotBetween(String value1, String value2) {
            addCriterion("SUSPHISTSTATE_ not between", value1, value2, "susphiststate");
            return this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("PRIORITY_ is null");
            return this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("PRIORITY_ is not null");
            return this;
        }

        public Criteria andPriorityEqualTo(Long value) {
            addCriterion("PRIORITY_ =", value, "priority");
            return this;
        }

        public Criteria andPriorityNotEqualTo(Long value) {
            addCriterion("PRIORITY_ <>", value, "priority");
            return this;
        }

        public Criteria andPriorityGreaterThan(Long value) {
            addCriterion("PRIORITY_ >", value, "priority");
            return this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Long value) {
            addCriterion("PRIORITY_ >=", value, "priority");
            return this;
        }

        public Criteria andPriorityLessThan(Long value) {
            addCriterion("PRIORITY_ <", value, "priority");
            return this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Long value) {
            addCriterion("PRIORITY_ <=", value, "priority");
            return this;
        }

        public Criteria andPriorityIn(List values) {
            addCriterion("PRIORITY_ in", values, "priority");
            return this;
        }

        public Criteria andPriorityNotIn(List values) {
            addCriterion("PRIORITY_ not in", values, "priority");
            return this;
        }

        public Criteria andPriorityBetween(Long value1, Long value2) {
            addCriterion("PRIORITY_ between", value1, value2, "priority");
            return this;
        }

        public Criteria andPriorityNotBetween(Long value1, Long value2) {
            addCriterion("PRIORITY_ not between", value1, value2, "priority");
            return this;
        }

        public Criteria andHisactinstIsNull() {
            addCriterion("HISACTINST_ is null");
            return this;
        }

        public Criteria andHisactinstIsNotNull() {
            addCriterion("HISACTINST_ is not null");
            return this;
        }

        public Criteria andHisactinstEqualTo(BigDecimal value) {
            addCriterion("HISACTINST_ =", value, "hisactinst");
            return this;
        }

        public Criteria andHisactinstNotEqualTo(BigDecimal value) {
            addCriterion("HISACTINST_ <>", value, "hisactinst");
            return this;
        }

        public Criteria andHisactinstGreaterThan(BigDecimal value) {
            addCriterion("HISACTINST_ >", value, "hisactinst");
            return this;
        }

        public Criteria andHisactinstGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HISACTINST_ >=", value, "hisactinst");
            return this;
        }

        public Criteria andHisactinstLessThan(BigDecimal value) {
            addCriterion("HISACTINST_ <", value, "hisactinst");
            return this;
        }

        public Criteria andHisactinstLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HISACTINST_ <=", value, "hisactinst");
            return this;
        }

        public Criteria andHisactinstIn(List values) {
            addCriterion("HISACTINST_ in", values, "hisactinst");
            return this;
        }

        public Criteria andHisactinstNotIn(List values) {
            addCriterion("HISACTINST_ not in", values, "hisactinst");
            return this;
        }

        public Criteria andHisactinstBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HISACTINST_ between", value1, value2, "hisactinst");
            return this;
        }

        public Criteria andHisactinstNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HISACTINST_ not between", value1, value2, "hisactinst");
            return this;
        }

        public Criteria andParentIsNull() {
            addCriterion("PARENT_ is null");
            return this;
        }

        public Criteria andParentIsNotNull() {
            addCriterion("PARENT_ is not null");
            return this;
        }

        public Criteria andParentEqualTo(BigDecimal value) {
            addCriterion("PARENT_ =", value, "parent");
            return this;
        }

        public Criteria andParentNotEqualTo(BigDecimal value) {
            addCriterion("PARENT_ <>", value, "parent");
            return this;
        }

        public Criteria andParentGreaterThan(BigDecimal value) {
            addCriterion("PARENT_ >", value, "parent");
            return this;
        }

        public Criteria andParentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PARENT_ >=", value, "parent");
            return this;
        }

        public Criteria andParentLessThan(BigDecimal value) {
            addCriterion("PARENT_ <", value, "parent");
            return this;
        }

        public Criteria andParentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PARENT_ <=", value, "parent");
            return this;
        }

        public Criteria andParentIn(List values) {
            addCriterion("PARENT_ in", values, "parent");
            return this;
        }

        public Criteria andParentNotIn(List values) {
            addCriterion("PARENT_ not in", values, "parent");
            return this;
        }

        public Criteria andParentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PARENT_ between", value1, value2, "parent");
            return this;
        }

        public Criteria andParentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PARENT_ not between", value1, value2, "parent");
            return this;
        }

        public Criteria andInstanceIsNull() {
            addCriterion("INSTANCE_ is null");
            return this;
        }

        public Criteria andInstanceIsNotNull() {
            addCriterion("INSTANCE_ is not null");
            return this;
        }

        public Criteria andInstanceEqualTo(BigDecimal value) {
            addCriterion("INSTANCE_ =", value, "instance");
            return this;
        }

        public Criteria andInstanceNotEqualTo(BigDecimal value) {
            addCriterion("INSTANCE_ <>", value, "instance");
            return this;
        }

        public Criteria andInstanceGreaterThan(BigDecimal value) {
            addCriterion("INSTANCE_ >", value, "instance");
            return this;
        }

        public Criteria andInstanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INSTANCE_ >=", value, "instance");
            return this;
        }

        public Criteria andInstanceLessThan(BigDecimal value) {
            addCriterion("INSTANCE_ <", value, "instance");
            return this;
        }

        public Criteria andInstanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INSTANCE_ <=", value, "instance");
            return this;
        }

        public Criteria andInstanceIn(List values) {
            addCriterion("INSTANCE_ in", values, "instance");
            return this;
        }

        public Criteria andInstanceNotIn(List values) {
            addCriterion("INSTANCE_ not in", values, "instance");
            return this;
        }

        public Criteria andInstanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INSTANCE_ between", value1, value2, "instance");
            return this;
        }

        public Criteria andInstanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INSTANCE_ not between", value1, value2, "instance");
            return this;
        }

        public Criteria andSuperexecIsNull() {
            addCriterion("SUPEREXEC_ is null");
            return this;
        }

        public Criteria andSuperexecIsNotNull() {
            addCriterion("SUPEREXEC_ is not null");
            return this;
        }

        public Criteria andSuperexecEqualTo(BigDecimal value) {
            addCriterion("SUPEREXEC_ =", value, "superexec");
            return this;
        }

        public Criteria andSuperexecNotEqualTo(BigDecimal value) {
            addCriterion("SUPEREXEC_ <>", value, "superexec");
            return this;
        }

        public Criteria andSuperexecGreaterThan(BigDecimal value) {
            addCriterion("SUPEREXEC_ >", value, "superexec");
            return this;
        }

        public Criteria andSuperexecGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUPEREXEC_ >=", value, "superexec");
            return this;
        }

        public Criteria andSuperexecLessThan(BigDecimal value) {
            addCriterion("SUPEREXEC_ <", value, "superexec");
            return this;
        }

        public Criteria andSuperexecLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUPEREXEC_ <=", value, "superexec");
            return this;
        }

        public Criteria andSuperexecIn(List values) {
            addCriterion("SUPEREXEC_ in", values, "superexec");
            return this;
        }

        public Criteria andSuperexecNotIn(List values) {
            addCriterion("SUPEREXEC_ not in", values, "superexec");
            return this;
        }

        public Criteria andSuperexecBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUPEREXEC_ between", value1, value2, "superexec");
            return this;
        }

        public Criteria andSuperexecNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUPEREXEC_ not between", value1, value2, "superexec");
            return this;
        }

        public Criteria andSubprocinstIsNull() {
            addCriterion("SUBPROCINST_ is null");
            return this;
        }

        public Criteria andSubprocinstIsNotNull() {
            addCriterion("SUBPROCINST_ is not null");
            return this;
        }

        public Criteria andSubprocinstEqualTo(BigDecimal value) {
            addCriterion("SUBPROCINST_ =", value, "subprocinst");
            return this;
        }

        public Criteria andSubprocinstNotEqualTo(BigDecimal value) {
            addCriterion("SUBPROCINST_ <>", value, "subprocinst");
            return this;
        }

        public Criteria andSubprocinstGreaterThan(BigDecimal value) {
            addCriterion("SUBPROCINST_ >", value, "subprocinst");
            return this;
        }

        public Criteria andSubprocinstGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUBPROCINST_ >=", value, "subprocinst");
            return this;
        }

        public Criteria andSubprocinstLessThan(BigDecimal value) {
            addCriterion("SUBPROCINST_ <", value, "subprocinst");
            return this;
        }

        public Criteria andSubprocinstLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUBPROCINST_ <=", value, "subprocinst");
            return this;
        }

        public Criteria andSubprocinstIn(List values) {
            addCriterion("SUBPROCINST_ in", values, "subprocinst");
            return this;
        }

        public Criteria andSubprocinstNotIn(List values) {
            addCriterion("SUBPROCINST_ not in", values, "subprocinst");
            return this;
        }

        public Criteria andSubprocinstBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUBPROCINST_ between", value1, value2, "subprocinst");
            return this;
        }

        public Criteria andSubprocinstNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUBPROCINST_ not between", value1, value2, "subprocinst");
            return this;
        }

        public Criteria andParentIdxIsNull() {
            addCriterion("PARENT_IDX_ is null");
            return this;
        }

        public Criteria andParentIdxIsNotNull() {
            addCriterion("PARENT_IDX_ is not null");
            return this;
        }

        public Criteria andParentIdxEqualTo(Long value) {
            addCriterion("PARENT_IDX_ =", value, "parentIdx");
            return this;
        }

        public Criteria andParentIdxNotEqualTo(Long value) {
            addCriterion("PARENT_IDX_ <>", value, "parentIdx");
            return this;
        }

        public Criteria andParentIdxGreaterThan(Long value) {
            addCriterion("PARENT_IDX_ >", value, "parentIdx");
            return this;
        }

        public Criteria andParentIdxGreaterThanOrEqualTo(Long value) {
            addCriterion("PARENT_IDX_ >=", value, "parentIdx");
            return this;
        }

        public Criteria andParentIdxLessThan(Long value) {
            addCriterion("PARENT_IDX_ <", value, "parentIdx");
            return this;
        }

        public Criteria andParentIdxLessThanOrEqualTo(Long value) {
            addCriterion("PARENT_IDX_ <=", value, "parentIdx");
            return this;
        }

        public Criteria andParentIdxIn(List values) {
            addCriterion("PARENT_IDX_ in", values, "parentIdx");
            return this;
        }

        public Criteria andParentIdxNotIn(List values) {
            addCriterion("PARENT_IDX_ not in", values, "parentIdx");
            return this;
        }

        public Criteria andParentIdxBetween(Long value1, Long value2) {
            addCriterion("PARENT_IDX_ between", value1, value2, "parentIdx");
            return this;
        }

        public Criteria andParentIdxNotBetween(Long value1, Long value2) {
            addCriterion("PARENT_IDX_ not between", value1, value2, "parentIdx");
            return this;
        }
    }
}