package com.gotop.jbpm.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class Jbpm4HistTaskExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(Jbpm4HistTaskExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public Jbpm4HistTaskExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected Jbpm4HistTaskExample(Jbpm4HistTaskExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table JBPM4_HIST_TASK
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andDbidIsNull() {
            addCriterion("DBID_ is null");
            return this;
        }

        public Criteria andDbidIsNotNull() {
            addCriterion("DBID_ is not null");
            return this;
        }

        public Criteria andDbidEqualTo(BigDecimal value) {
            addCriterion("DBID_ =", value, "dbid");
            return this;
        }

        public Criteria andDbidNotEqualTo(BigDecimal value) {
            addCriterion("DBID_ <>", value, "dbid");
            return this;
        }

        public Criteria andDbidGreaterThan(BigDecimal value) {
            addCriterion("DBID_ >", value, "dbid");
            return this;
        }

        public Criteria andDbidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DBID_ >=", value, "dbid");
            return this;
        }

        public Criteria andDbidLessThan(BigDecimal value) {
            addCriterion("DBID_ <", value, "dbid");
            return this;
        }

        public Criteria andDbidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DBID_ <=", value, "dbid");
            return this;
        }

        public Criteria andDbidIn(List values) {
            addCriterion("DBID_ in", values, "dbid");
            return this;
        }

        public Criteria andDbidNotIn(List values) {
            addCriterion("DBID_ not in", values, "dbid");
            return this;
        }

        public Criteria andDbidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DBID_ between", value1, value2, "dbid");
            return this;
        }

        public Criteria andDbidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DBID_ not between", value1, value2, "dbid");
            return this;
        }

        public Criteria andDbversionIsNull() {
            addCriterion("DBVERSION_ is null");
            return this;
        }

        public Criteria andDbversionIsNotNull() {
            addCriterion("DBVERSION_ is not null");
            return this;
        }

        public Criteria andDbversionEqualTo(Long value) {
            addCriterion("DBVERSION_ =", value, "dbversion");
            return this;
        }

        public Criteria andDbversionNotEqualTo(Long value) {
            addCriterion("DBVERSION_ <>", value, "dbversion");
            return this;
        }

        public Criteria andDbversionGreaterThan(Long value) {
            addCriterion("DBVERSION_ >", value, "dbversion");
            return this;
        }

        public Criteria andDbversionGreaterThanOrEqualTo(Long value) {
            addCriterion("DBVERSION_ >=", value, "dbversion");
            return this;
        }

        public Criteria andDbversionLessThan(Long value) {
            addCriterion("DBVERSION_ <", value, "dbversion");
            return this;
        }

        public Criteria andDbversionLessThanOrEqualTo(Long value) {
            addCriterion("DBVERSION_ <=", value, "dbversion");
            return this;
        }

        public Criteria andDbversionIn(List values) {
            addCriterion("DBVERSION_ in", values, "dbversion");
            return this;
        }

        public Criteria andDbversionNotIn(List values) {
            addCriterion("DBVERSION_ not in", values, "dbversion");
            return this;
        }

        public Criteria andDbversionBetween(Long value1, Long value2) {
            addCriterion("DBVERSION_ between", value1, value2, "dbversion");
            return this;
        }

        public Criteria andDbversionNotBetween(Long value1, Long value2) {
            addCriterion("DBVERSION_ not between", value1, value2, "dbversion");
            return this;
        }

        public Criteria andExecutionIsNull() {
            addCriterion("EXECUTION_ is null");
            return this;
        }

        public Criteria andExecutionIsNotNull() {
            addCriterion("EXECUTION_ is not null");
            return this;
        }

        public Criteria andExecutionEqualTo(String value) {
            addCriterion("EXECUTION_ =", value, "execution");
            return this;
        }

        public Criteria andExecutionNotEqualTo(String value) {
            addCriterion("EXECUTION_ <>", value, "execution");
            return this;
        }

        public Criteria andExecutionGreaterThan(String value) {
            addCriterion("EXECUTION_ >", value, "execution");
            return this;
        }

        public Criteria andExecutionGreaterThanOrEqualTo(String value) {
            addCriterion("EXECUTION_ >=", value, "execution");
            return this;
        }

        public Criteria andExecutionLessThan(String value) {
            addCriterion("EXECUTION_ <", value, "execution");
            return this;
        }

        public Criteria andExecutionLessThanOrEqualTo(String value) {
            addCriterion("EXECUTION_ <=", value, "execution");
            return this;
        }

        public Criteria andExecutionLike(String value) {
            addCriterion("EXECUTION_ like", value, "execution");
            return this;
        }

        public Criteria andExecutionNotLike(String value) {
            addCriterion("EXECUTION_ not like", value, "execution");
            return this;
        }

        public Criteria andExecutionIn(List values) {
            addCriterion("EXECUTION_ in", values, "execution");
            return this;
        }

        public Criteria andExecutionNotIn(List values) {
            addCriterion("EXECUTION_ not in", values, "execution");
            return this;
        }

        public Criteria andExecutionBetween(String value1, String value2) {
            addCriterion("EXECUTION_ between", value1, value2, "execution");
            return this;
        }

        public Criteria andExecutionNotBetween(String value1, String value2) {
            addCriterion("EXECUTION_ not between", value1, value2, "execution");
            return this;
        }

        public Criteria andOutcomeIsNull() {
            addCriterion("OUTCOME_ is null");
            return this;
        }

        public Criteria andOutcomeIsNotNull() {
            addCriterion("OUTCOME_ is not null");
            return this;
        }

        public Criteria andOutcomeEqualTo(String value) {
            addCriterion("OUTCOME_ =", value, "outcome");
            return this;
        }

        public Criteria andOutcomeNotEqualTo(String value) {
            addCriterion("OUTCOME_ <>", value, "outcome");
            return this;
        }

        public Criteria andOutcomeGreaterThan(String value) {
            addCriterion("OUTCOME_ >", value, "outcome");
            return this;
        }

        public Criteria andOutcomeGreaterThanOrEqualTo(String value) {
            addCriterion("OUTCOME_ >=", value, "outcome");
            return this;
        }

        public Criteria andOutcomeLessThan(String value) {
            addCriterion("OUTCOME_ <", value, "outcome");
            return this;
        }

        public Criteria andOutcomeLessThanOrEqualTo(String value) {
            addCriterion("OUTCOME_ <=", value, "outcome");
            return this;
        }

        public Criteria andOutcomeLike(String value) {
            addCriterion("OUTCOME_ like", value, "outcome");
            return this;
        }

        public Criteria andOutcomeNotLike(String value) {
            addCriterion("OUTCOME_ not like", value, "outcome");
            return this;
        }

        public Criteria andOutcomeIn(List values) {
            addCriterion("OUTCOME_ in", values, "outcome");
            return this;
        }

        public Criteria andOutcomeNotIn(List values) {
            addCriterion("OUTCOME_ not in", values, "outcome");
            return this;
        }

        public Criteria andOutcomeBetween(String value1, String value2) {
            addCriterion("OUTCOME_ between", value1, value2, "outcome");
            return this;
        }

        public Criteria andOutcomeNotBetween(String value1, String value2) {
            addCriterion("OUTCOME_ not between", value1, value2, "outcome");
            return this;
        }

        public Criteria andAssigneeIsNull() {
            addCriterion("ASSIGNEE_ is null");
            return this;
        }

        public Criteria andAssigneeIsNotNull() {
            addCriterion("ASSIGNEE_ is not null");
            return this;
        }

        public Criteria andAssigneeEqualTo(String value) {
            addCriterion("ASSIGNEE_ =", value, "assignee");
            return this;
        }

        public Criteria andAssigneeNotEqualTo(String value) {
            addCriterion("ASSIGNEE_ <>", value, "assignee");
            return this;
        }

        public Criteria andAssigneeGreaterThan(String value) {
            addCriterion("ASSIGNEE_ >", value, "assignee");
            return this;
        }

        public Criteria andAssigneeGreaterThanOrEqualTo(String value) {
            addCriterion("ASSIGNEE_ >=", value, "assignee");
            return this;
        }

        public Criteria andAssigneeLessThan(String value) {
            addCriterion("ASSIGNEE_ <", value, "assignee");
            return this;
        }

        public Criteria andAssigneeLessThanOrEqualTo(String value) {
            addCriterion("ASSIGNEE_ <=", value, "assignee");
            return this;
        }

        public Criteria andAssigneeLike(String value) {
            addCriterion("ASSIGNEE_ like", value, "assignee");
            return this;
        }

        public Criteria andAssigneeNotLike(String value) {
            addCriterion("ASSIGNEE_ not like", value, "assignee");
            return this;
        }

        public Criteria andAssigneeIn(List values) {
            addCriterion("ASSIGNEE_ in", values, "assignee");
            return this;
        }

        public Criteria andAssigneeNotIn(List values) {
            addCriterion("ASSIGNEE_ not in", values, "assignee");
            return this;
        }

        public Criteria andAssigneeBetween(String value1, String value2) {
            addCriterion("ASSIGNEE_ between", value1, value2, "assignee");
            return this;
        }

        public Criteria andAssigneeNotBetween(String value1, String value2) {
            addCriterion("ASSIGNEE_ not between", value1, value2, "assignee");
            return this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("PRIORITY_ is null");
            return this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("PRIORITY_ is not null");
            return this;
        }

        public Criteria andPriorityEqualTo(Long value) {
            addCriterion("PRIORITY_ =", value, "priority");
            return this;
        }

        public Criteria andPriorityNotEqualTo(Long value) {
            addCriterion("PRIORITY_ <>", value, "priority");
            return this;
        }

        public Criteria andPriorityGreaterThan(Long value) {
            addCriterion("PRIORITY_ >", value, "priority");
            return this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Long value) {
            addCriterion("PRIORITY_ >=", value, "priority");
            return this;
        }

        public Criteria andPriorityLessThan(Long value) {
            addCriterion("PRIORITY_ <", value, "priority");
            return this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Long value) {
            addCriterion("PRIORITY_ <=", value, "priority");
            return this;
        }

        public Criteria andPriorityIn(List values) {
            addCriterion("PRIORITY_ in", values, "priority");
            return this;
        }

        public Criteria andPriorityNotIn(List values) {
            addCriterion("PRIORITY_ not in", values, "priority");
            return this;
        }

        public Criteria andPriorityBetween(Long value1, Long value2) {
            addCriterion("PRIORITY_ between", value1, value2, "priority");
            return this;
        }

        public Criteria andPriorityNotBetween(Long value1, Long value2) {
            addCriterion("PRIORITY_ not between", value1, value2, "priority");
            return this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE_ is null");
            return this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE_ is not null");
            return this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE_ =", value, "state");
            return this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE_ <>", value, "state");
            return this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE_ >", value, "state");
            return this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE_ >=", value, "state");
            return this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE_ <", value, "state");
            return this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE_ <=", value, "state");
            return this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE_ like", value, "state");
            return this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE_ not like", value, "state");
            return this;
        }

        public Criteria andStateIn(List values) {
            addCriterion("STATE_ in", values, "state");
            return this;
        }

        public Criteria andStateNotIn(List values) {
            addCriterion("STATE_ not in", values, "state");
            return this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE_ between", value1, value2, "state");
            return this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE_ not between", value1, value2, "state");
            return this;
        }

        public Criteria andCreateIsNull() {
            addCriterion("CREATE_ is null");
            return this;
        }

        public Criteria andCreateIsNotNull() {
            addCriterion("CREATE_ is not null");
            return this;
        }

        public Criteria andCreateEqualTo(Date value) {
            addCriterion("CREATE_ =", value, "create");
            return this;
        }

        public Criteria andCreateNotEqualTo(Date value) {
            addCriterion("CREATE_ <>", value, "create");
            return this;
        }

        public Criteria andCreateGreaterThan(Date value) {
            addCriterion("CREATE_ >", value, "create");
            return this;
        }

        public Criteria andCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_ >=", value, "create");
            return this;
        }

        public Criteria andCreateLessThan(Date value) {
            addCriterion("CREATE_ <", value, "create");
            return this;
        }

        public Criteria andCreateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_ <=", value, "create");
            return this;
        }

        public Criteria andCreateIn(List values) {
            addCriterion("CREATE_ in", values, "create");
            return this;
        }

        public Criteria andCreateNotIn(List values) {
            addCriterion("CREATE_ not in", values, "create");
            return this;
        }

        public Criteria andCreateBetween(Date value1, Date value2) {
            addCriterion("CREATE_ between", value1, value2, "create");
            return this;
        }

        public Criteria andCreateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_ not between", value1, value2, "create");
            return this;
        }

        public Criteria andEndIsNull() {
            addCriterion("END_ is null");
            return this;
        }

        public Criteria andEndIsNotNull() {
            addCriterion("END_ is not null");
            return this;
        }

        public Criteria andEndEqualTo(Date value) {
            addCriterion("END_ =", value, "end");
            return this;
        }

        public Criteria andEndNotEqualTo(Date value) {
            addCriterion("END_ <>", value, "end");
            return this;
        }

        public Criteria andEndGreaterThan(Date value) {
            addCriterion("END_ >", value, "end");
            return this;
        }

        public Criteria andEndGreaterThanOrEqualTo(Date value) {
            addCriterion("END_ >=", value, "end");
            return this;
        }

        public Criteria andEndLessThan(Date value) {
            addCriterion("END_ <", value, "end");
            return this;
        }

        public Criteria andEndLessThanOrEqualTo(Date value) {
            addCriterion("END_ <=", value, "end");
            return this;
        }

        public Criteria andEndIn(List values) {
            addCriterion("END_ in", values, "end");
            return this;
        }

        public Criteria andEndNotIn(List values) {
            addCriterion("END_ not in", values, "end");
            return this;
        }

        public Criteria andEndBetween(Date value1, Date value2) {
            addCriterion("END_ between", value1, value2, "end");
            return this;
        }

        public Criteria andEndNotBetween(Date value1, Date value2) {
            addCriterion("END_ not between", value1, value2, "end");
            return this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("DURATION_ is null");
            return this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("DURATION_ is not null");
            return this;
        }

        public Criteria andDurationEqualTo(BigDecimal value) {
            addCriterion("DURATION_ =", value, "duration");
            return this;
        }

        public Criteria andDurationNotEqualTo(BigDecimal value) {
            addCriterion("DURATION_ <>", value, "duration");
            return this;
        }

        public Criteria andDurationGreaterThan(BigDecimal value) {
            addCriterion("DURATION_ >", value, "duration");
            return this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DURATION_ >=", value, "duration");
            return this;
        }

        public Criteria andDurationLessThan(BigDecimal value) {
            addCriterion("DURATION_ <", value, "duration");
            return this;
        }

        public Criteria andDurationLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DURATION_ <=", value, "duration");
            return this;
        }

        public Criteria andDurationIn(List values) {
            addCriterion("DURATION_ in", values, "duration");
            return this;
        }

        public Criteria andDurationNotIn(List values) {
            addCriterion("DURATION_ not in", values, "duration");
            return this;
        }

        public Criteria andDurationBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DURATION_ between", value1, value2, "duration");
            return this;
        }

        public Criteria andDurationNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DURATION_ not between", value1, value2, "duration");
            return this;
        }

        public Criteria andNextidxIsNull() {
            addCriterion("NEXTIDX_ is null");
            return this;
        }

        public Criteria andNextidxIsNotNull() {
            addCriterion("NEXTIDX_ is not null");
            return this;
        }

        public Criteria andNextidxEqualTo(Long value) {
            addCriterion("NEXTIDX_ =", value, "nextidx");
            return this;
        }

        public Criteria andNextidxNotEqualTo(Long value) {
            addCriterion("NEXTIDX_ <>", value, "nextidx");
            return this;
        }

        public Criteria andNextidxGreaterThan(Long value) {
            addCriterion("NEXTIDX_ >", value, "nextidx");
            return this;
        }

        public Criteria andNextidxGreaterThanOrEqualTo(Long value) {
            addCriterion("NEXTIDX_ >=", value, "nextidx");
            return this;
        }

        public Criteria andNextidxLessThan(Long value) {
            addCriterion("NEXTIDX_ <", value, "nextidx");
            return this;
        }

        public Criteria andNextidxLessThanOrEqualTo(Long value) {
            addCriterion("NEXTIDX_ <=", value, "nextidx");
            return this;
        }

        public Criteria andNextidxIn(List values) {
            addCriterion("NEXTIDX_ in", values, "nextidx");
            return this;
        }

        public Criteria andNextidxNotIn(List values) {
            addCriterion("NEXTIDX_ not in", values, "nextidx");
            return this;
        }

        public Criteria andNextidxBetween(Long value1, Long value2) {
            addCriterion("NEXTIDX_ between", value1, value2, "nextidx");
            return this;
        }

        public Criteria andNextidxNotBetween(Long value1, Long value2) {
            addCriterion("NEXTIDX_ not between", value1, value2, "nextidx");
            return this;
        }

        public Criteria andSupertaskIsNull() {
            addCriterion("SUPERTASK_ is null");
            return this;
        }

        public Criteria andSupertaskIsNotNull() {
            addCriterion("SUPERTASK_ is not null");
            return this;
        }

        public Criteria andSupertaskEqualTo(BigDecimal value) {
            addCriterion("SUPERTASK_ =", value, "supertask");
            return this;
        }

        public Criteria andSupertaskNotEqualTo(BigDecimal value) {
            addCriterion("SUPERTASK_ <>", value, "supertask");
            return this;
        }

        public Criteria andSupertaskGreaterThan(BigDecimal value) {
            addCriterion("SUPERTASK_ >", value, "supertask");
            return this;
        }

        public Criteria andSupertaskGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUPERTASK_ >=", value, "supertask");
            return this;
        }

        public Criteria andSupertaskLessThan(BigDecimal value) {
            addCriterion("SUPERTASK_ <", value, "supertask");
            return this;
        }

        public Criteria andSupertaskLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUPERTASK_ <=", value, "supertask");
            return this;
        }

        public Criteria andSupertaskIn(List values) {
            addCriterion("SUPERTASK_ in", values, "supertask");
            return this;
        }

        public Criteria andSupertaskNotIn(List values) {
            addCriterion("SUPERTASK_ not in", values, "supertask");
            return this;
        }

        public Criteria andSupertaskBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUPERTASK_ between", value1, value2, "supertask");
            return this;
        }

        public Criteria andSupertaskNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUPERTASK_ not between", value1, value2, "supertask");
            return this;
        }
    }
}