package com.gotop.jbpm.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class Jbpm4TaskExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(Jbpm4TaskExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public Jbpm4TaskExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected Jbpm4TaskExample(Jbpm4TaskExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table JBPM4_TASK
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andDbidIsNull() {
            addCriterion("DBID_ is null");
            return this;
        }

        public Criteria andDbidIsNotNull() {
            addCriterion("DBID_ is not null");
            return this;
        }

        public Criteria andDbidEqualTo(BigDecimal value) {
            addCriterion("DBID_ =", value, "dbid");
            return this;
        }

        public Criteria andDbidNotEqualTo(BigDecimal value) {
            addCriterion("DBID_ <>", value, "dbid");
            return this;
        }

        public Criteria andDbidGreaterThan(BigDecimal value) {
            addCriterion("DBID_ >", value, "dbid");
            return this;
        }

        public Criteria andDbidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DBID_ >=", value, "dbid");
            return this;
        }

        public Criteria andDbidLessThan(BigDecimal value) {
            addCriterion("DBID_ <", value, "dbid");
            return this;
        }

        public Criteria andDbidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DBID_ <=", value, "dbid");
            return this;
        }

        public Criteria andDbidIn(List values) {
            addCriterion("DBID_ in", values, "dbid");
            return this;
        }

        public Criteria andDbidNotIn(List values) {
            addCriterion("DBID_ not in", values, "dbid");
            return this;
        }

        public Criteria andDbidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DBID_ between", value1, value2, "dbid");
            return this;
        }

        public Criteria andDbidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DBID_ not between", value1, value2, "dbid");
            return this;
        }

        public Criteria andClassIsNull() {
            addCriterion("CLASS_ is null");
            return this;
        }

        public Criteria andClassIsNotNull() {
            addCriterion("CLASS_ is not null");
            return this;
        }

        public Criteria andClassEqualTo(String value) {
            addCriterion("CLASS_ =", value, "class");
            return this;
        }

        public Criteria andClassNotEqualTo(String value) {
            addCriterion("CLASS_ <>", value, "class");
            return this;
        }

        public Criteria andClassGreaterThan(String value) {
            addCriterion("CLASS_ >", value, "class");
            return this;
        }

        public Criteria andClassGreaterThanOrEqualTo(String value) {
            addCriterion("CLASS_ >=", value, "class");
            return this;
        }

        public Criteria andClassLessThan(String value) {
            addCriterion("CLASS_ <", value, "class");
            return this;
        }

        public Criteria andClassLessThanOrEqualTo(String value) {
            addCriterion("CLASS_ <=", value, "class");
            return this;
        }

        public Criteria andClassLike(String value) {
            addCriterion("CLASS_ like", value, "class");
            return this;
        }

        public Criteria andClassNotLike(String value) {
            addCriterion("CLASS_ not like", value, "class");
            return this;
        }

        public Criteria andClassIn(List values) {
            addCriterion("CLASS_ in", values, "class");
            return this;
        }

        public Criteria andClassNotIn(List values) {
            addCriterion("CLASS_ not in", values, "class");
            return this;
        }

        public Criteria andClassBetween(String value1, String value2) {
            addCriterion("CLASS_ between", value1, value2, "class");
            return this;
        }

        public Criteria andClassNotBetween(String value1, String value2) {
            addCriterion("CLASS_ not between", value1, value2, "class");
            return this;
        }

        public Criteria andDbversionIsNull() {
            addCriterion("DBVERSION_ is null");
            return this;
        }

        public Criteria andDbversionIsNotNull() {
            addCriterion("DBVERSION_ is not null");
            return this;
        }

        public Criteria andDbversionEqualTo(Long value) {
            addCriterion("DBVERSION_ =", value, "dbversion");
            return this;
        }

        public Criteria andDbversionNotEqualTo(Long value) {
            addCriterion("DBVERSION_ <>", value, "dbversion");
            return this;
        }

        public Criteria andDbversionGreaterThan(Long value) {
            addCriterion("DBVERSION_ >", value, "dbversion");
            return this;
        }

        public Criteria andDbversionGreaterThanOrEqualTo(Long value) {
            addCriterion("DBVERSION_ >=", value, "dbversion");
            return this;
        }

        public Criteria andDbversionLessThan(Long value) {
            addCriterion("DBVERSION_ <", value, "dbversion");
            return this;
        }

        public Criteria andDbversionLessThanOrEqualTo(Long value) {
            addCriterion("DBVERSION_ <=", value, "dbversion");
            return this;
        }

        public Criteria andDbversionIn(List values) {
            addCriterion("DBVERSION_ in", values, "dbversion");
            return this;
        }

        public Criteria andDbversionNotIn(List values) {
            addCriterion("DBVERSION_ not in", values, "dbversion");
            return this;
        }

        public Criteria andDbversionBetween(Long value1, Long value2) {
            addCriterion("DBVERSION_ between", value1, value2, "dbversion");
            return this;
        }

        public Criteria andDbversionNotBetween(Long value1, Long value2) {
            addCriterion("DBVERSION_ not between", value1, value2, "dbversion");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME_ is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME_ is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME_ =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME_ <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME_ >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME_ >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME_ <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME_ <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME_ like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME_ not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("NAME_ in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("NAME_ not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME_ between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME_ not between", value1, value2, "name");
            return this;
        }

        public Criteria andDescrIsNull() {
            addCriterion("DESCR_ is null");
            return this;
        }

        public Criteria andDescrIsNotNull() {
            addCriterion("DESCR_ is not null");
            return this;
        }

        public Criteria andDescrEqualTo(Object value) {
            addCriterion("DESCR_ =", value, "descr");
            return this;
        }

        public Criteria andDescrNotEqualTo(Object value) {
            addCriterion("DESCR_ <>", value, "descr");
            return this;
        }

        public Criteria andDescrGreaterThan(Object value) {
            addCriterion("DESCR_ >", value, "descr");
            return this;
        }

        public Criteria andDescrGreaterThanOrEqualTo(Object value) {
            addCriterion("DESCR_ >=", value, "descr");
            return this;
        }

        public Criteria andDescrLessThan(Object value) {
            addCriterion("DESCR_ <", value, "descr");
            return this;
        }

        public Criteria andDescrLessThanOrEqualTo(Object value) {
            addCriterion("DESCR_ <=", value, "descr");
            return this;
        }

        public Criteria andDescrIn(List values) {
            addCriterion("DESCR_ in", values, "descr");
            return this;
        }

        public Criteria andDescrNotIn(List values) {
            addCriterion("DESCR_ not in", values, "descr");
            return this;
        }

        public Criteria andDescrBetween(Object value1, Object value2) {
            addCriterion("DESCR_ between", value1, value2, "descr");
            return this;
        }

        public Criteria andDescrNotBetween(Object value1, Object value2) {
            addCriterion("DESCR_ not between", value1, value2, "descr");
            return this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE_ is null");
            return this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE_ is not null");
            return this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE_ =", value, "state");
            return this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE_ <>", value, "state");
            return this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE_ >", value, "state");
            return this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE_ >=", value, "state");
            return this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE_ <", value, "state");
            return this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE_ <=", value, "state");
            return this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE_ like", value, "state");
            return this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE_ not like", value, "state");
            return this;
        }

        public Criteria andStateIn(List values) {
            addCriterion("STATE_ in", values, "state");
            return this;
        }

        public Criteria andStateNotIn(List values) {
            addCriterion("STATE_ not in", values, "state");
            return this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE_ between", value1, value2, "state");
            return this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE_ not between", value1, value2, "state");
            return this;
        }

        public Criteria andSusphiststateIsNull() {
            addCriterion("SUSPHISTSTATE_ is null");
            return this;
        }

        public Criteria andSusphiststateIsNotNull() {
            addCriterion("SUSPHISTSTATE_ is not null");
            return this;
        }

        public Criteria andSusphiststateEqualTo(String value) {
            addCriterion("SUSPHISTSTATE_ =", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateNotEqualTo(String value) {
            addCriterion("SUSPHISTSTATE_ <>", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateGreaterThan(String value) {
            addCriterion("SUSPHISTSTATE_ >", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateGreaterThanOrEqualTo(String value) {
            addCriterion("SUSPHISTSTATE_ >=", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateLessThan(String value) {
            addCriterion("SUSPHISTSTATE_ <", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateLessThanOrEqualTo(String value) {
            addCriterion("SUSPHISTSTATE_ <=", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateLike(String value) {
            addCriterion("SUSPHISTSTATE_ like", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateNotLike(String value) {
            addCriterion("SUSPHISTSTATE_ not like", value, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateIn(List values) {
            addCriterion("SUSPHISTSTATE_ in", values, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateNotIn(List values) {
            addCriterion("SUSPHISTSTATE_ not in", values, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateBetween(String value1, String value2) {
            addCriterion("SUSPHISTSTATE_ between", value1, value2, "susphiststate");
            return this;
        }

        public Criteria andSusphiststateNotBetween(String value1, String value2) {
            addCriterion("SUSPHISTSTATE_ not between", value1, value2, "susphiststate");
            return this;
        }

        public Criteria andAssigneeIsNull() {
            addCriterion("ASSIGNEE_ is null");
            return this;
        }

        public Criteria andAssigneeIsNotNull() {
            addCriterion("ASSIGNEE_ is not null");
            return this;
        }

        public Criteria andAssigneeEqualTo(String value) {
            addCriterion("ASSIGNEE_ =", value, "assignee");
            return this;
        }

        public Criteria andAssigneeNotEqualTo(String value) {
            addCriterion("ASSIGNEE_ <>", value, "assignee");
            return this;
        }

        public Criteria andAssigneeGreaterThan(String value) {
            addCriterion("ASSIGNEE_ >", value, "assignee");
            return this;
        }

        public Criteria andAssigneeGreaterThanOrEqualTo(String value) {
            addCriterion("ASSIGNEE_ >=", value, "assignee");
            return this;
        }

        public Criteria andAssigneeLessThan(String value) {
            addCriterion("ASSIGNEE_ <", value, "assignee");
            return this;
        }

        public Criteria andAssigneeLessThanOrEqualTo(String value) {
            addCriterion("ASSIGNEE_ <=", value, "assignee");
            return this;
        }

        public Criteria andAssigneeLike(String value) {
            addCriterion("ASSIGNEE_ like", value, "assignee");
            return this;
        }

        public Criteria andAssigneeNotLike(String value) {
            addCriterion("ASSIGNEE_ not like", value, "assignee");
            return this;
        }

        public Criteria andAssigneeIn(List values) {
            addCriterion("ASSIGNEE_ in", values, "assignee");
            return this;
        }

        public Criteria andAssigneeNotIn(List values) {
            addCriterion("ASSIGNEE_ not in", values, "assignee");
            return this;
        }

        public Criteria andAssigneeBetween(String value1, String value2) {
            addCriterion("ASSIGNEE_ between", value1, value2, "assignee");
            return this;
        }

        public Criteria andAssigneeNotBetween(String value1, String value2) {
            addCriterion("ASSIGNEE_ not between", value1, value2, "assignee");
            return this;
        }

        public Criteria andFormIsNull() {
            addCriterion("FORM_ is null");
            return this;
        }

        public Criteria andFormIsNotNull() {
            addCriterion("FORM_ is not null");
            return this;
        }

        public Criteria andFormEqualTo(String value) {
            addCriterion("FORM_ =", value, "form");
            return this;
        }

        public Criteria andFormNotEqualTo(String value) {
            addCriterion("FORM_ <>", value, "form");
            return this;
        }

        public Criteria andFormGreaterThan(String value) {
            addCriterion("FORM_ >", value, "form");
            return this;
        }

        public Criteria andFormGreaterThanOrEqualTo(String value) {
            addCriterion("FORM_ >=", value, "form");
            return this;
        }

        public Criteria andFormLessThan(String value) {
            addCriterion("FORM_ <", value, "form");
            return this;
        }

        public Criteria andFormLessThanOrEqualTo(String value) {
            addCriterion("FORM_ <=", value, "form");
            return this;
        }

        public Criteria andFormLike(String value) {
            addCriterion("FORM_ like", value, "form");
            return this;
        }

        public Criteria andFormNotLike(String value) {
            addCriterion("FORM_ not like", value, "form");
            return this;
        }

        public Criteria andFormIn(List values) {
            addCriterion("FORM_ in", values, "form");
            return this;
        }

        public Criteria andFormNotIn(List values) {
            addCriterion("FORM_ not in", values, "form");
            return this;
        }

        public Criteria andFormBetween(String value1, String value2) {
            addCriterion("FORM_ between", value1, value2, "form");
            return this;
        }

        public Criteria andFormNotBetween(String value1, String value2) {
            addCriterion("FORM_ not between", value1, value2, "form");
            return this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("PRIORITY_ is null");
            return this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("PRIORITY_ is not null");
            return this;
        }

        public Criteria andPriorityEqualTo(Long value) {
            addCriterion("PRIORITY_ =", value, "priority");
            return this;
        }

        public Criteria andPriorityNotEqualTo(Long value) {
            addCriterion("PRIORITY_ <>", value, "priority");
            return this;
        }

        public Criteria andPriorityGreaterThan(Long value) {
            addCriterion("PRIORITY_ >", value, "priority");
            return this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Long value) {
            addCriterion("PRIORITY_ >=", value, "priority");
            return this;
        }

        public Criteria andPriorityLessThan(Long value) {
            addCriterion("PRIORITY_ <", value, "priority");
            return this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Long value) {
            addCriterion("PRIORITY_ <=", value, "priority");
            return this;
        }

        public Criteria andPriorityIn(List values) {
            addCriterion("PRIORITY_ in", values, "priority");
            return this;
        }

        public Criteria andPriorityNotIn(List values) {
            addCriterion("PRIORITY_ not in", values, "priority");
            return this;
        }

        public Criteria andPriorityBetween(Long value1, Long value2) {
            addCriterion("PRIORITY_ between", value1, value2, "priority");
            return this;
        }

        public Criteria andPriorityNotBetween(Long value1, Long value2) {
            addCriterion("PRIORITY_ not between", value1, value2, "priority");
            return this;
        }

        public Criteria andCreateIsNull() {
            addCriterion("CREATE_ is null");
            return this;
        }

        public Criteria andCreateIsNotNull() {
            addCriterion("CREATE_ is not null");
            return this;
        }

        public Criteria andCreateEqualTo(Date value) {
            addCriterion("CREATE_ =", value, "create");
            return this;
        }

        public Criteria andCreateNotEqualTo(Date value) {
            addCriterion("CREATE_ <>", value, "create");
            return this;
        }

        public Criteria andCreateGreaterThan(Date value) {
            addCriterion("CREATE_ >", value, "create");
            return this;
        }

        public Criteria andCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_ >=", value, "create");
            return this;
        }

        public Criteria andCreateLessThan(Date value) {
            addCriterion("CREATE_ <", value, "create");
            return this;
        }

        public Criteria andCreateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_ <=", value, "create");
            return this;
        }

        public Criteria andCreateIn(List values) {
            addCriterion("CREATE_ in", values, "create");
            return this;
        }

        public Criteria andCreateNotIn(List values) {
            addCriterion("CREATE_ not in", values, "create");
            return this;
        }

        public Criteria andCreateBetween(Date value1, Date value2) {
            addCriterion("CREATE_ between", value1, value2, "create");
            return this;
        }

        public Criteria andCreateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_ not between", value1, value2, "create");
            return this;
        }

        public Criteria andDuedateIsNull() {
            addCriterion("DUEDATE_ is null");
            return this;
        }

        public Criteria andDuedateIsNotNull() {
            addCriterion("DUEDATE_ is not null");
            return this;
        }

        public Criteria andDuedateEqualTo(Date value) {
            addCriterion("DUEDATE_ =", value, "duedate");
            return this;
        }

        public Criteria andDuedateNotEqualTo(Date value) {
            addCriterion("DUEDATE_ <>", value, "duedate");
            return this;
        }

        public Criteria andDuedateGreaterThan(Date value) {
            addCriterion("DUEDATE_ >", value, "duedate");
            return this;
        }

        public Criteria andDuedateGreaterThanOrEqualTo(Date value) {
            addCriterion("DUEDATE_ >=", value, "duedate");
            return this;
        }

        public Criteria andDuedateLessThan(Date value) {
            addCriterion("DUEDATE_ <", value, "duedate");
            return this;
        }

        public Criteria andDuedateLessThanOrEqualTo(Date value) {
            addCriterion("DUEDATE_ <=", value, "duedate");
            return this;
        }

        public Criteria andDuedateIn(List values) {
            addCriterion("DUEDATE_ in", values, "duedate");
            return this;
        }

        public Criteria andDuedateNotIn(List values) {
            addCriterion("DUEDATE_ not in", values, "duedate");
            return this;
        }

        public Criteria andDuedateBetween(Date value1, Date value2) {
            addCriterion("DUEDATE_ between", value1, value2, "duedate");
            return this;
        }

        public Criteria andDuedateNotBetween(Date value1, Date value2) {
            addCriterion("DUEDATE_ not between", value1, value2, "duedate");
            return this;
        }

        public Criteria andProgressIsNull() {
            addCriterion("PROGRESS_ is null");
            return this;
        }

        public Criteria andProgressIsNotNull() {
            addCriterion("PROGRESS_ is not null");
            return this;
        }

        public Criteria andProgressEqualTo(Long value) {
            addCriterion("PROGRESS_ =", value, "progress");
            return this;
        }

        public Criteria andProgressNotEqualTo(Long value) {
            addCriterion("PROGRESS_ <>", value, "progress");
            return this;
        }

        public Criteria andProgressGreaterThan(Long value) {
            addCriterion("PROGRESS_ >", value, "progress");
            return this;
        }

        public Criteria andProgressGreaterThanOrEqualTo(Long value) {
            addCriterion("PROGRESS_ >=", value, "progress");
            return this;
        }

        public Criteria andProgressLessThan(Long value) {
            addCriterion("PROGRESS_ <", value, "progress");
            return this;
        }

        public Criteria andProgressLessThanOrEqualTo(Long value) {
            addCriterion("PROGRESS_ <=", value, "progress");
            return this;
        }

        public Criteria andProgressIn(List values) {
            addCriterion("PROGRESS_ in", values, "progress");
            return this;
        }

        public Criteria andProgressNotIn(List values) {
            addCriterion("PROGRESS_ not in", values, "progress");
            return this;
        }

        public Criteria andProgressBetween(Long value1, Long value2) {
            addCriterion("PROGRESS_ between", value1, value2, "progress");
            return this;
        }

        public Criteria andProgressNotBetween(Long value1, Long value2) {
            addCriterion("PROGRESS_ not between", value1, value2, "progress");
            return this;
        }

        public Criteria andSignallingIsNull() {
            addCriterion("SIGNALLING_ is null");
            return this;
        }

        public Criteria andSignallingIsNotNull() {
            addCriterion("SIGNALLING_ is not null");
            return this;
        }

        public Criteria andSignallingEqualTo(Integer value) {
            addCriterion("SIGNALLING_ =", value, "signalling");
            return this;
        }

        public Criteria andSignallingNotEqualTo(Integer value) {
            addCriterion("SIGNALLING_ <>", value, "signalling");
            return this;
        }

        public Criteria andSignallingGreaterThan(Integer value) {
            addCriterion("SIGNALLING_ >", value, "signalling");
            return this;
        }

        public Criteria andSignallingGreaterThanOrEqualTo(Integer value) {
            addCriterion("SIGNALLING_ >=", value, "signalling");
            return this;
        }

        public Criteria andSignallingLessThan(Integer value) {
            addCriterion("SIGNALLING_ <", value, "signalling");
            return this;
        }

        public Criteria andSignallingLessThanOrEqualTo(Integer value) {
            addCriterion("SIGNALLING_ <=", value, "signalling");
            return this;
        }

        public Criteria andSignallingIn(List values) {
            addCriterion("SIGNALLING_ in", values, "signalling");
            return this;
        }

        public Criteria andSignallingNotIn(List values) {
            addCriterion("SIGNALLING_ not in", values, "signalling");
            return this;
        }

        public Criteria andSignallingBetween(Integer value1, Integer value2) {
            addCriterion("SIGNALLING_ between", value1, value2, "signalling");
            return this;
        }

        public Criteria andSignallingNotBetween(Integer value1, Integer value2) {
            addCriterion("SIGNALLING_ not between", value1, value2, "signalling");
            return this;
        }

        public Criteria andExecutionIdIsNull() {
            addCriterion("EXECUTION_ID_ is null");
            return this;
        }

        public Criteria andExecutionIdIsNotNull() {
            addCriterion("EXECUTION_ID_ is not null");
            return this;
        }

        public Criteria andExecutionIdEqualTo(String value) {
            addCriterion("EXECUTION_ID_ =", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdNotEqualTo(String value) {
            addCriterion("EXECUTION_ID_ <>", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdGreaterThan(String value) {
            addCriterion("EXECUTION_ID_ >", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdGreaterThanOrEqualTo(String value) {
            addCriterion("EXECUTION_ID_ >=", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdLessThan(String value) {
            addCriterion("EXECUTION_ID_ <", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdLessThanOrEqualTo(String value) {
            addCriterion("EXECUTION_ID_ <=", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdLike(String value) {
            addCriterion("EXECUTION_ID_ like", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdNotLike(String value) {
            addCriterion("EXECUTION_ID_ not like", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdIn(List values) {
            addCriterion("EXECUTION_ID_ in", values, "executionId");
            return this;
        }

        public Criteria andExecutionIdNotIn(List values) {
            addCriterion("EXECUTION_ID_ not in", values, "executionId");
            return this;
        }

        public Criteria andExecutionIdBetween(String value1, String value2) {
            addCriterion("EXECUTION_ID_ between", value1, value2, "executionId");
            return this;
        }

        public Criteria andExecutionIdNotBetween(String value1, String value2) {
            addCriterion("EXECUTION_ID_ not between", value1, value2, "executionId");
            return this;
        }

        public Criteria andActivityNameIsNull() {
            addCriterion("ACTIVITY_NAME_ is null");
            return this;
        }

        public Criteria andActivityNameIsNotNull() {
            addCriterion("ACTIVITY_NAME_ is not null");
            return this;
        }

        public Criteria andActivityNameEqualTo(String value) {
            addCriterion("ACTIVITY_NAME_ =", value, "activityName");
            return this;
        }

        public Criteria andActivityNameNotEqualTo(String value) {
            addCriterion("ACTIVITY_NAME_ <>", value, "activityName");
            return this;
        }

        public Criteria andActivityNameGreaterThan(String value) {
            addCriterion("ACTIVITY_NAME_ >", value, "activityName");
            return this;
        }

        public Criteria andActivityNameGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVITY_NAME_ >=", value, "activityName");
            return this;
        }

        public Criteria andActivityNameLessThan(String value) {
            addCriterion("ACTIVITY_NAME_ <", value, "activityName");
            return this;
        }

        public Criteria andActivityNameLessThanOrEqualTo(String value) {
            addCriterion("ACTIVITY_NAME_ <=", value, "activityName");
            return this;
        }

        public Criteria andActivityNameLike(String value) {
            addCriterion("ACTIVITY_NAME_ like", value, "activityName");
            return this;
        }

        public Criteria andActivityNameNotLike(String value) {
            addCriterion("ACTIVITY_NAME_ not like", value, "activityName");
            return this;
        }

        public Criteria andActivityNameIn(List values) {
            addCriterion("ACTIVITY_NAME_ in", values, "activityName");
            return this;
        }

        public Criteria andActivityNameNotIn(List values) {
            addCriterion("ACTIVITY_NAME_ not in", values, "activityName");
            return this;
        }

        public Criteria andActivityNameBetween(String value1, String value2) {
            addCriterion("ACTIVITY_NAME_ between", value1, value2, "activityName");
            return this;
        }

        public Criteria andActivityNameNotBetween(String value1, String value2) {
            addCriterion("ACTIVITY_NAME_ not between", value1, value2, "activityName");
            return this;
        }

        public Criteria andHasvarsIsNull() {
            addCriterion("HASVARS_ is null");
            return this;
        }

        public Criteria andHasvarsIsNotNull() {
            addCriterion("HASVARS_ is not null");
            return this;
        }

        public Criteria andHasvarsEqualTo(Integer value) {
            addCriterion("HASVARS_ =", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsNotEqualTo(Integer value) {
            addCriterion("HASVARS_ <>", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsGreaterThan(Integer value) {
            addCriterion("HASVARS_ >", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsGreaterThanOrEqualTo(Integer value) {
            addCriterion("HASVARS_ >=", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsLessThan(Integer value) {
            addCriterion("HASVARS_ <", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsLessThanOrEqualTo(Integer value) {
            addCriterion("HASVARS_ <=", value, "hasvars");
            return this;
        }

        public Criteria andHasvarsIn(List values) {
            addCriterion("HASVARS_ in", values, "hasvars");
            return this;
        }

        public Criteria andHasvarsNotIn(List values) {
            addCriterion("HASVARS_ not in", values, "hasvars");
            return this;
        }

        public Criteria andHasvarsBetween(Integer value1, Integer value2) {
            addCriterion("HASVARS_ between", value1, value2, "hasvars");
            return this;
        }

        public Criteria andHasvarsNotBetween(Integer value1, Integer value2) {
            addCriterion("HASVARS_ not between", value1, value2, "hasvars");
            return this;
        }

        public Criteria andSupertaskIsNull() {
            addCriterion("SUPERTASK_ is null");
            return this;
        }

        public Criteria andSupertaskIsNotNull() {
            addCriterion("SUPERTASK_ is not null");
            return this;
        }

        public Criteria andSupertaskEqualTo(BigDecimal value) {
            addCriterion("SUPERTASK_ =", value, "supertask");
            return this;
        }

        public Criteria andSupertaskNotEqualTo(BigDecimal value) {
            addCriterion("SUPERTASK_ <>", value, "supertask");
            return this;
        }

        public Criteria andSupertaskGreaterThan(BigDecimal value) {
            addCriterion("SUPERTASK_ >", value, "supertask");
            return this;
        }

        public Criteria andSupertaskGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUPERTASK_ >=", value, "supertask");
            return this;
        }

        public Criteria andSupertaskLessThan(BigDecimal value) {
            addCriterion("SUPERTASK_ <", value, "supertask");
            return this;
        }

        public Criteria andSupertaskLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUPERTASK_ <=", value, "supertask");
            return this;
        }

        public Criteria andSupertaskIn(List values) {
            addCriterion("SUPERTASK_ in", values, "supertask");
            return this;
        }

        public Criteria andSupertaskNotIn(List values) {
            addCriterion("SUPERTASK_ not in", values, "supertask");
            return this;
        }

        public Criteria andSupertaskBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUPERTASK_ between", value1, value2, "supertask");
            return this;
        }

        public Criteria andSupertaskNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUPERTASK_ not between", value1, value2, "supertask");
            return this;
        }

        public Criteria andExecutionIsNull() {
            addCriterion("EXECUTION_ is null");
            return this;
        }

        public Criteria andExecutionIsNotNull() {
            addCriterion("EXECUTION_ is not null");
            return this;
        }

        public Criteria andExecutionEqualTo(BigDecimal value) {
            addCriterion("EXECUTION_ =", value, "execution");
            return this;
        }

        public Criteria andExecutionNotEqualTo(BigDecimal value) {
            addCriterion("EXECUTION_ <>", value, "execution");
            return this;
        }

        public Criteria andExecutionGreaterThan(BigDecimal value) {
            addCriterion("EXECUTION_ >", value, "execution");
            return this;
        }

        public Criteria andExecutionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EXECUTION_ >=", value, "execution");
            return this;
        }

        public Criteria andExecutionLessThan(BigDecimal value) {
            addCriterion("EXECUTION_ <", value, "execution");
            return this;
        }

        public Criteria andExecutionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EXECUTION_ <=", value, "execution");
            return this;
        }

        public Criteria andExecutionIn(List values) {
            addCriterion("EXECUTION_ in", values, "execution");
            return this;
        }

        public Criteria andExecutionNotIn(List values) {
            addCriterion("EXECUTION_ not in", values, "execution");
            return this;
        }

        public Criteria andExecutionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EXECUTION_ between", value1, value2, "execution");
            return this;
        }

        public Criteria andExecutionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EXECUTION_ not between", value1, value2, "execution");
            return this;
        }

        public Criteria andProcinstIsNull() {
            addCriterion("PROCINST_ is null");
            return this;
        }

        public Criteria andProcinstIsNotNull() {
            addCriterion("PROCINST_ is not null");
            return this;
        }

        public Criteria andProcinstEqualTo(BigDecimal value) {
            addCriterion("PROCINST_ =", value, "procinst");
            return this;
        }

        public Criteria andProcinstNotEqualTo(BigDecimal value) {
            addCriterion("PROCINST_ <>", value, "procinst");
            return this;
        }

        public Criteria andProcinstGreaterThan(BigDecimal value) {
            addCriterion("PROCINST_ >", value, "procinst");
            return this;
        }

        public Criteria andProcinstGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PROCINST_ >=", value, "procinst");
            return this;
        }

        public Criteria andProcinstLessThan(BigDecimal value) {
            addCriterion("PROCINST_ <", value, "procinst");
            return this;
        }

        public Criteria andProcinstLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PROCINST_ <=", value, "procinst");
            return this;
        }

        public Criteria andProcinstIn(List values) {
            addCriterion("PROCINST_ in", values, "procinst");
            return this;
        }

        public Criteria andProcinstNotIn(List values) {
            addCriterion("PROCINST_ not in", values, "procinst");
            return this;
        }

        public Criteria andProcinstBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROCINST_ between", value1, value2, "procinst");
            return this;
        }

        public Criteria andProcinstNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROCINST_ not between", value1, value2, "procinst");
            return this;
        }

        public Criteria andSwimlaneIsNull() {
            addCriterion("SWIMLANE_ is null");
            return this;
        }

        public Criteria andSwimlaneIsNotNull() {
            addCriterion("SWIMLANE_ is not null");
            return this;
        }

        public Criteria andSwimlaneEqualTo(BigDecimal value) {
            addCriterion("SWIMLANE_ =", value, "swimlane");
            return this;
        }

        public Criteria andSwimlaneNotEqualTo(BigDecimal value) {
            addCriterion("SWIMLANE_ <>", value, "swimlane");
            return this;
        }

        public Criteria andSwimlaneGreaterThan(BigDecimal value) {
            addCriterion("SWIMLANE_ >", value, "swimlane");
            return this;
        }

        public Criteria andSwimlaneGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SWIMLANE_ >=", value, "swimlane");
            return this;
        }

        public Criteria andSwimlaneLessThan(BigDecimal value) {
            addCriterion("SWIMLANE_ <", value, "swimlane");
            return this;
        }

        public Criteria andSwimlaneLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SWIMLANE_ <=", value, "swimlane");
            return this;
        }

        public Criteria andSwimlaneIn(List values) {
            addCriterion("SWIMLANE_ in", values, "swimlane");
            return this;
        }

        public Criteria andSwimlaneNotIn(List values) {
            addCriterion("SWIMLANE_ not in", values, "swimlane");
            return this;
        }

        public Criteria andSwimlaneBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SWIMLANE_ between", value1, value2, "swimlane");
            return this;
        }

        public Criteria andSwimlaneNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SWIMLANE_ not between", value1, value2, "swimlane");
            return this;
        }

        public Criteria andTaskdefnameIsNull() {
            addCriterion("TASKDEFNAME_ is null");
            return this;
        }

        public Criteria andTaskdefnameIsNotNull() {
            addCriterion("TASKDEFNAME_ is not null");
            return this;
        }

        public Criteria andTaskdefnameEqualTo(String value) {
            addCriterion("TASKDEFNAME_ =", value, "taskdefname");
            return this;
        }

        public Criteria andTaskdefnameNotEqualTo(String value) {
            addCriterion("TASKDEFNAME_ <>", value, "taskdefname");
            return this;
        }

        public Criteria andTaskdefnameGreaterThan(String value) {
            addCriterion("TASKDEFNAME_ >", value, "taskdefname");
            return this;
        }

        public Criteria andTaskdefnameGreaterThanOrEqualTo(String value) {
            addCriterion("TASKDEFNAME_ >=", value, "taskdefname");
            return this;
        }

        public Criteria andTaskdefnameLessThan(String value) {
            addCriterion("TASKDEFNAME_ <", value, "taskdefname");
            return this;
        }

        public Criteria andTaskdefnameLessThanOrEqualTo(String value) {
            addCriterion("TASKDEFNAME_ <=", value, "taskdefname");
            return this;
        }

        public Criteria andTaskdefnameLike(String value) {
            addCriterion("TASKDEFNAME_ like", value, "taskdefname");
            return this;
        }

        public Criteria andTaskdefnameNotLike(String value) {
            addCriterion("TASKDEFNAME_ not like", value, "taskdefname");
            return this;
        }

        public Criteria andTaskdefnameIn(List values) {
            addCriterion("TASKDEFNAME_ in", values, "taskdefname");
            return this;
        }

        public Criteria andTaskdefnameNotIn(List values) {
            addCriterion("TASKDEFNAME_ not in", values, "taskdefname");
            return this;
        }

        public Criteria andTaskdefnameBetween(String value1, String value2) {
            addCriterion("TASKDEFNAME_ between", value1, value2, "taskdefname");
            return this;
        }

        public Criteria andTaskdefnameNotBetween(String value1, String value2) {
            addCriterion("TASKDEFNAME_ not between", value1, value2, "taskdefname");
            return this;
        }
    }
}