package com.gotop.jbpm.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TProcessTaskExeConfigExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TProcessTaskExeConfigExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public TProcessTaskExeConfigExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected TProcessTaskExeConfigExample(TProcessTaskExeConfigExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_PROCESS_TASK_EXE_CONFIG
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andDefinitionIdIsNull() {
            addCriterion("DEFINITION_ID is null");
            return this;
        }

        public Criteria andDefinitionIdIsNotNull() {
            addCriterion("DEFINITION_ID is not null");
            return this;
        }

        public Criteria andDefinitionIdEqualTo(String value) {
            addCriterion("DEFINITION_ID =", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdNotEqualTo(String value) {
            addCriterion("DEFINITION_ID <>", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdGreaterThan(String value) {
            addCriterion("DEFINITION_ID >", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEFINITION_ID >=", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdLessThan(String value) {
            addCriterion("DEFINITION_ID <", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdLessThanOrEqualTo(String value) {
            addCriterion("DEFINITION_ID <=", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdLike(String value) {
            addCriterion("DEFINITION_ID like", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdNotLike(String value) {
            addCriterion("DEFINITION_ID not like", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdIn(List values) {
            addCriterion("DEFINITION_ID in", values, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdNotIn(List values) {
            addCriterion("DEFINITION_ID not in", values, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdBetween(String value1, String value2) {
            addCriterion("DEFINITION_ID between", value1, value2, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdNotBetween(String value1, String value2) {
            addCriterion("DEFINITION_ID not between", value1, value2, "definitionId");
            return this;
        }

        public Criteria andActivityNameIsNull() {
            addCriterion("ACTIVITY_NAME is null");
            return this;
        }

        public Criteria andActivityNameIsNotNull() {
            addCriterion("ACTIVITY_NAME is not null");
            return this;
        }

        public Criteria andActivityNameEqualTo(String value) {
            addCriterion("ACTIVITY_NAME =", value, "activityName");
            return this;
        }

        public Criteria andActivityNameNotEqualTo(String value) {
            addCriterion("ACTIVITY_NAME <>", value, "activityName");
            return this;
        }

        public Criteria andActivityNameGreaterThan(String value) {
            addCriterion("ACTIVITY_NAME >", value, "activityName");
            return this;
        }

        public Criteria andActivityNameGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVITY_NAME >=", value, "activityName");
            return this;
        }

        public Criteria andActivityNameLessThan(String value) {
            addCriterion("ACTIVITY_NAME <", value, "activityName");
            return this;
        }

        public Criteria andActivityNameLessThanOrEqualTo(String value) {
            addCriterion("ACTIVITY_NAME <=", value, "activityName");
            return this;
        }

        public Criteria andActivityNameLike(String value) {
            addCriterion("ACTIVITY_NAME like", value, "activityName");
            return this;
        }

        public Criteria andActivityNameNotLike(String value) {
            addCriterion("ACTIVITY_NAME not like", value, "activityName");
            return this;
        }

        public Criteria andActivityNameIn(List values) {
            addCriterion("ACTIVITY_NAME in", values, "activityName");
            return this;
        }

        public Criteria andActivityNameNotIn(List values) {
            addCriterion("ACTIVITY_NAME not in", values, "activityName");
            return this;
        }

        public Criteria andActivityNameBetween(String value1, String value2) {
            addCriterion("ACTIVITY_NAME between", value1, value2, "activityName");
            return this;
        }

        public Criteria andActivityNameNotBetween(String value1, String value2) {
            addCriterion("ACTIVITY_NAME not between", value1, value2, "activityName");
            return this;
        }

        public Criteria andTaskAssIdIsNull() {
            addCriterion("TASK_ASS_ID is null");
            return this;
        }

        public Criteria andTaskAssIdIsNotNull() {
            addCriterion("TASK_ASS_ID is not null");
            return this;
        }

        public Criteria andTaskAssIdEqualTo(Long value) {
            addCriterion("TASK_ASS_ID =", value, "taskAssId");
            return this;
        }

        public Criteria andTaskAssIdNotEqualTo(Long value) {
            addCriterion("TASK_ASS_ID <>", value, "taskAssId");
            return this;
        }

        public Criteria andTaskAssIdGreaterThan(Long value) {
            addCriterion("TASK_ASS_ID >", value, "taskAssId");
            return this;
        }

        public Criteria andTaskAssIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TASK_ASS_ID >=", value, "taskAssId");
            return this;
        }

        public Criteria andTaskAssIdLessThan(Long value) {
            addCriterion("TASK_ASS_ID <", value, "taskAssId");
            return this;
        }

        public Criteria andTaskAssIdLessThanOrEqualTo(Long value) {
            addCriterion("TASK_ASS_ID <=", value, "taskAssId");
            return this;
        }

        public Criteria andTaskAssIdIn(List values) {
            addCriterion("TASK_ASS_ID in", values, "taskAssId");
            return this;
        }

        public Criteria andTaskAssIdNotIn(List values) {
            addCriterion("TASK_ASS_ID not in", values, "taskAssId");
            return this;
        }

        public Criteria andTaskAssIdBetween(Long value1, Long value2) {
            addCriterion("TASK_ASS_ID between", value1, value2, "taskAssId");
            return this;
        }

        public Criteria andTaskAssIdNotBetween(Long value1, Long value2) {
            addCriterion("TASK_ASS_ID not between", value1, value2, "taskAssId");
            return this;
        }

        public Criteria andTaskAssTypeIsNull() {
            addCriterion("TASK_ASS_TYPE is null");
            return this;
        }

        public Criteria andTaskAssTypeIsNotNull() {
            addCriterion("TASK_ASS_TYPE is not null");
            return this;
        }

        public Criteria andTaskAssTypeEqualTo(String value) {
            addCriterion("TASK_ASS_TYPE =", value, "taskAssType");
            return this;
        }

        public Criteria andTaskAssTypeNotEqualTo(String value) {
            addCriterion("TASK_ASS_TYPE <>", value, "taskAssType");
            return this;
        }

        public Criteria andTaskAssTypeGreaterThan(String value) {
            addCriterion("TASK_ASS_TYPE >", value, "taskAssType");
            return this;
        }

        public Criteria andTaskAssTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TASK_ASS_TYPE >=", value, "taskAssType");
            return this;
        }

        public Criteria andTaskAssTypeLessThan(String value) {
            addCriterion("TASK_ASS_TYPE <", value, "taskAssType");
            return this;
        }

        public Criteria andTaskAssTypeLessThanOrEqualTo(String value) {
            addCriterion("TASK_ASS_TYPE <=", value, "taskAssType");
            return this;
        }

        public Criteria andTaskAssTypeLike(String value) {
            addCriterion("TASK_ASS_TYPE like", value, "taskAssType");
            return this;
        }

        public Criteria andTaskAssTypeNotLike(String value) {
            addCriterion("TASK_ASS_TYPE not like", value, "taskAssType");
            return this;
        }

        public Criteria andTaskAssTypeIn(List values) {
            addCriterion("TASK_ASS_TYPE in", values, "taskAssType");
            return this;
        }

        public Criteria andTaskAssTypeNotIn(List values) {
            addCriterion("TASK_ASS_TYPE not in", values, "taskAssType");
            return this;
        }

        public Criteria andTaskAssTypeBetween(String value1, String value2) {
            addCriterion("TASK_ASS_TYPE between", value1, value2, "taskAssType");
            return this;
        }

        public Criteria andTaskAssTypeNotBetween(String value1, String value2) {
            addCriterion("TASK_ASS_TYPE not between", value1, value2, "taskAssType");
            return this;
        }
    }
}