package com.gotop.jbpm.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TProcessTaskAssigneePersonExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TProcessTaskAssigneePersonExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public TProcessTaskAssigneePersonExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected TProcessTaskAssigneePersonExample(TProcessTaskAssigneePersonExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_PROCESS_TASK_ASSIGNEE_PERSON
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdIsNull() {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID is null");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdIsNotNull() {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID is not null");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdEqualTo(Long value) {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID =", value, "processTaskAssigneeId");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdNotEqualTo(Long value) {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID <>", value, "processTaskAssigneeId");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdGreaterThan(Long value) {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID >", value, "processTaskAssigneeId");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID >=", value, "processTaskAssigneeId");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdLessThan(Long value) {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID <", value, "processTaskAssigneeId");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdLessThanOrEqualTo(Long value) {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID <=", value, "processTaskAssigneeId");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdIn(List values) {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID in", values, "processTaskAssigneeId");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdNotIn(List values) {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID not in", values, "processTaskAssigneeId");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdBetween(Long value1, Long value2) {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID between", value1, value2, "processTaskAssigneeId");
            return this;
        }

        public Criteria andProcessTaskAssigneeIdNotBetween(Long value1, Long value2) {
            addCriterion("PROCESS_TASK_ASSIGNEE_ID not between", value1, value2, "processTaskAssigneeId");
            return this;
        }

        public Criteria andExecutionIdIsNull() {
            addCriterion("EXECUTION_ID is null");
            return this;
        }

        public Criteria andExecutionIdIsNotNull() {
            addCriterion("EXECUTION_ID is not null");
            return this;
        }

        public Criteria andExecutionIdEqualTo(String value) {
            addCriterion("EXECUTION_ID =", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdNotEqualTo(String value) {
            addCriterion("EXECUTION_ID <>", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdGreaterThan(String value) {
            addCriterion("EXECUTION_ID >", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdGreaterThanOrEqualTo(String value) {
            addCriterion("EXECUTION_ID >=", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdLessThan(String value) {
            addCriterion("EXECUTION_ID <", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdLessThanOrEqualTo(String value) {
            addCriterion("EXECUTION_ID <=", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdLike(String value) {
            addCriterion("EXECUTION_ID like", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdNotLike(String value) {
            addCriterion("EXECUTION_ID not like", value, "executionId");
            return this;
        }

        public Criteria andExecutionIdIn(List values) {
            addCriterion("EXECUTION_ID in", values, "executionId");
            return this;
        }

        public Criteria andExecutionIdNotIn(List values) {
            addCriterion("EXECUTION_ID not in", values, "executionId");
            return this;
        }

        public Criteria andExecutionIdBetween(String value1, String value2) {
            addCriterion("EXECUTION_ID between", value1, value2, "executionId");
            return this;
        }

        public Criteria andExecutionIdNotBetween(String value1, String value2) {
            addCriterion("EXECUTION_ID not between", value1, value2, "executionId");
            return this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("TASK_ID is null");
            return this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("TASK_ID is not null");
            return this;
        }

        public Criteria andTaskIdEqualTo(String value) {
            addCriterion("TASK_ID =", value, "taskId");
            return this;
        }

        public Criteria andTaskIdNotEqualTo(String value) {
            addCriterion("TASK_ID <>", value, "taskId");
            return this;
        }

        public Criteria andTaskIdGreaterThan(String value) {
            addCriterion("TASK_ID >", value, "taskId");
            return this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("TASK_ID >=", value, "taskId");
            return this;
        }

        public Criteria andTaskIdLessThan(String value) {
            addCriterion("TASK_ID <", value, "taskId");
            return this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(String value) {
            addCriterion("TASK_ID <=", value, "taskId");
            return this;
        }

        public Criteria andTaskIdLike(String value) {
            addCriterion("TASK_ID like", value, "taskId");
            return this;
        }

        public Criteria andTaskIdNotLike(String value) {
            addCriterion("TASK_ID not like", value, "taskId");
            return this;
        }

        public Criteria andTaskIdIn(List values) {
            addCriterion("TASK_ID in", values, "taskId");
            return this;
        }

        public Criteria andTaskIdNotIn(List values) {
            addCriterion("TASK_ID not in", values, "taskId");
            return this;
        }

        public Criteria andTaskIdBetween(String value1, String value2) {
            addCriterion("TASK_ID between", value1, value2, "taskId");
            return this;
        }

        public Criteria andTaskIdNotBetween(String value1, String value2) {
            addCriterion("TASK_ID not between", value1, value2, "taskId");
            return this;
        }

        public Criteria andTaskAssigneeIdIsNull() {
            addCriterion("TASK_ASSIGNEE_ID is null");
            return this;
        }

        public Criteria andTaskAssigneeIdIsNotNull() {
            addCriterion("TASK_ASSIGNEE_ID is not null");
            return this;
        }

        public Criteria andTaskAssigneeIdEqualTo(Long value) {
            addCriterion("TASK_ASSIGNEE_ID =", value, "taskAssigneeId");
            return this;
        }

        public Criteria andTaskAssigneeIdNotEqualTo(Long value) {
            addCriterion("TASK_ASSIGNEE_ID <>", value, "taskAssigneeId");
            return this;
        }

        public Criteria andTaskAssigneeIdGreaterThan(Long value) {
            addCriterion("TASK_ASSIGNEE_ID >", value, "taskAssigneeId");
            return this;
        }

        public Criteria andTaskAssigneeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TASK_ASSIGNEE_ID >=", value, "taskAssigneeId");
            return this;
        }

        public Criteria andTaskAssigneeIdLessThan(Long value) {
            addCriterion("TASK_ASSIGNEE_ID <", value, "taskAssigneeId");
            return this;
        }

        public Criteria andTaskAssigneeIdLessThanOrEqualTo(Long value) {
            addCriterion("TASK_ASSIGNEE_ID <=", value, "taskAssigneeId");
            return this;
        }

        public Criteria andTaskAssigneeIdIn(List values) {
            addCriterion("TASK_ASSIGNEE_ID in", values, "taskAssigneeId");
            return this;
        }

        public Criteria andTaskAssigneeIdNotIn(List values) {
            addCriterion("TASK_ASSIGNEE_ID not in", values, "taskAssigneeId");
            return this;
        }

        public Criteria andTaskAssigneeIdBetween(Long value1, Long value2) {
            addCriterion("TASK_ASSIGNEE_ID between", value1, value2, "taskAssigneeId");
            return this;
        }

        public Criteria andTaskAssigneeIdNotBetween(Long value1, Long value2) {
            addCriterion("TASK_ASSIGNEE_ID not between", value1, value2, "taskAssigneeId");
            return this;
        }
    }
}