package com.gotop.jbpm.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TProcessBusinessExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TProcessBusinessExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public TProcessBusinessExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected TProcessBusinessExample(TProcessBusinessExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_PROCESS_BUSINESS
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andBusinessTypeIsNull() {
            addCriterion("BUSINESS_TYPE is null");
            return this;
        }

        public Criteria andBusinessTypeIsNotNull() {
            addCriterion("BUSINESS_TYPE is not null");
            return this;
        }

        public Criteria andBusinessTypeEqualTo(String value) {
            addCriterion("BUSINESS_TYPE =", value, "businessType");
            return this;
        }

        public Criteria andBusinessTypeNotEqualTo(String value) {
            addCriterion("BUSINESS_TYPE <>", value, "businessType");
            return this;
        }

        public Criteria andBusinessTypeGreaterThan(String value) {
            addCriterion("BUSINESS_TYPE >", value, "businessType");
            return this;
        }

        public Criteria andBusinessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TYPE >=", value, "businessType");
            return this;
        }

        public Criteria andBusinessTypeLessThan(String value) {
            addCriterion("BUSINESS_TYPE <", value, "businessType");
            return this;
        }

        public Criteria andBusinessTypeLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TYPE <=", value, "businessType");
            return this;
        }

        public Criteria andBusinessTypeLike(String value) {
            addCriterion("BUSINESS_TYPE like", value, "businessType");
            return this;
        }

        public Criteria andBusinessTypeNotLike(String value) {
            addCriterion("BUSINESS_TYPE not like", value, "businessType");
            return this;
        }

        public Criteria andBusinessTypeIn(List values) {
            addCriterion("BUSINESS_TYPE in", values, "businessType");
            return this;
        }

        public Criteria andBusinessTypeNotIn(List values) {
            addCriterion("BUSINESS_TYPE not in", values, "businessType");
            return this;
        }

        public Criteria andBusinessTypeBetween(String value1, String value2) {
            addCriterion("BUSINESS_TYPE between", value1, value2, "businessType");
            return this;
        }

        public Criteria andBusinessTypeNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_TYPE not between", value1, value2, "businessType");
            return this;
        }

        public Criteria andBusinessKeyIsNull() {
            addCriterion("BUSINESS_KEY is null");
            return this;
        }

        public Criteria andBusinessKeyIsNotNull() {
            addCriterion("BUSINESS_KEY is not null");
            return this;
        }

        public Criteria andBusinessKeyEqualTo(Long value) {
            addCriterion("BUSINESS_KEY =", value, "businessKey");
            return this;
        }

        public Criteria andBusinessKeyNotEqualTo(Long value) {
            addCriterion("BUSINESS_KEY <>", value, "businessKey");
            return this;
        }

        public Criteria andBusinessKeyGreaterThan(Long value) {
            addCriterion("BUSINESS_KEY >", value, "businessKey");
            return this;
        }

        public Criteria andBusinessKeyGreaterThanOrEqualTo(Long value) {
            addCriterion("BUSINESS_KEY >=", value, "businessKey");
            return this;
        }

        public Criteria andBusinessKeyLessThan(Long value) {
            addCriterion("BUSINESS_KEY <", value, "businessKey");
            return this;
        }

        public Criteria andBusinessKeyLessThanOrEqualTo(Long value) {
            addCriterion("BUSINESS_KEY <=", value, "businessKey");
            return this;
        }

        public Criteria andBusinessKeyIn(List values) {
            addCriterion("BUSINESS_KEY in", values, "businessKey");
            return this;
        }

        public Criteria andBusinessKeyNotIn(List values) {
            addCriterion("BUSINESS_KEY not in", values, "businessKey");
            return this;
        }

        public Criteria andBusinessKeyBetween(Long value1, Long value2) {
            addCriterion("BUSINESS_KEY between", value1, value2, "businessKey");
            return this;
        }

        public Criteria andBusinessKeyNotBetween(Long value1, Long value2) {
            addCriterion("BUSINESS_KEY not between", value1, value2, "businessKey");
            return this;
        }

        public Criteria andBusinessTitleIsNull() {
            addCriterion("BUSINESS_TITLE is null");
            return this;
        }

        public Criteria andBusinessTitleIsNotNull() {
            addCriterion("BUSINESS_TITLE is not null");
            return this;
        }

        public Criteria andBusinessTitleEqualTo(String value) {
            addCriterion("BUSINESS_TITLE =", value, "businessTitle");
            return this;
        }

        public Criteria andBusinessTitleNotEqualTo(String value) {
            addCriterion("BUSINESS_TITLE <>", value, "businessTitle");
            return this;
        }

        public Criteria andBusinessTitleGreaterThan(String value) {
            addCriterion("BUSINESS_TITLE >", value, "businessTitle");
            return this;
        }

        public Criteria andBusinessTitleGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TITLE >=", value, "businessTitle");
            return this;
        }

        public Criteria andBusinessTitleLessThan(String value) {
            addCriterion("BUSINESS_TITLE <", value, "businessTitle");
            return this;
        }

        public Criteria andBusinessTitleLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TITLE <=", value, "businessTitle");
            return this;
        }

        public Criteria andBusinessTitleLike(String value) {
            addCriterion("BUSINESS_TITLE like", value, "businessTitle");
            return this;
        }

        public Criteria andBusinessTitleNotLike(String value) {
            addCriterion("BUSINESS_TITLE not like", value, "businessTitle");
            return this;
        }

        public Criteria andBusinessTitleIn(List values) {
            addCriterion("BUSINESS_TITLE in", values, "businessTitle");
            return this;
        }

        public Criteria andBusinessTitleNotIn(List values) {
            addCriterion("BUSINESS_TITLE not in", values, "businessTitle");
            return this;
        }

        public Criteria andBusinessTitleBetween(String value1, String value2) {
            addCriterion("BUSINESS_TITLE between", value1, value2, "businessTitle");
            return this;
        }

        public Criteria andBusinessTitleNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_TITLE not between", value1, value2, "businessTitle");
            return this;
        }
    }
}