package com.gotop.jbpm.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TProcessConfigExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TProcessConfigExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public TProcessConfigExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected TProcessConfigExample(TProcessConfigExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_PROCESS_CONFIG
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andDefinitionIdIsNull() {
            addCriterion("DEFINITION_ID is null");
            return this;
        }

        public Criteria andDefinitionIdIsNotNull() {
            addCriterion("DEFINITION_ID is not null");
            return this;
        }

        public Criteria andDefinitionIdEqualTo(String value) {
            addCriterion("DEFINITION_ID =", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdNotEqualTo(String value) {
            addCriterion("DEFINITION_ID <>", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdGreaterThan(String value) {
            addCriterion("DEFINITION_ID >", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEFINITION_ID >=", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdLessThan(String value) {
            addCriterion("DEFINITION_ID <", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdLessThanOrEqualTo(String value) {
            addCriterion("DEFINITION_ID <=", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdLike(String value) {
            addCriterion("DEFINITION_ID like", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdNotLike(String value) {
            addCriterion("DEFINITION_ID not like", value, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdIn(List values) {
            addCriterion("DEFINITION_ID in", values, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdNotIn(List values) {
            addCriterion("DEFINITION_ID not in", values, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdBetween(String value1, String value2) {
            addCriterion("DEFINITION_ID between", value1, value2, "definitionId");
            return this;
        }

        public Criteria andDefinitionIdNotBetween(String value1, String value2) {
            addCriterion("DEFINITION_ID not between", value1, value2, "definitionId");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("USER_ID =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("USER_ID <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("USER_ID >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("USER_ID >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("USER_ID <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("USER_ID <=", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("USER_ID in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("USER_ID not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return this;
        }

        public Criteria andUploadOrgIsNull() {
            addCriterion("UPLOAD_ORG is null");
            return this;
        }

        public Criteria andUploadOrgIsNotNull() {
            addCriterion("UPLOAD_ORG is not null");
            return this;
        }

        public Criteria andUploadOrgEqualTo(Long value) {
            addCriterion("UPLOAD_ORG =", value, "uploadOrg");
            return this;
        }

        public Criteria andUploadOrgNotEqualTo(Long value) {
            addCriterion("UPLOAD_ORG <>", value, "uploadOrg");
            return this;
        }

        public Criteria andUploadOrgGreaterThan(Long value) {
            addCriterion("UPLOAD_ORG >", value, "uploadOrg");
            return this;
        }

        public Criteria andUploadOrgGreaterThanOrEqualTo(Long value) {
            addCriterion("UPLOAD_ORG >=", value, "uploadOrg");
            return this;
        }

        public Criteria andUploadOrgLessThan(Long value) {
            addCriterion("UPLOAD_ORG <", value, "uploadOrg");
            return this;
        }

        public Criteria andUploadOrgLessThanOrEqualTo(Long value) {
            addCriterion("UPLOAD_ORG <=", value, "uploadOrg");
            return this;
        }

        public Criteria andUploadOrgIn(List values) {
            addCriterion("UPLOAD_ORG in", values, "uploadOrg");
            return this;
        }

        public Criteria andUploadOrgNotIn(List values) {
            addCriterion("UPLOAD_ORG not in", values, "uploadOrg");
            return this;
        }

        public Criteria andUploadOrgBetween(Long value1, Long value2) {
            addCriterion("UPLOAD_ORG between", value1, value2, "uploadOrg");
            return this;
        }

        public Criteria andUploadOrgNotBetween(Long value1, Long value2) {
            addCriterion("UPLOAD_ORG not between", value1, value2, "uploadOrg");
            return this;
        }

        public Criteria andUploadTimeIsNull() {
            addCriterion("UPLOAD_TIME is null");
            return this;
        }

        public Criteria andUploadTimeIsNotNull() {
            addCriterion("UPLOAD_TIME is not null");
            return this;
        }

        public Criteria andUploadTimeEqualTo(String value) {
            addCriterion("UPLOAD_TIME =", value, "uploadTime");
            return this;
        }

        public Criteria andUploadTimeNotEqualTo(String value) {
            addCriterion("UPLOAD_TIME <>", value, "uploadTime");
            return this;
        }

        public Criteria andUploadTimeGreaterThan(String value) {
            addCriterion("UPLOAD_TIME >", value, "uploadTime");
            return this;
        }

        public Criteria andUploadTimeGreaterThanOrEqualTo(String value) {
            addCriterion("UPLOAD_TIME >=", value, "uploadTime");
            return this;
        }

        public Criteria andUploadTimeLessThan(String value) {
            addCriterion("UPLOAD_TIME <", value, "uploadTime");
            return this;
        }

        public Criteria andUploadTimeLessThanOrEqualTo(String value) {
            addCriterion("UPLOAD_TIME <=", value, "uploadTime");
            return this;
        }

        public Criteria andUploadTimeLike(String value) {
            addCriterion("UPLOAD_TIME like", value, "uploadTime");
            return this;
        }

        public Criteria andUploadTimeNotLike(String value) {
            addCriterion("UPLOAD_TIME not like", value, "uploadTime");
            return this;
        }

        public Criteria andUploadTimeIn(List values) {
            addCriterion("UPLOAD_TIME in", values, "uploadTime");
            return this;
        }

        public Criteria andUploadTimeNotIn(List values) {
            addCriterion("UPLOAD_TIME not in", values, "uploadTime");
            return this;
        }

        public Criteria andUploadTimeBetween(String value1, String value2) {
            addCriterion("UPLOAD_TIME between", value1, value2, "uploadTime");
            return this;
        }

        public Criteria andUploadTimeNotBetween(String value1, String value2) {
            addCriterion("UPLOAD_TIME not between", value1, value2, "uploadTime");
            return this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return this;
        }

        public Criteria andStateIn(List values) {
            addCriterion("STATE in", values, "state");
            return this;
        }

        public Criteria andStateNotIn(List values) {
            addCriterion("STATE not in", values, "state");
            return this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return this;
        }

        public Criteria andRoleOrgPersonIsNull() {
            addCriterion("ROLE_ORG_PERSON is null");
            return this;
        }

        public Criteria andRoleOrgPersonIsNotNull() {
            addCriterion("ROLE_ORG_PERSON is not null");
            return this;
        }

        public Criteria andRoleOrgPersonEqualTo(String value) {
            addCriterion("ROLE_ORG_PERSON =", value, "roleOrgPerson");
            return this;
        }

        public Criteria andRoleOrgPersonNotEqualTo(String value) {
            addCriterion("ROLE_ORG_PERSON <>", value, "roleOrgPerson");
            return this;
        }

        public Criteria andRoleOrgPersonGreaterThan(String value) {
            addCriterion("ROLE_ORG_PERSON >", value, "roleOrgPerson");
            return this;
        }

        public Criteria andRoleOrgPersonGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_ORG_PERSON >=", value, "roleOrgPerson");
            return this;
        }

        public Criteria andRoleOrgPersonLessThan(String value) {
            addCriterion("ROLE_ORG_PERSON <", value, "roleOrgPerson");
            return this;
        }

        public Criteria andRoleOrgPersonLessThanOrEqualTo(String value) {
            addCriterion("ROLE_ORG_PERSON <=", value, "roleOrgPerson");
            return this;
        }

        public Criteria andRoleOrgPersonLike(String value) {
            addCriterion("ROLE_ORG_PERSON like", value, "roleOrgPerson");
            return this;
        }

        public Criteria andRoleOrgPersonNotLike(String value) {
            addCriterion("ROLE_ORG_PERSON not like", value, "roleOrgPerson");
            return this;
        }

        public Criteria andRoleOrgPersonIn(List values) {
            addCriterion("ROLE_ORG_PERSON in", values, "roleOrgPerson");
            return this;
        }

        public Criteria andRoleOrgPersonNotIn(List values) {
            addCriterion("ROLE_ORG_PERSON not in", values, "roleOrgPerson");
            return this;
        }

        public Criteria andRoleOrgPersonBetween(String value1, String value2) {
            addCriterion("ROLE_ORG_PERSON between", value1, value2, "roleOrgPerson");
            return this;
        }

        public Criteria andRoleOrgPersonNotBetween(String value1, String value2) {
            addCriterion("ROLE_ORG_PERSON not between", value1, value2, "roleOrgPerson");
            return this;
        }

        public Criteria andProcessNameIsNull() {
            addCriterion("PROCESS_NAME is null");
            return this;
        }

        public Criteria andProcessNameIsNotNull() {
            addCriterion("PROCESS_NAME is not null");
            return this;
        }

        public Criteria andProcessNameEqualTo(String value) {
            addCriterion("PROCESS_NAME =", value, "processName");
            return this;
        }

        public Criteria andProcessNameNotEqualTo(String value) {
            addCriterion("PROCESS_NAME <>", value, "processName");
            return this;
        }

        public Criteria andProcessNameGreaterThan(String value) {
            addCriterion("PROCESS_NAME >", value, "processName");
            return this;
        }

        public Criteria andProcessNameGreaterThanOrEqualTo(String value) {
            addCriterion("PROCESS_NAME >=", value, "processName");
            return this;
        }

        public Criteria andProcessNameLessThan(String value) {
            addCriterion("PROCESS_NAME <", value, "processName");
            return this;
        }

        public Criteria andProcessNameLessThanOrEqualTo(String value) {
            addCriterion("PROCESS_NAME <=", value, "processName");
            return this;
        }

        public Criteria andProcessNameLike(String value) {
            addCriterion("PROCESS_NAME like", value, "processName");
            return this;
        }

        public Criteria andProcessNameNotLike(String value) {
            addCriterion("PROCESS_NAME not like", value, "processName");
            return this;
        }

        public Criteria andProcessNameIn(List values) {
            addCriterion("PROCESS_NAME in", values, "processName");
            return this;
        }

        public Criteria andProcessNameNotIn(List values) {
            addCriterion("PROCESS_NAME not in", values, "processName");
            return this;
        }

        public Criteria andProcessNameBetween(String value1, String value2) {
            addCriterion("PROCESS_NAME between", value1, value2, "processName");
            return this;
        }

        public Criteria andProcessNameNotBetween(String value1, String value2) {
            addCriterion("PROCESS_NAME not between", value1, value2, "processName");
            return this;
        }
    }
}