package com.gotop.euipApply.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TApplyEuipExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TApplyEuipExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** */
    public TApplyEuipExample() {
        oredCriteria = new ArrayList();
    }

    /** */
    protected TApplyEuipExample(TApplyEuipExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** */
    /** */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_APPLY_EUIP
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andEpIdIsNull() {
            addCriterion("EP_ID is null");
            return this;
        }

        public Criteria andEpIdIsNotNull() {
            addCriterion("EP_ID is not null");
            return this;
        }

        public Criteria andEpIdEqualTo(Long value) {
            addCriterion("EP_ID =", value, "epId");
            return this;
        }

        public Criteria andEpIdNotEqualTo(Long value) {
            addCriterion("EP_ID <>", value, "epId");
            return this;
        }

        public Criteria andEpIdGreaterThan(Long value) {
            addCriterion("EP_ID >", value, "epId");
            return this;
        }

        public Criteria andEpIdGreaterThanOrEqualTo(Long value) {
            addCriterion("EP_ID >=", value, "epId");
            return this;
        }

        public Criteria andEpIdLessThan(Long value) {
            addCriterion("EP_ID <", value, "epId");
            return this;
        }

        public Criteria andEpIdLessThanOrEqualTo(Long value) {
            addCriterion("EP_ID <=", value, "epId");
            return this;
        }

        public Criteria andEpIdIn(List values) {
            addCriterion("EP_ID in", values, "epId");
            return this;
        }

        public Criteria andEpIdNotIn(List values) {
            addCriterion("EP_ID not in", values, "epId");
            return this;
        }

        public Criteria andEpIdBetween(Long value1, Long value2) {
            addCriterion("EP_ID between", value1, value2, "epId");
            return this;
        }

        public Criteria andEpIdNotBetween(Long value1, Long value2) {
            addCriterion("EP_ID not between", value1, value2, "epId");
            return this;
        }

        public Criteria andEmpIdIsNull() {
            addCriterion("EMP_ID is null");
            return this;
        }

        public Criteria andEmpIdIsNotNull() {
            addCriterion("EMP_ID is not null");
            return this;
        }

        public Criteria andEmpIdEqualTo(Long value) {
            addCriterion("EMP_ID =", value, "empId");
            return this;
        }

        public Criteria andEmpIdNotEqualTo(Long value) {
            addCriterion("EMP_ID <>", value, "empId");
            return this;
        }

        public Criteria andEmpIdGreaterThan(Long value) {
            addCriterion("EMP_ID >", value, "empId");
            return this;
        }

        public Criteria andEmpIdGreaterThanOrEqualTo(Long value) {
            addCriterion("EMP_ID >=", value, "empId");
            return this;
        }

        public Criteria andEmpIdLessThan(Long value) {
            addCriterion("EMP_ID <", value, "empId");
            return this;
        }

        public Criteria andEmpIdLessThanOrEqualTo(Long value) {
            addCriterion("EMP_ID <=", value, "empId");
            return this;
        }

        public Criteria andEmpIdIn(List values) {
            addCriterion("EMP_ID in", values, "empId");
            return this;
        }

        public Criteria andEmpIdNotIn(List values) {
            addCriterion("EMP_ID not in", values, "empId");
            return this;
        }

        public Criteria andEmpIdBetween(Long value1, Long value2) {
            addCriterion("EMP_ID between", value1, value2, "empId");
            return this;
        }

        public Criteria andEmpIdNotBetween(Long value1, Long value2) {
            addCriterion("EMP_ID not between", value1, value2, "empId");
            return this;
        }

        public Criteria andFlowIdIsNull() {
            addCriterion("FLOW_ID is null");
            return this;
        }

        public Criteria andFlowIdIsNotNull() {
            addCriterion("FLOW_ID is not null");
            return this;
        }

        public Criteria andFlowIdEqualTo(String value) {
            addCriterion("FLOW_ID =", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotEqualTo(String value) {
            addCriterion("FLOW_ID <>", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThan(String value) {
            addCriterion("FLOW_ID >", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThanOrEqualTo(String value) {
            addCriterion("FLOW_ID >=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThan(String value) {
            addCriterion("FLOW_ID <", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThanOrEqualTo(String value) {
            addCriterion("FLOW_ID <=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLike(String value) {
            addCriterion("FLOW_ID like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotLike(String value) {
            addCriterion("FLOW_ID not like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdIn(List values) {
            addCriterion("FLOW_ID in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdNotIn(List values) {
            addCriterion("FLOW_ID not in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdBetween(String value1, String value2) {
            addCriterion("FLOW_ID between", value1, value2, "flowId");
            return this;
        }

        public Criteria andFlowIdNotBetween(String value1, String value2) {
            addCriterion("FLOW_ID not between", value1, value2, "flowId");
            return this;
        }

        public Criteria andPhoneNoIsNull() {
            addCriterion("PHONE_NO is null");
            return this;
        }

        public Criteria andPhoneNoIsNotNull() {
            addCriterion("PHONE_NO is not null");
            return this;
        }

        public Criteria andPhoneNoEqualTo(String value) {
            addCriterion("PHONE_NO =", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoNotEqualTo(String value) {
            addCriterion("PHONE_NO <>", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoGreaterThan(String value) {
            addCriterion("PHONE_NO >", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE_NO >=", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoLessThan(String value) {
            addCriterion("PHONE_NO <", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoLessThanOrEqualTo(String value) {
            addCriterion("PHONE_NO <=", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoLike(String value) {
            addCriterion("PHONE_NO like", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoNotLike(String value) {
            addCriterion("PHONE_NO not like", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoIn(List values) {
            addCriterion("PHONE_NO in", values, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoNotIn(List values) {
            addCriterion("PHONE_NO not in", values, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoBetween(String value1, String value2) {
            addCriterion("PHONE_NO between", value1, value2, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoNotBetween(String value1, String value2) {
            addCriterion("PHONE_NO not between", value1, value2, "phoneNo");
            return this;
        }

        public Criteria andEpTitleIsNull() {
            addCriterion("EP_TITLE is null");
            return this;
        }

        public Criteria andEpTitleIsNotNull() {
            addCriterion("EP_TITLE is not null");
            return this;
        }

        public Criteria andEpTitleEqualTo(String value) {
            addCriterion("EP_TITLE =", value, "epTitle");
            return this;
        }

        public Criteria andEpTitleNotEqualTo(String value) {
            addCriterion("EP_TITLE <>", value, "epTitle");
            return this;
        }

        public Criteria andEpTitleGreaterThan(String value) {
            addCriterion("EP_TITLE >", value, "epTitle");
            return this;
        }

        public Criteria andEpTitleGreaterThanOrEqualTo(String value) {
            addCriterion("EP_TITLE >=", value, "epTitle");
            return this;
        }

        public Criteria andEpTitleLessThan(String value) {
            addCriterion("EP_TITLE <", value, "epTitle");
            return this;
        }

        public Criteria andEpTitleLessThanOrEqualTo(String value) {
            addCriterion("EP_TITLE <=", value, "epTitle");
            return this;
        }

        public Criteria andEpTitleLike(String value) {
            addCriterion("EP_TITLE like", value, "epTitle");
            return this;
        }

        public Criteria andEpTitleNotLike(String value) {
            addCriterion("EP_TITLE not like", value, "epTitle");
            return this;
        }

        public Criteria andEpTitleIn(List values) {
            addCriterion("EP_TITLE in", values, "epTitle");
            return this;
        }

        public Criteria andEpTitleNotIn(List values) {
            addCriterion("EP_TITLE not in", values, "epTitle");
            return this;
        }

        public Criteria andEpTitleBetween(String value1, String value2) {
            addCriterion("EP_TITLE between", value1, value2, "epTitle");
            return this;
        }

        public Criteria andEpTitleNotBetween(String value1, String value2) {
            addCriterion("EP_TITLE not between", value1, value2, "epTitle");
            return this;
        }

        public Criteria andEpMatterIsNull() {
            addCriterion("EP_MATTER is null");
            return this;
        }

        public Criteria andEpMatterIsNotNull() {
            addCriterion("EP_MATTER is not null");
            return this;
        }

        public Criteria andEpMatterEqualTo(String value) {
            addCriterion("EP_MATTER =", value, "epMatter");
            return this;
        }

        public Criteria andEpMatterNotEqualTo(String value) {
            addCriterion("EP_MATTER <>", value, "epMatter");
            return this;
        }

        public Criteria andEpMatterGreaterThan(String value) {
            addCriterion("EP_MATTER >", value, "epMatter");
            return this;
        }

        public Criteria andEpMatterGreaterThanOrEqualTo(String value) {
            addCriterion("EP_MATTER >=", value, "epMatter");
            return this;
        }

        public Criteria andEpMatterLessThan(String value) {
            addCriterion("EP_MATTER <", value, "epMatter");
            return this;
        }

        public Criteria andEpMatterLessThanOrEqualTo(String value) {
            addCriterion("EP_MATTER <=", value, "epMatter");
            return this;
        }

        public Criteria andEpMatterLike(String value) {
            addCriterion("EP_MATTER like", value, "epMatter");
            return this;
        }

        public Criteria andEpMatterNotLike(String value) {
            addCriterion("EP_MATTER not like", value, "epMatter");
            return this;
        }

        public Criteria andEpMatterIn(List values) {
            addCriterion("EP_MATTER in", values, "epMatter");
            return this;
        }

        public Criteria andEpMatterNotIn(List values) {
            addCriterion("EP_MATTER not in", values, "epMatter");
            return this;
        }

        public Criteria andEpMatterBetween(String value1, String value2) {
            addCriterion("EP_MATTER between", value1, value2, "epMatter");
            return this;
        }

        public Criteria andEpMatterNotBetween(String value1, String value2) {
            addCriterion("EP_MATTER not between", value1, value2, "epMatter");
            return this;
        }

        public Criteria andEpTypeIsNull() {
            addCriterion("EP_TYPE is null");
            return this;
        }

        public Criteria andEpTypeIsNotNull() {
            addCriterion("EP_TYPE is not null");
            return this;
        }

        public Criteria andEpTypeEqualTo(String value) {
            addCriterion("EP_TYPE =", value, "epType");
            return this;
        }

        public Criteria andEpTypeNotEqualTo(String value) {
            addCriterion("EP_TYPE <>", value, "epType");
            return this;
        }

        public Criteria andEpTypeGreaterThan(String value) {
            addCriterion("EP_TYPE >", value, "epType");
            return this;
        }

        public Criteria andEpTypeGreaterThanOrEqualTo(String value) {
            addCriterion("EP_TYPE >=", value, "epType");
            return this;
        }

        public Criteria andEpTypeLessThan(String value) {
            addCriterion("EP_TYPE <", value, "epType");
            return this;
        }

        public Criteria andEpTypeLessThanOrEqualTo(String value) {
            addCriterion("EP_TYPE <=", value, "epType");
            return this;
        }

        public Criteria andEpTypeLike(String value) {
            addCriterion("EP_TYPE like", value, "epType");
            return this;
        }

        public Criteria andEpTypeNotLike(String value) {
            addCriterion("EP_TYPE not like", value, "epType");
            return this;
        }

        public Criteria andEpTypeIn(List values) {
            addCriterion("EP_TYPE in", values, "epType");
            return this;
        }

        public Criteria andEpTypeNotIn(List values) {
            addCriterion("EP_TYPE not in", values, "epType");
            return this;
        }

        public Criteria andEpTypeBetween(String value1, String value2) {
            addCriterion("EP_TYPE between", value1, value2, "epType");
            return this;
        }

        public Criteria andEpTypeNotBetween(String value1, String value2) {
            addCriterion("EP_TYPE not between", value1, value2, "epType");
            return this;
        }

        public Criteria andEpNumberIsNull() {
            addCriterion("EP_NUMBER is null");
            return this;
        }

        public Criteria andEpNumberIsNotNull() {
            addCriterion("EP_NUMBER is not null");
            return this;
        }

        public Criteria andEpNumberEqualTo(Long value) {
            addCriterion("EP_NUMBER =", value, "epNumber");
            return this;
        }

        public Criteria andEpNumberNotEqualTo(Long value) {
            addCriterion("EP_NUMBER <>", value, "epNumber");
            return this;
        }

        public Criteria andEpNumberGreaterThan(Long value) {
            addCriterion("EP_NUMBER >", value, "epNumber");
            return this;
        }

        public Criteria andEpNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("EP_NUMBER >=", value, "epNumber");
            return this;
        }

        public Criteria andEpNumberLessThan(Long value) {
            addCriterion("EP_NUMBER <", value, "epNumber");
            return this;
        }

        public Criteria andEpNumberLessThanOrEqualTo(Long value) {
            addCriterion("EP_NUMBER <=", value, "epNumber");
            return this;
        }

        public Criteria andEpNumberIn(List values) {
            addCriterion("EP_NUMBER in", values, "epNumber");
            return this;
        }

        public Criteria andEpNumberNotIn(List values) {
            addCriterion("EP_NUMBER not in", values, "epNumber");
            return this;
        }

        public Criteria andEpNumberBetween(Long value1, Long value2) {
            addCriterion("EP_NUMBER between", value1, value2, "epNumber");
            return this;
        }

        public Criteria andEpNumberNotBetween(Long value1, Long value2) {
            addCriterion("EP_NUMBER not between", value1, value2, "epNumber");
            return this;
        }

        public Criteria andEpBudgetIsNull() {
            addCriterion("EP_BUDGET is null");
            return this;
        }

        public Criteria andEpBudgetIsNotNull() {
            addCriterion("EP_BUDGET is not null");
            return this;
        }

        public Criteria andEpBudgetEqualTo(BigDecimal value) {
            addCriterion("EP_BUDGET =", value, "epBudget");
            return this;
        }

        public Criteria andEpBudgetNotEqualTo(BigDecimal value) {
            addCriterion("EP_BUDGET <>", value, "epBudget");
            return this;
        }

        public Criteria andEpBudgetGreaterThan(BigDecimal value) {
            addCriterion("EP_BUDGET >", value, "epBudget");
            return this;
        }

        public Criteria andEpBudgetGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EP_BUDGET >=", value, "epBudget");
            return this;
        }

        public Criteria andEpBudgetLessThan(BigDecimal value) {
            addCriterion("EP_BUDGET <", value, "epBudget");
            return this;
        }

        public Criteria andEpBudgetLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EP_BUDGET <=", value, "epBudget");
            return this;
        }

        public Criteria andEpBudgetIn(List values) {
            addCriterion("EP_BUDGET in", values, "epBudget");
            return this;
        }

        public Criteria andEpBudgetNotIn(List values) {
            addCriterion("EP_BUDGET not in", values, "epBudget");
            return this;
        }

        public Criteria andEpBudgetBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EP_BUDGET between", value1, value2, "epBudget");
            return this;
        }

        public Criteria andEpBudgetNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EP_BUDGET not between", value1, value2, "epBudget");
            return this;
        }

        public Criteria andEpReasonIsNull() {
            addCriterion("EP_REASON is null");
            return this;
        }

        public Criteria andEpReasonIsNotNull() {
            addCriterion("EP_REASON is not null");
            return this;
        }

        public Criteria andEpReasonEqualTo(String value) {
            addCriterion("EP_REASON =", value, "epReason");
            return this;
        }

        public Criteria andEpReasonNotEqualTo(String value) {
            addCriterion("EP_REASON <>", value, "epReason");
            return this;
        }

        public Criteria andEpReasonGreaterThan(String value) {
            addCriterion("EP_REASON >", value, "epReason");
            return this;
        }

        public Criteria andEpReasonGreaterThanOrEqualTo(String value) {
            addCriterion("EP_REASON >=", value, "epReason");
            return this;
        }

        public Criteria andEpReasonLessThan(String value) {
            addCriterion("EP_REASON <", value, "epReason");
            return this;
        }

        public Criteria andEpReasonLessThanOrEqualTo(String value) {
            addCriterion("EP_REASON <=", value, "epReason");
            return this;
        }

        public Criteria andEpReasonLike(String value) {
            addCriterion("EP_REASON like", value, "epReason");
            return this;
        }

        public Criteria andEpReasonNotLike(String value) {
            addCriterion("EP_REASON not like", value, "epReason");
            return this;
        }

        public Criteria andEpReasonIn(List values) {
            addCriterion("EP_REASON in", values, "epReason");
            return this;
        }

        public Criteria andEpReasonNotIn(List values) {
            addCriterion("EP_REASON not in", values, "epReason");
            return this;
        }

        public Criteria andEpReasonBetween(String value1, String value2) {
            addCriterion("EP_REASON between", value1, value2, "epReason");
            return this;
        }

        public Criteria andEpReasonNotBetween(String value1, String value2) {
            addCriterion("EP_REASON not between", value1, value2, "epReason");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateIn(List values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateNotIn(List values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return this;
        }
    }
}