package com.gotop.superviseReceive.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TSuperviceReceiveExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TSuperviceReceiveExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** */
    public TSuperviceReceiveExample() {
        oredCriteria = new ArrayList();
    }

    /** */
    protected TSuperviceReceiveExample(TSuperviceReceiveExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** */
    /** */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_SUPERVICE_RECEIVE
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andRecIdIsNull() {
            addCriterion("REC_ID is null");
            return this;
        }

        public Criteria andRecIdIsNotNull() {
            addCriterion("REC_ID is not null");
            return this;
        }

        public Criteria andRecIdEqualTo(Long value) {
            addCriterion("REC_ID =", value, "recId");
            return this;
        }

        public Criteria andRecIdNotEqualTo(Long value) {
            addCriterion("REC_ID <>", value, "recId");
            return this;
        }

        public Criteria andRecIdGreaterThan(Long value) {
            addCriterion("REC_ID >", value, "recId");
            return this;
        }

        public Criteria andRecIdGreaterThanOrEqualTo(Long value) {
            addCriterion("REC_ID >=", value, "recId");
            return this;
        }

        public Criteria andRecIdLessThan(Long value) {
            addCriterion("REC_ID <", value, "recId");
            return this;
        }

        public Criteria andRecIdLessThanOrEqualTo(Long value) {
            addCriterion("REC_ID <=", value, "recId");
            return this;
        }

        public Criteria andRecIdIn(List values) {
            addCriterion("REC_ID in", values, "recId");
            return this;
        }

        public Criteria andRecIdNotIn(List values) {
            addCriterion("REC_ID not in", values, "recId");
            return this;
        }

        public Criteria andRecIdBetween(Long value1, Long value2) {
            addCriterion("REC_ID between", value1, value2, "recId");
            return this;
        }

        public Criteria andRecIdNotBetween(Long value1, Long value2) {
            addCriterion("REC_ID not between", value1, value2, "recId");
            return this;
        }

        public Criteria andSuperviseIdIsNull() {
            addCriterion("SUPERVISE_ID is null");
            return this;
        }

        public Criteria andSuperviseIdIsNotNull() {
            addCriterion("SUPERVISE_ID is not null");
            return this;
        }

        public Criteria andSuperviseIdEqualTo(Long value) {
            addCriterion("SUPERVISE_ID =", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdNotEqualTo(Long value) {
            addCriterion("SUPERVISE_ID <>", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdGreaterThan(Long value) {
            addCriterion("SUPERVISE_ID >", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SUPERVISE_ID >=", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdLessThan(Long value) {
            addCriterion("SUPERVISE_ID <", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdLessThanOrEqualTo(Long value) {
            addCriterion("SUPERVISE_ID <=", value, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdIn(List values) {
            addCriterion("SUPERVISE_ID in", values, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdNotIn(List values) {
            addCriterion("SUPERVISE_ID not in", values, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdBetween(Long value1, Long value2) {
            addCriterion("SUPERVISE_ID between", value1, value2, "superviseId");
            return this;
        }

        public Criteria andSuperviseIdNotBetween(Long value1, Long value2) {
            addCriterion("SUPERVISE_ID not between", value1, value2, "superviseId");
            return this;
        }

        public Criteria andReceiveEmpIsNull() {
            addCriterion("RECEIVE_EMP is null");
            return this;
        }

        public Criteria andReceiveEmpIsNotNull() {
            addCriterion("RECEIVE_EMP is not null");
            return this;
        }

        public Criteria andReceiveEmpEqualTo(String value) {
            addCriterion("RECEIVE_EMP =", value, "receiveEmp");
            return this;
        }

        public Criteria andReceiveEmpNotEqualTo(String value) {
            addCriterion("RECEIVE_EMP <>", value, "receiveEmp");
            return this;
        }

        public Criteria andReceiveEmpGreaterThan(String value) {
            addCriterion("RECEIVE_EMP >", value, "receiveEmp");
            return this;
        }

        public Criteria andReceiveEmpGreaterThanOrEqualTo(String value) {
            addCriterion("RECEIVE_EMP >=", value, "receiveEmp");
            return this;
        }

        public Criteria andReceiveEmpLessThan(String value) {
            addCriterion("RECEIVE_EMP <", value, "receiveEmp");
            return this;
        }

        public Criteria andReceiveEmpLessThanOrEqualTo(String value) {
            addCriterion("RECEIVE_EMP <=", value, "receiveEmp");
            return this;
        }

        public Criteria andReceiveEmpLike(String value) {
            addCriterion("RECEIVE_EMP like", value, "receiveEmp");
            return this;
        }

        public Criteria andReceiveEmpNotLike(String value) {
            addCriterion("RECEIVE_EMP not like", value, "receiveEmp");
            return this;
        }

        public Criteria andReceiveEmpIn(List values) {
            addCriterion("RECEIVE_EMP in", values, "receiveEmp");
            return this;
        }

        public Criteria andReceiveEmpNotIn(List values) {
            addCriterion("RECEIVE_EMP not in", values, "receiveEmp");
            return this;
        }

        public Criteria andReceiveEmpBetween(String value1, String value2) {
            addCriterion("RECEIVE_EMP between", value1, value2, "receiveEmp");
            return this;
        }

        public Criteria andReceiveEmpNotBetween(String value1, String value2) {
            addCriterion("RECEIVE_EMP not between", value1, value2, "receiveEmp");
            return this;
        }

        public Criteria andContentIsNull() {
            addCriterion("CONTENT is null");
            return this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("CONTENT is not null");
            return this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("CONTENT =", value, "content");
            return this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("CONTENT <>", value, "content");
            return this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("CONTENT >", value, "content");
            return this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT >=", value, "content");
            return this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("CONTENT <", value, "content");
            return this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("CONTENT <=", value, "content");
            return this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("CONTENT like", value, "content");
            return this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("CONTENT not like", value, "content");
            return this;
        }

        public Criteria andContentIn(List values) {
            addCriterion("CONTENT in", values, "content");
            return this;
        }

        public Criteria andContentNotIn(List values) {
            addCriterion("CONTENT not in", values, "content");
            return this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("CONTENT between", value1, value2, "content");
            return this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("CONTENT not between", value1, value2, "content");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("STATUS in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("STATUS not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return this;
        }

        public Criteria andReceiveDateIsNull() {
            addCriterion("RECEIVE_DATE is null");
            return this;
        }

        public Criteria andReceiveDateIsNotNull() {
            addCriterion("RECEIVE_DATE is not null");
            return this;
        }

        public Criteria andReceiveDateEqualTo(String value) {
            addCriterion("RECEIVE_DATE =", value, "receiveDate");
            return this;
        }

        public Criteria andReceiveDateNotEqualTo(String value) {
            addCriterion("RECEIVE_DATE <>", value, "receiveDate");
            return this;
        }

        public Criteria andReceiveDateGreaterThan(String value) {
            addCriterion("RECEIVE_DATE >", value, "receiveDate");
            return this;
        }

        public Criteria andReceiveDateGreaterThanOrEqualTo(String value) {
            addCriterion("RECEIVE_DATE >=", value, "receiveDate");
            return this;
        }

        public Criteria andReceiveDateLessThan(String value) {
            addCriterion("RECEIVE_DATE <", value, "receiveDate");
            return this;
        }

        public Criteria andReceiveDateLessThanOrEqualTo(String value) {
            addCriterion("RECEIVE_DATE <=", value, "receiveDate");
            return this;
        }

        public Criteria andReceiveDateLike(String value) {
            addCriterion("RECEIVE_DATE like", value, "receiveDate");
            return this;
        }

        public Criteria andReceiveDateNotLike(String value) {
            addCriterion("RECEIVE_DATE not like", value, "receiveDate");
            return this;
        }

        public Criteria andReceiveDateIn(List values) {
            addCriterion("RECEIVE_DATE in", values, "receiveDate");
            return this;
        }

        public Criteria andReceiveDateNotIn(List values) {
            addCriterion("RECEIVE_DATE not in", values, "receiveDate");
            return this;
        }

        public Criteria andReceiveDateBetween(String value1, String value2) {
            addCriterion("RECEIVE_DATE between", value1, value2, "receiveDate");
            return this;
        }

        public Criteria andReceiveDateNotBetween(String value1, String value2) {
            addCriterion("RECEIVE_DATE not between", value1, value2, "receiveDate");
            return this;
        }

        public Criteria andReceiveTimeIsNull() {
            addCriterion("RECEIVE_TIME is null");
            return this;
        }

        public Criteria andReceiveTimeIsNotNull() {
            addCriterion("RECEIVE_TIME is not null");
            return this;
        }

        public Criteria andReceiveTimeEqualTo(String value) {
            addCriterion("RECEIVE_TIME =", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeNotEqualTo(String value) {
            addCriterion("RECEIVE_TIME <>", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeGreaterThan(String value) {
            addCriterion("RECEIVE_TIME >", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeGreaterThanOrEqualTo(String value) {
            addCriterion("RECEIVE_TIME >=", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeLessThan(String value) {
            addCriterion("RECEIVE_TIME <", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeLessThanOrEqualTo(String value) {
            addCriterion("RECEIVE_TIME <=", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeLike(String value) {
            addCriterion("RECEIVE_TIME like", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeNotLike(String value) {
            addCriterion("RECEIVE_TIME not like", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeIn(List values) {
            addCriterion("RECEIVE_TIME in", values, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeNotIn(List values) {
            addCriterion("RECEIVE_TIME not in", values, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeBetween(String value1, String value2) {
            addCriterion("RECEIVE_TIME between", value1, value2, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeNotBetween(String value1, String value2) {
            addCriterion("RECEIVE_TIME not between", value1, value2, "receiveTime");
            return this;
        }

        public Criteria andNodeIdIsNull() {
            addCriterion("NODE_ID is null");
            return this;
        }

        public Criteria andNodeIdIsNotNull() {
            addCriterion("NODE_ID is not null");
            return this;
        }

        public Criteria andNodeIdEqualTo(String value) {
            addCriterion("NODE_ID =", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdNotEqualTo(String value) {
            addCriterion("NODE_ID <>", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdGreaterThan(String value) {
            addCriterion("NODE_ID >", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdGreaterThanOrEqualTo(String value) {
            addCriterion("NODE_ID >=", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdLessThan(String value) {
            addCriterion("NODE_ID <", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdLessThanOrEqualTo(String value) {
            addCriterion("NODE_ID <=", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdLike(String value) {
            addCriterion("NODE_ID like", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdNotLike(String value) {
            addCriterion("NODE_ID not like", value, "nodeId");
            return this;
        }

        public Criteria andNodeIdIn(List values) {
            addCriterion("NODE_ID in", values, "nodeId");
            return this;
        }

        public Criteria andNodeIdNotIn(List values) {
            addCriterion("NODE_ID not in", values, "nodeId");
            return this;
        }

        public Criteria andNodeIdBetween(String value1, String value2) {
            addCriterion("NODE_ID between", value1, value2, "nodeId");
            return this;
        }

        public Criteria andNodeIdNotBetween(String value1, String value2) {
            addCriterion("NODE_ID not between", value1, value2, "nodeId");
            return this;
        }

        public Criteria andNodeNameIsNull() {
            addCriterion("NODE_NAME is null");
            return this;
        }

        public Criteria andNodeNameIsNotNull() {
            addCriterion("NODE_NAME is not null");
            return this;
        }

        public Criteria andNodeNameEqualTo(String value) {
            addCriterion("NODE_NAME =", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameNotEqualTo(String value) {
            addCriterion("NODE_NAME <>", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameGreaterThan(String value) {
            addCriterion("NODE_NAME >", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameGreaterThanOrEqualTo(String value) {
            addCriterion("NODE_NAME >=", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameLessThan(String value) {
            addCriterion("NODE_NAME <", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameLessThanOrEqualTo(String value) {
            addCriterion("NODE_NAME <=", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameLike(String value) {
            addCriterion("NODE_NAME like", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameNotLike(String value) {
            addCriterion("NODE_NAME not like", value, "nodeName");
            return this;
        }

        public Criteria andNodeNameIn(List values) {
            addCriterion("NODE_NAME in", values, "nodeName");
            return this;
        }

        public Criteria andNodeNameNotIn(List values) {
            addCriterion("NODE_NAME not in", values, "nodeName");
            return this;
        }

        public Criteria andNodeNameBetween(String value1, String value2) {
            addCriterion("NODE_NAME between", value1, value2, "nodeName");
            return this;
        }

        public Criteria andNodeNameNotBetween(String value1, String value2) {
            addCriterion("NODE_NAME not between", value1, value2, "nodeName");
            return this;
        }
    }
}