package test.gotop.crm.demo.model.datacell;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class AbfTGgbExample {

	/**
	 * @abatorgenerated
	 */
	protected Logger log = Logger.getLogger(AbfTGgbExample.class);
	/**
	 * 排序字段.
	 * @abatorgenerated
	 */
	protected String orderByClause;
	/**
	 * sql条件.
	 * @abatorgenerated
	 */
	protected List oredCriteria;
	/**
	 * 分页查询的起始行数.
	 * @abatorgenerated
	 */
	private Integer oracleStart;
	/**
	 * 分页查询结束行数.
	 * @abatorgenerated
	 */
	private Integer oracleEnd;

	/**
	 * @abatorgenerated  
	 */
	public AbfTGgbExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * @abatorgenerated  
	 */
	protected AbfTGgbExample(AbfTGgbExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
		this.oracleStart = example.oracleStart;
		this.oracleEnd = example.oracleEnd;
	}

	/**
	 * @abatorgenerated  
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * @abatorgenerated  
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * @abatorgenerated  
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * @abatorgenerated  
	 */
	public Integer getOracleStart() {
		return oracleStart;
	}

	/**
	 * @abatorgenerated  
	 */
	public void setOracleStart(Integer oracleStart) {
		this.oracleStart = oracleStart;
	}

	/**
	 * @abatorgenerated  
	 */
	public Integer getOracleEnd() {
		return oracleEnd;
	}

	/**
	 * @abatorgenerated  
	 */
	public void setOracleEnd(Integer oracleEnd) {
		this.oracleEnd = oracleEnd;
	}

	/**
	 * 增加整个新查询条件(Criteria)，增加后以or方式查询.
	 * @abatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
	 * @abatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * 仅创新新Criteria,并且返回
	 * @abatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * 清除查询条件
	 * @abatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table BKLS.ABF_T_GGB
	 * @abatorgenerated  Fri Nov 18 10:28:06 CST 2011
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIGgbhIsNull() {
			addCriterion("a.I_GGBH is null");
			return this;
		}

		public Criteria andIGgbhIsNotNull() {
			addCriterion("a.I_GGBH is not null");
			return this;
		}

		public Criteria andIGgbhEqualTo(Integer value) {
			addCriterion("a.I_GGBH =", value, "iGgbh");
			return this;
		}

		public Criteria andIGgbhNotEqualTo(Integer value) {
			addCriterion("a.I_GGBH <>", value, "iGgbh");
			return this;
		}

		public Criteria andIGgbhGreaterThan(Integer value) {
			addCriterion("a.I_GGBH >", value, "iGgbh");
			return this;
		}

		public Criteria andIGgbhGreaterThanOrEqualTo(Integer value) {
			addCriterion("a.I_GGBH >=", value, "iGgbh");
			return this;
		}

		public Criteria andIGgbhLessThan(Integer value) {
			addCriterion("a.I_GGBH <", value, "iGgbh");
			return this;
		}

		public Criteria andIGgbhLessThanOrEqualTo(Integer value) {
			addCriterion("a.I_GGBH <=", value, "iGgbh");
			return this;
		}

		public Criteria andIGgbhIn(List values) {
			addCriterion("a.I_GGBH in", values, "iGgbh");
			return this;
		}

		public Criteria andIGgbhNotIn(List values) {
			addCriterion("a.I_GGBH not in", values, "iGgbh");
			return this;
		}

		public Criteria andIGgbhBetween(Integer value1, Integer value2) {
			addCriterion("a.I_GGBH between", value1, value2, "iGgbh");
			return this;
		}

		public Criteria andIGgbhNotBetween(Integer value1, Integer value2) {
			addCriterion("a.I_GGBH not between", value1, value2, "iGgbh");
			return this;
		}

		public Criteria andVGgxxIsNull() {
			addCriterion("a.V_GGXX is null");
			return this;
		}

		public Criteria andVGgxxIsNotNull() {
			addCriterion("a.V_GGXX is not null");
			return this;
		}

		public Criteria andVGgxxEqualTo(String value) {
			addCriterion("a.V_GGXX =", value, "vGgxx");
			return this;
		}

		public Criteria andVGgxxNotEqualTo(String value) {
			addCriterion("a.V_GGXX <>", value, "vGgxx");
			return this;
		}

		public Criteria andVGgxxGreaterThan(String value) {
			addCriterion("a.V_GGXX >", value, "vGgxx");
			return this;
		}

		public Criteria andVGgxxGreaterThanOrEqualTo(String value) {
			addCriterion("a.V_GGXX >=", value, "vGgxx");
			return this;
		}

		public Criteria andVGgxxLessThan(String value) {
			addCriterion("a.V_GGXX <", value, "vGgxx");
			return this;
		}

		public Criteria andVGgxxLessThanOrEqualTo(String value) {
			addCriterion("a.V_GGXX <=", value, "vGgxx");
			return this;
		}

		public Criteria andVGgxxLike(String value) {
			addCriterion("a.V_GGXX like", value, "vGgxx");
			return this;
		}

		public Criteria andVGgxxNotLike(String value) {
			addCriterion("a.V_GGXX not like", value, "vGgxx");
			return this;
		}

		public Criteria andVGgxxIn(List values) {
			addCriterion("a.V_GGXX in", values, "vGgxx");
			return this;
		}

		public Criteria andVGgxxNotIn(List values) {
			addCriterion("a.V_GGXX not in", values, "vGgxx");
			return this;
		}

		public Criteria andVGgxxBetween(String value1, String value2) {
			addCriterion("a.V_GGXX between", value1, value2, "vGgxx");
			return this;
		}

		public Criteria andVGgxxNotBetween(String value1, String value2) {
			addCriterion("a.V_GGXX not between", value1, value2, "vGgxx");
			return this;
		}

		public Criteria andVFbrIsNull() {
			addCriterion("a.V_FBR is null");
			return this;
		}

		public Criteria andVFbrIsNotNull() {
			addCriterion("a.V_FBR is not null");
			return this;
		}

		public Criteria andVFbrEqualTo(String value) {
			addCriterion("a.V_FBR =", value, "vFbr");
			return this;
		}

		public Criteria andVFbrNotEqualTo(String value) {
			addCriterion("a.V_FBR <>", value, "vFbr");
			return this;
		}

		public Criteria andVFbrGreaterThan(String value) {
			addCriterion("a.V_FBR >", value, "vFbr");
			return this;
		}

		public Criteria andVFbrGreaterThanOrEqualTo(String value) {
			addCriterion("a.V_FBR >=", value, "vFbr");
			return this;
		}

		public Criteria andVFbrLessThan(String value) {
			addCriterion("a.V_FBR <", value, "vFbr");
			return this;
		}

		public Criteria andVFbrLessThanOrEqualTo(String value) {
			addCriterion("a.V_FBR <=", value, "vFbr");
			return this;
		}

		public Criteria andVFbrLike(String value) {
			addCriterion("a.V_FBR like", value, "vFbr");
			return this;
		}

		public Criteria andVFbrNotLike(String value) {
			addCriterion("a.V_FBR not like", value, "vFbr");
			return this;
		}

		public Criteria andVFbrIn(List values) {
			addCriterion("a.V_FBR in", values, "vFbr");
			return this;
		}

		public Criteria andVFbrNotIn(List values) {
			addCriterion("a.V_FBR not in", values, "vFbr");
			return this;
		}

		public Criteria andVFbrBetween(String value1, String value2) {
			addCriterion("a.V_FBR between", value1, value2, "vFbr");
			return this;
		}

		public Criteria andVFbrNotBetween(String value1, String value2) {
			addCriterion("a.V_FBR not between", value1, value2, "vFbr");
			return this;
		}

		public Criteria andDFbsjIsNull() {
			addCriterion("a.D_FBSJ is null");
			return this;
		}

		public Criteria andDFbsjIsNotNull() {
			addCriterion("a.D_FBSJ is not null");
			return this;
		}

		public Criteria andDFbsjEqualTo(Date value) {
			addCriterion("a.D_FBSJ =", value, "dFbsj");
			return this;
		}

		public Criteria andDFbsjNotEqualTo(Date value) {
			addCriterion("a.D_FBSJ <>", value, "dFbsj");
			return this;
		}

		public Criteria andDFbsjGreaterThan(Date value) {
			addCriterion("a.D_FBSJ >", value, "dFbsj");
			return this;
		}

		public Criteria andDFbsjGreaterThanOrEqualTo(Date value) {
			addCriterion("a.D_FBSJ >=", value, "dFbsj");
			return this;
		}

		public Criteria andDFbsjLessThan(Date value) {
			addCriterion("a.D_FBSJ <", value, "dFbsj");
			return this;
		}

		public Criteria andDFbsjLessThanOrEqualTo(Date value) {
			addCriterion("a.D_FBSJ <=", value, "dFbsj");
			return this;
		}

		public Criteria andDFbsjIn(List values) {
			addCriterion("a.D_FBSJ in", values, "dFbsj");
			return this;
		}

		public Criteria andDFbsjNotIn(List values) {
			addCriterion("a.D_FBSJ not in", values, "dFbsj");
			return this;
		}

		public Criteria andDFbsjBetween(Date value1, Date value2) {
			addCriterion("a.D_FBSJ between", value1, value2, "dFbsj");
			return this;
		}

		public Criteria andDFbsjNotBetween(Date value1, Date value2) {
			addCriterion("a.D_FBSJ not between", value1, value2, "dFbsj");
			return this;
		}

		public Criteria andVGgbtIsNull() {
			addCriterion("a.V_GGBT is null");
			return this;
		}

		public Criteria andVGgbtIsNotNull() {
			addCriterion("a.V_GGBT is not null");
			return this;
		}

		public Criteria andVGgbtEqualTo(String value) {
			addCriterion("a.V_GGBT =", value, "vGgbt");
			return this;
		}

		public Criteria andVGgbtNotEqualTo(String value) {
			addCriterion("a.V_GGBT <>", value, "vGgbt");
			return this;
		}

		public Criteria andVGgbtGreaterThan(String value) {
			addCriterion("a.V_GGBT >", value, "vGgbt");
			return this;
		}

		public Criteria andVGgbtGreaterThanOrEqualTo(String value) {
			addCriterion("a.V_GGBT >=", value, "vGgbt");
			return this;
		}

		public Criteria andVGgbtLessThan(String value) {
			addCriterion("a.V_GGBT <", value, "vGgbt");
			return this;
		}

		public Criteria andVGgbtLessThanOrEqualTo(String value) {
			addCriterion("a.V_GGBT <=", value, "vGgbt");
			return this;
		}

		public Criteria andVGgbtLike(String value) {
			addCriterion("a.V_GGBT like", value, "vGgbt");
			return this;
		}

		public Criteria andVGgbtNotLike(String value) {
			addCriterion("a.V_GGBT not like", value, "vGgbt");
			return this;
		}

		public Criteria andVGgbtIn(List values) {
			addCriterion("a.V_GGBT in", values, "vGgbt");
			return this;
		}

		public Criteria andVGgbtNotIn(List values) {
			addCriterion("a.V_GGBT not in", values, "vGgbt");
			return this;
		}

		public Criteria andVGgbtBetween(String value1, String value2) {
			addCriterion("a.V_GGBT between", value1, value2, "vGgbt");
			return this;
		}

		public Criteria andVGgbtNotBetween(String value1, String value2) {
			addCriterion("a.V_GGBT not between", value1, value2, "vGgbt");
			return this;
		}

		public Criteria andVFbfwIsNull() {
			addCriterion("a.V_FBFW is null");
			return this;
		}

		public Criteria andVFbfwIsNotNull() {
			addCriterion("a.V_FBFW is not null");
			return this;
		}

		public Criteria andVFbfwEqualTo(String value) {
			addCriterion("a.V_FBFW =", value, "vFbfw");
			return this;
		}

		public Criteria andVFbfwNotEqualTo(String value) {
			addCriterion("a.V_FBFW <>", value, "vFbfw");
			return this;
		}

		public Criteria andVFbfwGreaterThan(String value) {
			addCriterion("a.V_FBFW >", value, "vFbfw");
			return this;
		}

		public Criteria andVFbfwGreaterThanOrEqualTo(String value) {
			addCriterion("a.V_FBFW >=", value, "vFbfw");
			return this;
		}

		public Criteria andVFbfwLessThan(String value) {
			addCriterion("a.V_FBFW <", value, "vFbfw");
			return this;
		}

		public Criteria andVFbfwLessThanOrEqualTo(String value) {
			addCriterion("a.V_FBFW <=", value, "vFbfw");
			return this;
		}

		public Criteria andVFbfwLike(String value) {
			addCriterion("a.V_FBFW like", value, "vFbfw");
			return this;
		}

		public Criteria andVFbfwNotLike(String value) {
			addCriterion("a.V_FBFW not like", value, "vFbfw");
			return this;
		}

		public Criteria andVFbfwIn(List values) {
			addCriterion("a.V_FBFW in", values, "vFbfw");
			return this;
		}

		public Criteria andVFbfwNotIn(List values) {
			addCriterion("a.V_FBFW not in", values, "vFbfw");
			return this;
		}

		public Criteria andVFbfwBetween(String value1, String value2) {
			addCriterion("a.V_FBFW between", value1, value2, "vFbfw");
			return this;
		}

		public Criteria andVFbfwNotBetween(String value1, String value2) {
			addCriterion("a.V_FBFW not between", value1, value2, "vFbfw");
			return this;
		}

		public Criteria andVBlqxIsNull() {
			addCriterion("a.V_BLQX is null");
			return this;
		}

		public Criteria andVBlqxIsNotNull() {
			addCriterion("a.V_BLQX is not null");
			return this;
		}

		public Criteria andVBlqxEqualTo(String value) {
			addCriterion("a.V_BLQX =", value, "vBlqx");
			return this;
		}

		public Criteria andVBlqxNotEqualTo(String value) {
			addCriterion("a.V_BLQX <>", value, "vBlqx");
			return this;
		}

		public Criteria andVBlqxGreaterThan(String value) {
			addCriterion("a.V_BLQX >", value, "vBlqx");
			return this;
		}

		public Criteria andVBlqxGreaterThanOrEqualTo(String value) {
			addCriterion("a.V_BLQX >=", value, "vBlqx");
			return this;
		}

		public Criteria andVBlqxLessThan(String value) {
			addCriterion("a.V_BLQX <", value, "vBlqx");
			return this;
		}

		public Criteria andVBlqxLessThanOrEqualTo(String value) {
			addCriterion("a.V_BLQX <=", value, "vBlqx");
			return this;
		}

		public Criteria andVBlqxLike(String value) {
			addCriterion("a.V_BLQX like", value, "vBlqx");
			return this;
		}

		public Criteria andVBlqxNotLike(String value) {
			addCriterion("a.V_BLQX not like", value, "vBlqx");
			return this;
		}

		public Criteria andVBlqxIn(List values) {
			addCriterion("a.V_BLQX in", values, "vBlqx");
			return this;
		}

		public Criteria andVBlqxNotIn(List values) {
			addCriterion("a.V_BLQX not in", values, "vBlqx");
			return this;
		}

		public Criteria andVBlqxBetween(String value1, String value2) {
			addCriterion("a.V_BLQX between", value1, value2, "vBlqx");
			return this;
		}

		public Criteria andVBlqxNotBetween(String value1, String value2) {
			addCriterion("a.V_BLQX not between", value1, value2, "vBlqx");
			return this;
		}

		public Criteria andVGgfjIsNull() {
			addCriterion("a.V_GGFJ is null");
			return this;
		}

		public Criteria andVGgfjIsNotNull() {
			addCriterion("a.V_GGFJ is not null");
			return this;
		}

		public Criteria andVGgfjEqualTo(String value) {
			addCriterion("a.V_GGFJ =", value, "vGgfj");
			return this;
		}

		public Criteria andVGgfjNotEqualTo(String value) {
			addCriterion("a.V_GGFJ <>", value, "vGgfj");
			return this;
		}

		public Criteria andVGgfjGreaterThan(String value) {
			addCriterion("a.V_GGFJ >", value, "vGgfj");
			return this;
		}

		public Criteria andVGgfjGreaterThanOrEqualTo(String value) {
			addCriterion("a.V_GGFJ >=", value, "vGgfj");
			return this;
		}

		public Criteria andVGgfjLessThan(String value) {
			addCriterion("a.V_GGFJ <", value, "vGgfj");
			return this;
		}

		public Criteria andVGgfjLessThanOrEqualTo(String value) {
			addCriterion("a.V_GGFJ <=", value, "vGgfj");
			return this;
		}

		public Criteria andVGgfjLike(String value) {
			addCriterion("a.V_GGFJ like", value, "vGgfj");
			return this;
		}

		public Criteria andVGgfjNotLike(String value) {
			addCriterion("a.V_GGFJ not like", value, "vGgfj");
			return this;
		}

		public Criteria andVGgfjIn(List values) {
			addCriterion("a.V_GGFJ in", values, "vGgfj");
			return this;
		}

		public Criteria andVGgfjNotIn(List values) {
			addCriterion("a.V_GGFJ not in", values, "vGgfj");
			return this;
		}

		public Criteria andVGgfjBetween(String value1, String value2) {
			addCriterion("a.V_GGFJ between", value1, value2, "vGgfj");
			return this;
		}

		public Criteria andVGgfjNotBetween(String value1, String value2) {
			addCriterion("a.V_GGFJ not between", value1, value2, "vGgfj");
			return this;
		}

		public Criteria andVShrIsNull() {
			addCriterion("a.V_SHR is null");
			return this;
		}

		public Criteria andVShrIsNotNull() {
			addCriterion("a.V_SHR is not null");
			return this;
		}

		public Criteria andVShrEqualTo(String value) {
			addCriterion("a.V_SHR =", value, "vShr");
			return this;
		}

		public Criteria andVShrNotEqualTo(String value) {
			addCriterion("a.V_SHR <>", value, "vShr");
			return this;
		}

		public Criteria andVShrGreaterThan(String value) {
			addCriterion("a.V_SHR >", value, "vShr");
			return this;
		}

		public Criteria andVShrGreaterThanOrEqualTo(String value) {
			addCriterion("a.V_SHR >=", value, "vShr");
			return this;
		}

		public Criteria andVShrLessThan(String value) {
			addCriterion("a.V_SHR <", value, "vShr");
			return this;
		}

		public Criteria andVShrLessThanOrEqualTo(String value) {
			addCriterion("a.V_SHR <=", value, "vShr");
			return this;
		}

		public Criteria andVShrLike(String value) {
			addCriterion("a.V_SHR like", value, "vShr");
			return this;
		}

		public Criteria andVShrNotLike(String value) {
			addCriterion("a.V_SHR not like", value, "vShr");
			return this;
		}

		public Criteria andVShrIn(List values) {
			addCriterion("a.V_SHR in", values, "vShr");
			return this;
		}

		public Criteria andVShrNotIn(List values) {
			addCriterion("a.V_SHR not in", values, "vShr");
			return this;
		}

		public Criteria andVShrBetween(String value1, String value2) {
			addCriterion("a.V_SHR between", value1, value2, "vShr");
			return this;
		}

		public Criteria andVShrNotBetween(String value1, String value2) {
			addCriterion("a.V_SHR not between", value1, value2, "vShr");
			return this;
		}

		public Criteria andVShyjIsNull() {
			addCriterion("a.V_SHYJ is null");
			return this;
		}

		public Criteria andVShyjIsNotNull() {
			addCriterion("a.V_SHYJ is not null");
			return this;
		}

		public Criteria andVShyjEqualTo(String value) {
			addCriterion("a.V_SHYJ =", value, "vShyj");
			return this;
		}

		public Criteria andVShyjNotEqualTo(String value) {
			addCriterion("a.V_SHYJ <>", value, "vShyj");
			return this;
		}

		public Criteria andVShyjGreaterThan(String value) {
			addCriterion("a.V_SHYJ >", value, "vShyj");
			return this;
		}

		public Criteria andVShyjGreaterThanOrEqualTo(String value) {
			addCriterion("a.V_SHYJ >=", value, "vShyj");
			return this;
		}

		public Criteria andVShyjLessThan(String value) {
			addCriterion("a.V_SHYJ <", value, "vShyj");
			return this;
		}

		public Criteria andVShyjLessThanOrEqualTo(String value) {
			addCriterion("a.V_SHYJ <=", value, "vShyj");
			return this;
		}

		public Criteria andVShyjLike(String value) {
			addCriterion("a.V_SHYJ like", value, "vShyj");
			return this;
		}

		public Criteria andVShyjNotLike(String value) {
			addCriterion("a.V_SHYJ not like", value, "vShyj");
			return this;
		}

		public Criteria andVShyjIn(List values) {
			addCriterion("a.V_SHYJ in", values, "vShyj");
			return this;
		}

		public Criteria andVShyjNotIn(List values) {
			addCriterion("a.V_SHYJ not in", values, "vShyj");
			return this;
		}

		public Criteria andVShyjBetween(String value1, String value2) {
			addCriterion("a.V_SHYJ between", value1, value2, "vShyj");
			return this;
		}

		public Criteria andVShyjNotBetween(String value1, String value2) {
			addCriterion("a.V_SHYJ not between", value1, value2, "vShyj");
			return this;
		}

		public Criteria andVGgztIsNull() {
			addCriterion("a.V_GGZT is null");
			return this;
		}

		public Criteria andVGgztIsNotNull() {
			addCriterion("a.V_GGZT is not null");
			return this;
		}

		public Criteria andVGgztEqualTo(String value) {
			addCriterion("a.V_GGZT =", value, "vGgzt");
			return this;
		}

		public Criteria andVGgztNotEqualTo(String value) {
			addCriterion("a.V_GGZT <>", value, "vGgzt");
			return this;
		}

		public Criteria andVGgztGreaterThan(String value) {
			addCriterion("a.V_GGZT >", value, "vGgzt");
			return this;
		}

		public Criteria andVGgztGreaterThanOrEqualTo(String value) {
			addCriterion("a.V_GGZT >=", value, "vGgzt");
			return this;
		}

		public Criteria andVGgztLessThan(String value) {
			addCriterion("a.V_GGZT <", value, "vGgzt");
			return this;
		}

		public Criteria andVGgztLessThanOrEqualTo(String value) {
			addCriterion("a.V_GGZT <=", value, "vGgzt");
			return this;
		}

		public Criteria andVGgztLike(String value) {
			addCriterion("a.V_GGZT like", value, "vGgzt");
			return this;
		}

		public Criteria andVGgztNotLike(String value) {
			addCriterion("a.V_GGZT not like", value, "vGgzt");
			return this;
		}

		public Criteria andVGgztIn(List values) {
			addCriterion("a.V_GGZT in", values, "vGgzt");
			return this;
		}

		public Criteria andVGgztNotIn(List values) {
			addCriterion("a.V_GGZT not in", values, "vGgzt");
			return this;
		}

		public Criteria andVGgztBetween(String value1, String value2) {
			addCriterion("a.V_GGZT between", value1, value2, "vGgzt");
			return this;
		}

		public Criteria andVGgztNotBetween(String value1, String value2) {
			addCriterion("a.V_GGZT not between", value1, value2, "vGgzt");
			return this;
		}

		public Criteria andFillerIsNull() {
			addCriterion("a.FILLER is null");
			return this;
		}

		public Criteria andFillerIsNotNull() {
			addCriterion("a.FILLER is not null");
			return this;
		}

		public Criteria andFillerEqualTo(String value) {
			addCriterion("a.FILLER =", value, "filler");
			return this;
		}

		public Criteria andFillerNotEqualTo(String value) {
			addCriterion("a.FILLER <>", value, "filler");
			return this;
		}

		public Criteria andFillerGreaterThan(String value) {
			addCriterion("a.FILLER >", value, "filler");
			return this;
		}

		public Criteria andFillerGreaterThanOrEqualTo(String value) {
			addCriterion("a.FILLER >=", value, "filler");
			return this;
		}

		public Criteria andFillerLessThan(String value) {
			addCriterion("a.FILLER <", value, "filler");
			return this;
		}

		public Criteria andFillerLessThanOrEqualTo(String value) {
			addCriterion("a.FILLER <=", value, "filler");
			return this;
		}

		public Criteria andFillerLike(String value) {
			addCriterion("a.FILLER like", value, "filler");
			return this;
		}

		public Criteria andFillerNotLike(String value) {
			addCriterion("a.FILLER not like", value, "filler");
			return this;
		}

		public Criteria andFillerIn(List values) {
			addCriterion("a.FILLER in", values, "filler");
			return this;
		}

		public Criteria andFillerNotIn(List values) {
			addCriterion("a.FILLER not in", values, "filler");
			return this;
		}

		public Criteria andFillerBetween(String value1, String value2) {
			addCriterion("a.FILLER between", value1, value2, "filler");
			return this;
		}

		public Criteria andFillerNotBetween(String value1, String value2) {
			addCriterion("a.FILLER not between", value1, value2, "filler");
			return this;
		}

		public Criteria andVXtmcIsNull() {
			addCriterion("a.V_XTMC is null");
			return this;
		}

		public Criteria andVXtmcIsNotNull() {
			addCriterion("a.V_XTMC is not null");
			return this;
		}

		public Criteria andVXtmcEqualTo(String value) {
			addCriterion("a.V_XTMC =", value, "vXtmc");
			return this;
		}

		public Criteria andVXtmcNotEqualTo(String value) {
			addCriterion("a.V_XTMC <>", value, "vXtmc");
			return this;
		}

		public Criteria andVXtmcGreaterThan(String value) {
			addCriterion("a.V_XTMC >", value, "vXtmc");
			return this;
		}

		public Criteria andVXtmcGreaterThanOrEqualTo(String value) {
			addCriterion("a.V_XTMC >=", value, "vXtmc");
			return this;
		}

		public Criteria andVXtmcLessThan(String value) {
			addCriterion("a.V_XTMC <", value, "vXtmc");
			return this;
		}

		public Criteria andVXtmcLessThanOrEqualTo(String value) {
			addCriterion("a.V_XTMC <=", value, "vXtmc");
			return this;
		}

		public Criteria andVXtmcLike(String value) {
			addCriterion("a.V_XTMC like", value, "vXtmc");
			return this;
		}

		public Criteria andVXtmcNotLike(String value) {
			addCriterion("a.V_XTMC not like", value, "vXtmc");
			return this;
		}

		public Criteria andVXtmcIn(List values) {
			addCriterion("a.V_XTMC in", values, "vXtmc");
			return this;
		}

		public Criteria andVXtmcNotIn(List values) {
			addCriterion("a.V_XTMC not in", values, "vXtmc");
			return this;
		}

		public Criteria andVXtmcBetween(String value1, String value2) {
			addCriterion("a.V_XTMC between", value1, value2, "vXtmc");
			return this;
		}

		public Criteria andVXtmcNotBetween(String value1, String value2) {
			addCriterion("a.V_XTMC not between", value1, value2, "vXtmc");
			return this;
		}
	}
}