package test.gotop.crm.demo.model.datacell;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class AbfTJgfjxxbExample {

	/**
	 * @abatorgenerated
	 */
	protected Logger log = Logger.getLogger(AbfTJgfjxxbExample.class);
	/**
	 * 排序字段.
	 * @abatorgenerated
	 */
	protected String orderByClause;
	/**
	 * sql条件.
	 * @abatorgenerated
	 */
	protected List oredCriteria;
	/**
	 * 分页查询的起始行数.
	 * @abatorgenerated
	 */
	private Integer oracleStart;
	/**
	 * 分页查询结束行数.
	 * @abatorgenerated
	 */
	private Integer oracleEnd;

	/**
	 * @abatorgenerated  
	 */
	public AbfTJgfjxxbExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * @abatorgenerated  
	 */
	protected AbfTJgfjxxbExample(AbfTJgfjxxbExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
		this.oracleStart = example.oracleStart;
		this.oracleEnd = example.oracleEnd;
	}

	/**
	 * @abatorgenerated  
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * @abatorgenerated  
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * @abatorgenerated  
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * @abatorgenerated  
	 */
	public Integer getOracleStart() {
		return oracleStart;
	}

	/**
	 * @abatorgenerated  
	 */
	public void setOracleStart(Integer oracleStart) {
		this.oracleStart = oracleStart;
	}

	/**
	 * @abatorgenerated  
	 */
	public Integer getOracleEnd() {
		return oracleEnd;
	}

	/**
	 * @abatorgenerated  
	 */
	public void setOracleEnd(Integer oracleEnd) {
		this.oracleEnd = oracleEnd;
	}

	/**
	 * 增加整个新查询条件(Criteria)，增加后以or方式查询.
	 * @abatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
	 * @abatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * 仅创新新Criteria,并且返回
	 * @abatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * 清除查询条件
	 * @abatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table BKLS.ABF_T_JGFJXXB
	 * @abatorgenerated  Fri Nov 18 10:28:06 CST 2011
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andOrgidIsNull() {
			addCriterion("a.ORGID is null");
			return this;
		}

		public Criteria andOrgidIsNotNull() {
			addCriterion("a.ORGID is not null");
			return this;
		}

		public Criteria andOrgidEqualTo(Integer value) {
			addCriterion("a.ORGID =", value, "orgid");
			return this;
		}

		public Criteria andOrgidNotEqualTo(Integer value) {
			addCriterion("a.ORGID <>", value, "orgid");
			return this;
		}

		public Criteria andOrgidGreaterThan(Integer value) {
			addCriterion("a.ORGID >", value, "orgid");
			return this;
		}

		public Criteria andOrgidGreaterThanOrEqualTo(Integer value) {
			addCriterion("a.ORGID >=", value, "orgid");
			return this;
		}

		public Criteria andOrgidLessThan(Integer value) {
			addCriterion("a.ORGID <", value, "orgid");
			return this;
		}

		public Criteria andOrgidLessThanOrEqualTo(Integer value) {
			addCriterion("a.ORGID <=", value, "orgid");
			return this;
		}

		public Criteria andOrgidIn(List values) {
			addCriterion("a.ORGID in", values, "orgid");
			return this;
		}

		public Criteria andOrgidNotIn(List values) {
			addCriterion("a.ORGID not in", values, "orgid");
			return this;
		}

		public Criteria andOrgidBetween(Integer value1, Integer value2) {
			addCriterion("a.ORGID between", value1, value2, "orgid");
			return this;
		}

		public Criteria andOrgidNotBetween(Integer value1, Integer value2) {
			addCriterion("a.ORGID not between", value1, value2, "orgid");
			return this;
		}

		public Criteria andManapositionIsNull() {
			addCriterion("a.MANAPOSITION is null");
			return this;
		}

		public Criteria andManapositionIsNotNull() {
			addCriterion("a.MANAPOSITION is not null");
			return this;
		}

		public Criteria andManapositionEqualTo(Integer value) {
			addCriterion("a.MANAPOSITION =", value, "manaposition");
			return this;
		}

		public Criteria andManapositionNotEqualTo(Integer value) {
			addCriterion("a.MANAPOSITION <>", value, "manaposition");
			return this;
		}

		public Criteria andManapositionGreaterThan(Integer value) {
			addCriterion("a.MANAPOSITION >", value, "manaposition");
			return this;
		}

		public Criteria andManapositionGreaterThanOrEqualTo(Integer value) {
			addCriterion("a.MANAPOSITION >=", value, "manaposition");
			return this;
		}

		public Criteria andManapositionLessThan(Integer value) {
			addCriterion("a.MANAPOSITION <", value, "manaposition");
			return this;
		}

		public Criteria andManapositionLessThanOrEqualTo(Integer value) {
			addCriterion("a.MANAPOSITION <=", value, "manaposition");
			return this;
		}

		public Criteria andManapositionIn(List values) {
			addCriterion("a.MANAPOSITION in", values, "manaposition");
			return this;
		}

		public Criteria andManapositionNotIn(List values) {
			addCriterion("a.MANAPOSITION not in", values, "manaposition");
			return this;
		}

		public Criteria andManapositionBetween(Integer value1, Integer value2) {
			addCriterion("a.MANAPOSITION between", value1, value2,
					"manaposition");
			return this;
		}

		public Criteria andManapositionNotBetween(Integer value1, Integer value2) {
			addCriterion("a.MANAPOSITION not between", value1, value2,
					"manaposition");
			return this;
		}

		public Criteria andManageridIsNull() {
			addCriterion("a.MANAGERID is null");
			return this;
		}

		public Criteria andManageridIsNotNull() {
			addCriterion("a.MANAGERID is not null");
			return this;
		}

		public Criteria andManageridEqualTo(Integer value) {
			addCriterion("a.MANAGERID =", value, "managerid");
			return this;
		}

		public Criteria andManageridNotEqualTo(Integer value) {
			addCriterion("a.MANAGERID <>", value, "managerid");
			return this;
		}

		public Criteria andManageridGreaterThan(Integer value) {
			addCriterion("a.MANAGERID >", value, "managerid");
			return this;
		}

		public Criteria andManageridGreaterThanOrEqualTo(Integer value) {
			addCriterion("a.MANAGERID >=", value, "managerid");
			return this;
		}

		public Criteria andManageridLessThan(Integer value) {
			addCriterion("a.MANAGERID <", value, "managerid");
			return this;
		}

		public Criteria andManageridLessThanOrEqualTo(Integer value) {
			addCriterion("a.MANAGERID <=", value, "managerid");
			return this;
		}

		public Criteria andManageridIn(List values) {
			addCriterion("a.MANAGERID in", values, "managerid");
			return this;
		}

		public Criteria andManageridNotIn(List values) {
			addCriterion("a.MANAGERID not in", values, "managerid");
			return this;
		}

		public Criteria andManageridBetween(Integer value1, Integer value2) {
			addCriterion("a.MANAGERID between", value1, value2, "managerid");
			return this;
		}

		public Criteria andManageridNotBetween(Integer value1, Integer value2) {
			addCriterion("a.MANAGERID not between", value1, value2, "managerid");
			return this;
		}

		public Criteria andOrgmanagerIsNull() {
			addCriterion("a.ORGMANAGER is null");
			return this;
		}

		public Criteria andOrgmanagerIsNotNull() {
			addCriterion("a.ORGMANAGER is not null");
			return this;
		}

		public Criteria andOrgmanagerEqualTo(String value) {
			addCriterion("a.ORGMANAGER =", value, "orgmanager");
			return this;
		}

		public Criteria andOrgmanagerNotEqualTo(String value) {
			addCriterion("a.ORGMANAGER <>", value, "orgmanager");
			return this;
		}

		public Criteria andOrgmanagerGreaterThan(String value) {
			addCriterion("a.ORGMANAGER >", value, "orgmanager");
			return this;
		}

		public Criteria andOrgmanagerGreaterThanOrEqualTo(String value) {
			addCriterion("a.ORGMANAGER >=", value, "orgmanager");
			return this;
		}

		public Criteria andOrgmanagerLessThan(String value) {
			addCriterion("a.ORGMANAGER <", value, "orgmanager");
			return this;
		}

		public Criteria andOrgmanagerLessThanOrEqualTo(String value) {
			addCriterion("a.ORGMANAGER <=", value, "orgmanager");
			return this;
		}

		public Criteria andOrgmanagerLike(String value) {
			addCriterion("a.ORGMANAGER like", value, "orgmanager");
			return this;
		}

		public Criteria andOrgmanagerNotLike(String value) {
			addCriterion("a.ORGMANAGER not like", value, "orgmanager");
			return this;
		}

		public Criteria andOrgmanagerIn(List values) {
			addCriterion("a.ORGMANAGER in", values, "orgmanager");
			return this;
		}

		public Criteria andOrgmanagerNotIn(List values) {
			addCriterion("a.ORGMANAGER not in", values, "orgmanager");
			return this;
		}

		public Criteria andOrgmanagerBetween(String value1, String value2) {
			addCriterion("a.ORGMANAGER between", value1, value2, "orgmanager");
			return this;
		}

		public Criteria andOrgmanagerNotBetween(String value1, String value2) {
			addCriterion("a.ORGMANAGER not between", value1, value2,
					"orgmanager");
			return this;
		}

		public Criteria andOrglevelIsNull() {
			addCriterion("a.ORGLEVEL is null");
			return this;
		}

		public Criteria andOrglevelIsNotNull() {
			addCriterion("a.ORGLEVEL is not null");
			return this;
		}

		public Criteria andOrglevelEqualTo(Integer value) {
			addCriterion("a.ORGLEVEL =", value, "orglevel");
			return this;
		}

		public Criteria andOrglevelNotEqualTo(Integer value) {
			addCriterion("a.ORGLEVEL <>", value, "orglevel");
			return this;
		}

		public Criteria andOrglevelGreaterThan(Integer value) {
			addCriterion("a.ORGLEVEL >", value, "orglevel");
			return this;
		}

		public Criteria andOrglevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("a.ORGLEVEL >=", value, "orglevel");
			return this;
		}

		public Criteria andOrglevelLessThan(Integer value) {
			addCriterion("a.ORGLEVEL <", value, "orglevel");
			return this;
		}

		public Criteria andOrglevelLessThanOrEqualTo(Integer value) {
			addCriterion("a.ORGLEVEL <=", value, "orglevel");
			return this;
		}

		public Criteria andOrglevelIn(List values) {
			addCriterion("a.ORGLEVEL in", values, "orglevel");
			return this;
		}

		public Criteria andOrglevelNotIn(List values) {
			addCriterion("a.ORGLEVEL not in", values, "orglevel");
			return this;
		}

		public Criteria andOrglevelBetween(Integer value1, Integer value2) {
			addCriterion("a.ORGLEVEL between", value1, value2, "orglevel");
			return this;
		}

		public Criteria andOrglevelNotBetween(Integer value1, Integer value2) {
			addCriterion("a.ORGLEVEL not between", value1, value2, "orglevel");
			return this;
		}

		public Criteria andWeburlIsNull() {
			addCriterion("a.WEBURL is null");
			return this;
		}

		public Criteria andWeburlIsNotNull() {
			addCriterion("a.WEBURL is not null");
			return this;
		}

		public Criteria andWeburlEqualTo(String value) {
			addCriterion("a.WEBURL =", value, "weburl");
			return this;
		}

		public Criteria andWeburlNotEqualTo(String value) {
			addCriterion("a.WEBURL <>", value, "weburl");
			return this;
		}

		public Criteria andWeburlGreaterThan(String value) {
			addCriterion("a.WEBURL >", value, "weburl");
			return this;
		}

		public Criteria andWeburlGreaterThanOrEqualTo(String value) {
			addCriterion("a.WEBURL >=", value, "weburl");
			return this;
		}

		public Criteria andWeburlLessThan(String value) {
			addCriterion("a.WEBURL <", value, "weburl");
			return this;
		}

		public Criteria andWeburlLessThanOrEqualTo(String value) {
			addCriterion("a.WEBURL <=", value, "weburl");
			return this;
		}

		public Criteria andWeburlLike(String value) {
			addCriterion("a.WEBURL like", value, "weburl");
			return this;
		}

		public Criteria andWeburlNotLike(String value) {
			addCriterion("a.WEBURL not like", value, "weburl");
			return this;
		}

		public Criteria andWeburlIn(List values) {
			addCriterion("a.WEBURL in", values, "weburl");
			return this;
		}

		public Criteria andWeburlNotIn(List values) {
			addCriterion("a.WEBURL not in", values, "weburl");
			return this;
		}

		public Criteria andWeburlBetween(String value1, String value2) {
			addCriterion("a.WEBURL between", value1, value2, "weburl");
			return this;
		}

		public Criteria andWeburlNotBetween(String value1, String value2) {
			addCriterion("a.WEBURL not between", value1, value2, "weburl");
			return this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("a.CREATETIME is null");
			return this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("a.CREATETIME is not null");
			return this;
		}

		public Criteria andCreatetimeEqualTo(Object value) {
			addCriterion("a.CREATETIME =", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeNotEqualTo(Object value) {
			addCriterion("a.CREATETIME <>", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeGreaterThan(Object value) {
			addCriterion("a.CREATETIME >", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Object value) {
			addCriterion("a.CREATETIME >=", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeLessThan(Object value) {
			addCriterion("a.CREATETIME <", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Object value) {
			addCriterion("a.CREATETIME <=", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeIn(List values) {
			addCriterion("a.CREATETIME in", values, "createtime");
			return this;
		}

		public Criteria andCreatetimeNotIn(List values) {
			addCriterion("a.CREATETIME not in", values, "createtime");
			return this;
		}

		public Criteria andCreatetimeBetween(Object value1, Object value2) {
			addCriterion("a.CREATETIME between", value1, value2, "createtime");
			return this;
		}

		public Criteria andCreatetimeNotBetween(Object value1, Object value2) {
			addCriterion("a.CREATETIME not between", value1, value2,
					"createtime");
			return this;
		}

		public Criteria andStartdateIsNull() {
			addCriterion("a.STARTDATE is null");
			return this;
		}

		public Criteria andStartdateIsNotNull() {
			addCriterion("a.STARTDATE is not null");
			return this;
		}

		public Criteria andStartdateEqualTo(Date value) {
			addCriterion("a.STARTDATE =", value, "startdate");
			return this;
		}

		public Criteria andStartdateNotEqualTo(Date value) {
			addCriterion("a.STARTDATE <>", value, "startdate");
			return this;
		}

		public Criteria andStartdateGreaterThan(Date value) {
			addCriterion("a.STARTDATE >", value, "startdate");
			return this;
		}

		public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
			addCriterion("a.STARTDATE >=", value, "startdate");
			return this;
		}

		public Criteria andStartdateLessThan(Date value) {
			addCriterion("a.STARTDATE <", value, "startdate");
			return this;
		}

		public Criteria andStartdateLessThanOrEqualTo(Date value) {
			addCriterion("a.STARTDATE <=", value, "startdate");
			return this;
		}

		public Criteria andStartdateIn(List values) {
			addCriterion("a.STARTDATE in", values, "startdate");
			return this;
		}

		public Criteria andStartdateNotIn(List values) {
			addCriterion("a.STARTDATE not in", values, "startdate");
			return this;
		}

		public Criteria andStartdateBetween(Date value1, Date value2) {
			addCriterion("a.STARTDATE between", value1, value2, "startdate");
			return this;
		}

		public Criteria andStartdateNotBetween(Date value1, Date value2) {
			addCriterion("a.STARTDATE not between", value1, value2, "startdate");
			return this;
		}

		public Criteria andEnddateIsNull() {
			addCriterion("a.ENDDATE is null");
			return this;
		}

		public Criteria andEnddateIsNotNull() {
			addCriterion("a.ENDDATE is not null");
			return this;
		}

		public Criteria andEnddateEqualTo(Date value) {
			addCriterion("a.ENDDATE =", value, "enddate");
			return this;
		}

		public Criteria andEnddateNotEqualTo(Date value) {
			addCriterion("a.ENDDATE <>", value, "enddate");
			return this;
		}

		public Criteria andEnddateGreaterThan(Date value) {
			addCriterion("a.ENDDATE >", value, "enddate");
			return this;
		}

		public Criteria andEnddateGreaterThanOrEqualTo(Date value) {
			addCriterion("a.ENDDATE >=", value, "enddate");
			return this;
		}

		public Criteria andEnddateLessThan(Date value) {
			addCriterion("a.ENDDATE <", value, "enddate");
			return this;
		}

		public Criteria andEnddateLessThanOrEqualTo(Date value) {
			addCriterion("a.ENDDATE <=", value, "enddate");
			return this;
		}

		public Criteria andEnddateIn(List values) {
			addCriterion("a.ENDDATE in", values, "enddate");
			return this;
		}

		public Criteria andEnddateNotIn(List values) {
			addCriterion("a.ENDDATE not in", values, "enddate");
			return this;
		}

		public Criteria andEnddateBetween(Date value1, Date value2) {
			addCriterion("a.ENDDATE between", value1, value2, "enddate");
			return this;
		}

		public Criteria andEnddateNotBetween(Date value1, Date value2) {
			addCriterion("a.ENDDATE not between", value1, value2, "enddate");
			return this;
		}

		public Criteria andLinkmanIsNull() {
			addCriterion("a.LINKMAN is null");
			return this;
		}

		public Criteria andLinkmanIsNotNull() {
			addCriterion("a.LINKMAN is not null");
			return this;
		}

		public Criteria andLinkmanEqualTo(String value) {
			addCriterion("a.LINKMAN =", value, "linkman");
			return this;
		}

		public Criteria andLinkmanNotEqualTo(String value) {
			addCriterion("a.LINKMAN <>", value, "linkman");
			return this;
		}

		public Criteria andLinkmanGreaterThan(String value) {
			addCriterion("a.LINKMAN >", value, "linkman");
			return this;
		}

		public Criteria andLinkmanGreaterThanOrEqualTo(String value) {
			addCriterion("a.LINKMAN >=", value, "linkman");
			return this;
		}

		public Criteria andLinkmanLessThan(String value) {
			addCriterion("a.LINKMAN <", value, "linkman");
			return this;
		}

		public Criteria andLinkmanLessThanOrEqualTo(String value) {
			addCriterion("a.LINKMAN <=", value, "linkman");
			return this;
		}

		public Criteria andLinkmanLike(String value) {
			addCriterion("a.LINKMAN like", value, "linkman");
			return this;
		}

		public Criteria andLinkmanNotLike(String value) {
			addCriterion("a.LINKMAN not like", value, "linkman");
			return this;
		}

		public Criteria andLinkmanIn(List values) {
			addCriterion("a.LINKMAN in", values, "linkman");
			return this;
		}

		public Criteria andLinkmanNotIn(List values) {
			addCriterion("a.LINKMAN not in", values, "linkman");
			return this;
		}

		public Criteria andLinkmanBetween(String value1, String value2) {
			addCriterion("a.LINKMAN between", value1, value2, "linkman");
			return this;
		}

		public Criteria andLinkmanNotBetween(String value1, String value2) {
			addCriterion("a.LINKMAN not between", value1, value2, "linkman");
			return this;
		}

		public Criteria andLinktelIsNull() {
			addCriterion("a.LINKTEL is null");
			return this;
		}

		public Criteria andLinktelIsNotNull() {
			addCriterion("a.LINKTEL is not null");
			return this;
		}

		public Criteria andLinktelEqualTo(String value) {
			addCriterion("a.LINKTEL =", value, "linktel");
			return this;
		}

		public Criteria andLinktelNotEqualTo(String value) {
			addCriterion("a.LINKTEL <>", value, "linktel");
			return this;
		}

		public Criteria andLinktelGreaterThan(String value) {
			addCriterion("a.LINKTEL >", value, "linktel");
			return this;
		}

		public Criteria andLinktelGreaterThanOrEqualTo(String value) {
			addCriterion("a.LINKTEL >=", value, "linktel");
			return this;
		}

		public Criteria andLinktelLessThan(String value) {
			addCriterion("a.LINKTEL <", value, "linktel");
			return this;
		}

		public Criteria andLinktelLessThanOrEqualTo(String value) {
			addCriterion("a.LINKTEL <=", value, "linktel");
			return this;
		}

		public Criteria andLinktelLike(String value) {
			addCriterion("a.LINKTEL like", value, "linktel");
			return this;
		}

		public Criteria andLinktelNotLike(String value) {
			addCriterion("a.LINKTEL not like", value, "linktel");
			return this;
		}

		public Criteria andLinktelIn(List values) {
			addCriterion("a.LINKTEL in", values, "linktel");
			return this;
		}

		public Criteria andLinktelNotIn(List values) {
			addCriterion("a.LINKTEL not in", values, "linktel");
			return this;
		}

		public Criteria andLinktelBetween(String value1, String value2) {
			addCriterion("a.LINKTEL between", value1, value2, "linktel");
			return this;
		}

		public Criteria andLinktelNotBetween(String value1, String value2) {
			addCriterion("a.LINKTEL not between", value1, value2, "linktel");
			return this;
		}

		public Criteria andOrgaddrIsNull() {
			addCriterion("a.ORGADDR is null");
			return this;
		}

		public Criteria andOrgaddrIsNotNull() {
			addCriterion("a.ORGADDR is not null");
			return this;
		}

		public Criteria andOrgaddrEqualTo(String value) {
			addCriterion("a.ORGADDR =", value, "orgaddr");
			return this;
		}

		public Criteria andOrgaddrNotEqualTo(String value) {
			addCriterion("a.ORGADDR <>", value, "orgaddr");
			return this;
		}

		public Criteria andOrgaddrGreaterThan(String value) {
			addCriterion("a.ORGADDR >", value, "orgaddr");
			return this;
		}

		public Criteria andOrgaddrGreaterThanOrEqualTo(String value) {
			addCriterion("a.ORGADDR >=", value, "orgaddr");
			return this;
		}

		public Criteria andOrgaddrLessThan(String value) {
			addCriterion("a.ORGADDR <", value, "orgaddr");
			return this;
		}

		public Criteria andOrgaddrLessThanOrEqualTo(String value) {
			addCriterion("a.ORGADDR <=", value, "orgaddr");
			return this;
		}

		public Criteria andOrgaddrLike(String value) {
			addCriterion("a.ORGADDR like", value, "orgaddr");
			return this;
		}

		public Criteria andOrgaddrNotLike(String value) {
			addCriterion("a.ORGADDR not like", value, "orgaddr");
			return this;
		}

		public Criteria andOrgaddrIn(List values) {
			addCriterion("a.ORGADDR in", values, "orgaddr");
			return this;
		}

		public Criteria andOrgaddrNotIn(List values) {
			addCriterion("a.ORGADDR not in", values, "orgaddr");
			return this;
		}

		public Criteria andOrgaddrBetween(String value1, String value2) {
			addCriterion("a.ORGADDR between", value1, value2, "orgaddr");
			return this;
		}

		public Criteria andOrgaddrNotBetween(String value1, String value2) {
			addCriterion("a.ORGADDR not between", value1, value2, "orgaddr");
			return this;
		}

		public Criteria andZipcodeIsNull() {
			addCriterion("a.ZIPCODE is null");
			return this;
		}

		public Criteria andZipcodeIsNotNull() {
			addCriterion("a.ZIPCODE is not null");
			return this;
		}

		public Criteria andZipcodeEqualTo(String value) {
			addCriterion("a.ZIPCODE =", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeNotEqualTo(String value) {
			addCriterion("a.ZIPCODE <>", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeGreaterThan(String value) {
			addCriterion("a.ZIPCODE >", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeGreaterThanOrEqualTo(String value) {
			addCriterion("a.ZIPCODE >=", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeLessThan(String value) {
			addCriterion("a.ZIPCODE <", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeLessThanOrEqualTo(String value) {
			addCriterion("a.ZIPCODE <=", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeLike(String value) {
			addCriterion("a.ZIPCODE like", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeNotLike(String value) {
			addCriterion("a.ZIPCODE not like", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeIn(List values) {
			addCriterion("a.ZIPCODE in", values, "zipcode");
			return this;
		}

		public Criteria andZipcodeNotIn(List values) {
			addCriterion("a.ZIPCODE not in", values, "zipcode");
			return this;
		}

		public Criteria andZipcodeBetween(String value1, String value2) {
			addCriterion("a.ZIPCODE between", value1, value2, "zipcode");
			return this;
		}

		public Criteria andZipcodeNotBetween(String value1, String value2) {
			addCriterion("a.ZIPCODE not between", value1, value2, "zipcode");
			return this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("a.EMAIL is null");
			return this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("a.EMAIL is not null");
			return this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("a.EMAIL =", value, "email");
			return this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("a.EMAIL <>", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("a.EMAIL >", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("a.EMAIL >=", value, "email");
			return this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("a.EMAIL <", value, "email");
			return this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("a.EMAIL <=", value, "email");
			return this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("a.EMAIL like", value, "email");
			return this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("a.EMAIL not like", value, "email");
			return this;
		}

		public Criteria andEmailIn(List values) {
			addCriterion("a.EMAIL in", values, "email");
			return this;
		}

		public Criteria andEmailNotIn(List values) {
			addCriterion("a.EMAIL not in", values, "email");
			return this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("a.EMAIL between", value1, value2, "email");
			return this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("a.EMAIL not between", value1, value2, "email");
			return this;
		}

		public Criteria andReserve1IsNull() {
			addCriterion("a.RESERVE1 is null");
			return this;
		}

		public Criteria andReserve1IsNotNull() {
			addCriterion("a.RESERVE1 is not null");
			return this;
		}

		public Criteria andReserve1EqualTo(String value) {
			addCriterion("a.RESERVE1 =", value, "reserve1");
			return this;
		}

		public Criteria andReserve1NotEqualTo(String value) {
			addCriterion("a.RESERVE1 <>", value, "reserve1");
			return this;
		}

		public Criteria andReserve1GreaterThan(String value) {
			addCriterion("a.RESERVE1 >", value, "reserve1");
			return this;
		}

		public Criteria andReserve1GreaterThanOrEqualTo(String value) {
			addCriterion("a.RESERVE1 >=", value, "reserve1");
			return this;
		}

		public Criteria andReserve1LessThan(String value) {
			addCriterion("a.RESERVE1 <", value, "reserve1");
			return this;
		}

		public Criteria andReserve1LessThanOrEqualTo(String value) {
			addCriterion("a.RESERVE1 <=", value, "reserve1");
			return this;
		}

		public Criteria andReserve1Like(String value) {
			addCriterion("a.RESERVE1 like", value, "reserve1");
			return this;
		}

		public Criteria andReserve1NotLike(String value) {
			addCriterion("a.RESERVE1 not like", value, "reserve1");
			return this;
		}

		public Criteria andReserve1In(List values) {
			addCriterion("a.RESERVE1 in", values, "reserve1");
			return this;
		}

		public Criteria andReserve1NotIn(List values) {
			addCriterion("a.RESERVE1 not in", values, "reserve1");
			return this;
		}

		public Criteria andReserve1Between(String value1, String value2) {
			addCriterion("a.RESERVE1 between", value1, value2, "reserve1");
			return this;
		}

		public Criteria andReserve1NotBetween(String value1, String value2) {
			addCriterion("a.RESERVE1 not between", value1, value2, "reserve1");
			return this;
		}

		public Criteria andReserve2IsNull() {
			addCriterion("a.RESERVE2 is null");
			return this;
		}

		public Criteria andReserve2IsNotNull() {
			addCriterion("a.RESERVE2 is not null");
			return this;
		}

		public Criteria andReserve2EqualTo(String value) {
			addCriterion("a.RESERVE2 =", value, "reserve2");
			return this;
		}

		public Criteria andReserve2NotEqualTo(String value) {
			addCriterion("a.RESERVE2 <>", value, "reserve2");
			return this;
		}

		public Criteria andReserve2GreaterThan(String value) {
			addCriterion("a.RESERVE2 >", value, "reserve2");
			return this;
		}

		public Criteria andReserve2GreaterThanOrEqualTo(String value) {
			addCriterion("a.RESERVE2 >=", value, "reserve2");
			return this;
		}

		public Criteria andReserve2LessThan(String value) {
			addCriterion("a.RESERVE2 <", value, "reserve2");
			return this;
		}

		public Criteria andReserve2LessThanOrEqualTo(String value) {
			addCriterion("a.RESERVE2 <=", value, "reserve2");
			return this;
		}

		public Criteria andReserve2Like(String value) {
			addCriterion("a.RESERVE2 like", value, "reserve2");
			return this;
		}

		public Criteria andReserve2NotLike(String value) {
			addCriterion("a.RESERVE2 not like", value, "reserve2");
			return this;
		}

		public Criteria andReserve2In(List values) {
			addCriterion("a.RESERVE2 in", values, "reserve2");
			return this;
		}

		public Criteria andReserve2NotIn(List values) {
			addCriterion("a.RESERVE2 not in", values, "reserve2");
			return this;
		}

		public Criteria andReserve2Between(String value1, String value2) {
			addCriterion("a.RESERVE2 between", value1, value2, "reserve2");
			return this;
		}

		public Criteria andReserve2NotBetween(String value1, String value2) {
			addCriterion("a.RESERVE2 not between", value1, value2, "reserve2");
			return this;
		}

		public Criteria andReserve3IsNull() {
			addCriterion("a.RESERVE3 is null");
			return this;
		}

		public Criteria andReserve3IsNotNull() {
			addCriterion("a.RESERVE3 is not null");
			return this;
		}

		public Criteria andReserve3EqualTo(String value) {
			addCriterion("a.RESERVE3 =", value, "reserve3");
			return this;
		}

		public Criteria andReserve3NotEqualTo(String value) {
			addCriterion("a.RESERVE3 <>", value, "reserve3");
			return this;
		}

		public Criteria andReserve3GreaterThan(String value) {
			addCriterion("a.RESERVE3 >", value, "reserve3");
			return this;
		}

		public Criteria andReserve3GreaterThanOrEqualTo(String value) {
			addCriterion("a.RESERVE3 >=", value, "reserve3");
			return this;
		}

		public Criteria andReserve3LessThan(String value) {
			addCriterion("a.RESERVE3 <", value, "reserve3");
			return this;
		}

		public Criteria andReserve3LessThanOrEqualTo(String value) {
			addCriterion("a.RESERVE3 <=", value, "reserve3");
			return this;
		}

		public Criteria andReserve3Like(String value) {
			addCriterion("a.RESERVE3 like", value, "reserve3");
			return this;
		}

		public Criteria andReserve3NotLike(String value) {
			addCriterion("a.RESERVE3 not like", value, "reserve3");
			return this;
		}

		public Criteria andReserve3In(List values) {
			addCriterion("a.RESERVE3 in", values, "reserve3");
			return this;
		}

		public Criteria andReserve3NotIn(List values) {
			addCriterion("a.RESERVE3 not in", values, "reserve3");
			return this;
		}

		public Criteria andReserve3Between(String value1, String value2) {
			addCriterion("a.RESERVE3 between", value1, value2, "reserve3");
			return this;
		}

		public Criteria andReserve3NotBetween(String value1, String value2) {
			addCriterion("a.RESERVE3 not between", value1, value2, "reserve3");
			return this;
		}

		public Criteria andReserve4IsNull() {
			addCriterion("a.RESERVE4 is null");
			return this;
		}

		public Criteria andReserve4IsNotNull() {
			addCriterion("a.RESERVE4 is not null");
			return this;
		}

		public Criteria andReserve4EqualTo(String value) {
			addCriterion("a.RESERVE4 =", value, "reserve4");
			return this;
		}

		public Criteria andReserve4NotEqualTo(String value) {
			addCriterion("a.RESERVE4 <>", value, "reserve4");
			return this;
		}

		public Criteria andReserve4GreaterThan(String value) {
			addCriterion("a.RESERVE4 >", value, "reserve4");
			return this;
		}

		public Criteria andReserve4GreaterThanOrEqualTo(String value) {
			addCriterion("a.RESERVE4 >=", value, "reserve4");
			return this;
		}

		public Criteria andReserve4LessThan(String value) {
			addCriterion("a.RESERVE4 <", value, "reserve4");
			return this;
		}

		public Criteria andReserve4LessThanOrEqualTo(String value) {
			addCriterion("a.RESERVE4 <=", value, "reserve4");
			return this;
		}

		public Criteria andReserve4Like(String value) {
			addCriterion("a.RESERVE4 like", value, "reserve4");
			return this;
		}

		public Criteria andReserve4NotLike(String value) {
			addCriterion("a.RESERVE4 not like", value, "reserve4");
			return this;
		}

		public Criteria andReserve4In(List values) {
			addCriterion("a.RESERVE4 in", values, "reserve4");
			return this;
		}

		public Criteria andReserve4NotIn(List values) {
			addCriterion("a.RESERVE4 not in", values, "reserve4");
			return this;
		}

		public Criteria andReserve4Between(String value1, String value2) {
			addCriterion("a.RESERVE4 between", value1, value2, "reserve4");
			return this;
		}

		public Criteria andReserve4NotBetween(String value1, String value2) {
			addCriterion("a.RESERVE4 not between", value1, value2, "reserve4");
			return this;
		}

		public Criteria andReserve5IsNull() {
			addCriterion("a.RESERVE5 is null");
			return this;
		}

		public Criteria andReserve5IsNotNull() {
			addCriterion("a.RESERVE5 is not null");
			return this;
		}

		public Criteria andReserve5EqualTo(String value) {
			addCriterion("a.RESERVE5 =", value, "reserve5");
			return this;
		}

		public Criteria andReserve5NotEqualTo(String value) {
			addCriterion("a.RESERVE5 <>", value, "reserve5");
			return this;
		}

		public Criteria andReserve5GreaterThan(String value) {
			addCriterion("a.RESERVE5 >", value, "reserve5");
			return this;
		}

		public Criteria andReserve5GreaterThanOrEqualTo(String value) {
			addCriterion("a.RESERVE5 >=", value, "reserve5");
			return this;
		}

		public Criteria andReserve5LessThan(String value) {
			addCriterion("a.RESERVE5 <", value, "reserve5");
			return this;
		}

		public Criteria andReserve5LessThanOrEqualTo(String value) {
			addCriterion("a.RESERVE5 <=", value, "reserve5");
			return this;
		}

		public Criteria andReserve5Like(String value) {
			addCriterion("a.RESERVE5 like", value, "reserve5");
			return this;
		}

		public Criteria andReserve5NotLike(String value) {
			addCriterion("a.RESERVE5 not like", value, "reserve5");
			return this;
		}

		public Criteria andReserve5In(List values) {
			addCriterion("a.RESERVE5 in", values, "reserve5");
			return this;
		}

		public Criteria andReserve5NotIn(List values) {
			addCriterion("a.RESERVE5 not in", values, "reserve5");
			return this;
		}

		public Criteria andReserve5Between(String value1, String value2) {
			addCriterion("a.RESERVE5 between", value1, value2, "reserve5");
			return this;
		}

		public Criteria andReserve5NotBetween(String value1, String value2) {
			addCriterion("a.RESERVE5 not between", value1, value2, "reserve5");
			return this;
		}

		public Criteria andReserve6IsNull() {
			addCriterion("a.RESERVE6 is null");
			return this;
		}

		public Criteria andReserve6IsNotNull() {
			addCriterion("a.RESERVE6 is not null");
			return this;
		}

		public Criteria andReserve6EqualTo(String value) {
			addCriterion("a.RESERVE6 =", value, "reserve6");
			return this;
		}

		public Criteria andReserve6NotEqualTo(String value) {
			addCriterion("a.RESERVE6 <>", value, "reserve6");
			return this;
		}

		public Criteria andReserve6GreaterThan(String value) {
			addCriterion("a.RESERVE6 >", value, "reserve6");
			return this;
		}

		public Criteria andReserve6GreaterThanOrEqualTo(String value) {
			addCriterion("a.RESERVE6 >=", value, "reserve6");
			return this;
		}

		public Criteria andReserve6LessThan(String value) {
			addCriterion("a.RESERVE6 <", value, "reserve6");
			return this;
		}

		public Criteria andReserve6LessThanOrEqualTo(String value) {
			addCriterion("a.RESERVE6 <=", value, "reserve6");
			return this;
		}

		public Criteria andReserve6Like(String value) {
			addCriterion("a.RESERVE6 like", value, "reserve6");
			return this;
		}

		public Criteria andReserve6NotLike(String value) {
			addCriterion("a.RESERVE6 not like", value, "reserve6");
			return this;
		}

		public Criteria andReserve6In(List values) {
			addCriterion("a.RESERVE6 in", values, "reserve6");
			return this;
		}

		public Criteria andReserve6NotIn(List values) {
			addCriterion("a.RESERVE6 not in", values, "reserve6");
			return this;
		}

		public Criteria andReserve6Between(String value1, String value2) {
			addCriterion("a.RESERVE6 between", value1, value2, "reserve6");
			return this;
		}

		public Criteria andReserve6NotBetween(String value1, String value2) {
			addCriterion("a.RESERVE6 not between", value1, value2, "reserve6");
			return this;
		}

		public Criteria andReserve7IsNull() {
			addCriterion("a.RESERVE7 is null");
			return this;
		}

		public Criteria andReserve7IsNotNull() {
			addCriterion("a.RESERVE7 is not null");
			return this;
		}

		public Criteria andReserve7EqualTo(String value) {
			addCriterion("a.RESERVE7 =", value, "reserve7");
			return this;
		}

		public Criteria andReserve7NotEqualTo(String value) {
			addCriterion("a.RESERVE7 <>", value, "reserve7");
			return this;
		}

		public Criteria andReserve7GreaterThan(String value) {
			addCriterion("a.RESERVE7 >", value, "reserve7");
			return this;
		}

		public Criteria andReserve7GreaterThanOrEqualTo(String value) {
			addCriterion("a.RESERVE7 >=", value, "reserve7");
			return this;
		}

		public Criteria andReserve7LessThan(String value) {
			addCriterion("a.RESERVE7 <", value, "reserve7");
			return this;
		}

		public Criteria andReserve7LessThanOrEqualTo(String value) {
			addCriterion("a.RESERVE7 <=", value, "reserve7");
			return this;
		}

		public Criteria andReserve7Like(String value) {
			addCriterion("a.RESERVE7 like", value, "reserve7");
			return this;
		}

		public Criteria andReserve7NotLike(String value) {
			addCriterion("a.RESERVE7 not like", value, "reserve7");
			return this;
		}

		public Criteria andReserve7In(List values) {
			addCriterion("a.RESERVE7 in", values, "reserve7");
			return this;
		}

		public Criteria andReserve7NotIn(List values) {
			addCriterion("a.RESERVE7 not in", values, "reserve7");
			return this;
		}

		public Criteria andReserve7Between(String value1, String value2) {
			addCriterion("a.RESERVE7 between", value1, value2, "reserve7");
			return this;
		}

		public Criteria andReserve7NotBetween(String value1, String value2) {
			addCriterion("a.RESERVE7 not between", value1, value2, "reserve7");
			return this;
		}

		public Criteria andReserve8IsNull() {
			addCriterion("a.RESERVE8 is null");
			return this;
		}

		public Criteria andReserve8IsNotNull() {
			addCriterion("a.RESERVE8 is not null");
			return this;
		}

		public Criteria andReserve8EqualTo(String value) {
			addCriterion("a.RESERVE8 =", value, "reserve8");
			return this;
		}

		public Criteria andReserve8NotEqualTo(String value) {
			addCriterion("a.RESERVE8 <>", value, "reserve8");
			return this;
		}

		public Criteria andReserve8GreaterThan(String value) {
			addCriterion("a.RESERVE8 >", value, "reserve8");
			return this;
		}

		public Criteria andReserve8GreaterThanOrEqualTo(String value) {
			addCriterion("a.RESERVE8 >=", value, "reserve8");
			return this;
		}

		public Criteria andReserve8LessThan(String value) {
			addCriterion("a.RESERVE8 <", value, "reserve8");
			return this;
		}

		public Criteria andReserve8LessThanOrEqualTo(String value) {
			addCriterion("a.RESERVE8 <=", value, "reserve8");
			return this;
		}

		public Criteria andReserve8Like(String value) {
			addCriterion("a.RESERVE8 like", value, "reserve8");
			return this;
		}

		public Criteria andReserve8NotLike(String value) {
			addCriterion("a.RESERVE8 not like", value, "reserve8");
			return this;
		}

		public Criteria andReserve8In(List values) {
			addCriterion("a.RESERVE8 in", values, "reserve8");
			return this;
		}

		public Criteria andReserve8NotIn(List values) {
			addCriterion("a.RESERVE8 not in", values, "reserve8");
			return this;
		}

		public Criteria andReserve8Between(String value1, String value2) {
			addCriterion("a.RESERVE8 between", value1, value2, "reserve8");
			return this;
		}

		public Criteria andReserve8NotBetween(String value1, String value2) {
			addCriterion("a.RESERVE8 not between", value1, value2, "reserve8");
			return this;
		}

		public Criteria andReserve9IsNull() {
			addCriterion("a.RESERVE9 is null");
			return this;
		}

		public Criteria andReserve9IsNotNull() {
			addCriterion("a.RESERVE9 is not null");
			return this;
		}

		public Criteria andReserve9EqualTo(String value) {
			addCriterion("a.RESERVE9 =", value, "reserve9");
			return this;
		}

		public Criteria andReserve9NotEqualTo(String value) {
			addCriterion("a.RESERVE9 <>", value, "reserve9");
			return this;
		}

		public Criteria andReserve9GreaterThan(String value) {
			addCriterion("a.RESERVE9 >", value, "reserve9");
			return this;
		}

		public Criteria andReserve9GreaterThanOrEqualTo(String value) {
			addCriterion("a.RESERVE9 >=", value, "reserve9");
			return this;
		}

		public Criteria andReserve9LessThan(String value) {
			addCriterion("a.RESERVE9 <", value, "reserve9");
			return this;
		}

		public Criteria andReserve9LessThanOrEqualTo(String value) {
			addCriterion("a.RESERVE9 <=", value, "reserve9");
			return this;
		}

		public Criteria andReserve9Like(String value) {
			addCriterion("a.RESERVE9 like", value, "reserve9");
			return this;
		}

		public Criteria andReserve9NotLike(String value) {
			addCriterion("a.RESERVE9 not like", value, "reserve9");
			return this;
		}

		public Criteria andReserve9In(List values) {
			addCriterion("a.RESERVE9 in", values, "reserve9");
			return this;
		}

		public Criteria andReserve9NotIn(List values) {
			addCriterion("a.RESERVE9 not in", values, "reserve9");
			return this;
		}

		public Criteria andReserve9Between(String value1, String value2) {
			addCriterion("a.RESERVE9 between", value1, value2, "reserve9");
			return this;
		}

		public Criteria andReserve9NotBetween(String value1, String value2) {
			addCriterion("a.RESERVE9 not between", value1, value2, "reserve9");
			return this;
		}
	}
}