package com.gotop.euipApply.dao.impl;

import com.gotop.euipApply.dao.ITApplyEuipDAO;
import com.gotop.euipApply.model.TApplyEuip;
import com.gotop.euipApply.model.TApplyEuipExample;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import org.apache.log4j.Logger;

public class TApplyEuipDAO extends SqlMapClientDao implements ITApplyEuipDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TApplyEuipDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_APPLY_EUIP
     *
     * @abatorgenerated 
     */
    public TApplyEuipDAO() {
        super();
    }

    /**
     * 新增
     */
	@Override
	public void insertEuipInfo(TApplyEuip euip) throws Exception {
	insert("T_APPLY_EUIP_SqlMap.insert_euip_apply_info", euip);
		
	}

	/**
	 * 查询
	 */
	@Override
	public TApplyEuip queryApplyEuip(TApplyEuip euip) throws Exception {
		return (TApplyEuip) queryForObject("T_APPLY_EUIP_SqlMap.query_euip_apply_info",euip);
	}

	/**
	 * 修改
	 */
	@Override
	public void updateApplyEuip(TApplyEuip euip) throws Exception {
	update("T_APPLY_EUIP_SqlMap.update_euip_apply_info", euip);
	}

    
}