package test.gotop.crm.demo.model.celltest;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class AcOperatorExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(AcOperatorExample.class);;

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /**
     * @abatorgenerated */
    public AcOperatorExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * @abatorgenerated */
    protected AcOperatorExample(AcOperatorExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /**
     * @abatorgenerated */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * @abatorgenerated */
    /**
     * @abatorgenerated */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * @abatorgenerated */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * @abatorgenerated */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /**
     * @abatorgenerated */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /**
     * @abatorgenerated */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /**
     * @abatorgenerated */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table BKLS.AC_OPERATOR
     *
     * @abatorgenerated Thu Nov 17 15:57:59 CST 2011
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andOperatoridIsNull() {
            addCriterion("OPERATORID is null");
            return this;
        }

        public Criteria andOperatoridIsNotNull() {
            addCriterion("OPERATORID is not null");
            return this;
        }

        public Criteria andOperatoridEqualTo(Integer value) {
            addCriterion("OPERATORID =", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotEqualTo(Integer value) {
            addCriterion("OPERATORID <>", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThan(Integer value) {
            addCriterion("OPERATORID >", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridGreaterThanOrEqualTo(Integer value) {
            addCriterion("OPERATORID >=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThan(Integer value) {
            addCriterion("OPERATORID <", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridLessThanOrEqualTo(Integer value) {
            addCriterion("OPERATORID <=", value, "operatorid");
            return this;
        }

        public Criteria andOperatoridIn(List values) {
            addCriterion("OPERATORID in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotIn(List values) {
            addCriterion("OPERATORID not in", values, "operatorid");
            return this;
        }

        public Criteria andOperatoridBetween(Integer value1, Integer value2) {
            addCriterion("OPERATORID between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andOperatoridNotBetween(Integer value1, Integer value2) {
            addCriterion("OPERATORID not between", value1, value2, "operatorid");
            return this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("USERID =", value, "userid");
            return this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("USERID <>", value, "userid");
            return this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("USERID >", value, "userid");
            return this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "userid");
            return this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("USERID <", value, "userid");
            return this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "userid");
            return this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("USERID like", value, "userid");
            return this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("USERID not like", value, "userid");
            return this;
        }

        public Criteria andUseridIn(List values) {
            addCriterion("USERID in", values, "userid");
            return this;
        }

        public Criteria andUseridNotIn(List values) {
            addCriterion("USERID not in", values, "userid");
            return this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("PASSWORD is null");
            return this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("PASSWORD is not null");
            return this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("PASSWORD =", value, "password");
            return this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "password");
            return this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("PASSWORD <", value, "password");
            return this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "password");
            return this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("PASSWORD like", value, "password");
            return this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("PASSWORD not like", value, "password");
            return this;
        }

        public Criteria andPasswordIn(List values) {
            addCriterion("PASSWORD in", values, "password");
            return this;
        }

        public Criteria andPasswordNotIn(List values) {
            addCriterion("PASSWORD not in", values, "password");
            return this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "password");
            return this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "password");
            return this;
        }

        public Criteria andInvaldateIsNull() {
            addCriterion("INVALDATE is null");
            return this;
        }

        public Criteria andInvaldateIsNotNull() {
            addCriterion("INVALDATE is not null");
            return this;
        }

        public Criteria andInvaldateEqualTo(Date value) {
            addCriterion("INVALDATE =", value, "invaldate");
            return this;
        }

        public Criteria andInvaldateNotEqualTo(Date value) {
            addCriterion("INVALDATE <>", value, "invaldate");
            return this;
        }

        public Criteria andInvaldateGreaterThan(Date value) {
            addCriterion("INVALDATE >", value, "invaldate");
            return this;
        }

        public Criteria andInvaldateGreaterThanOrEqualTo(Date value) {
            addCriterion("INVALDATE >=", value, "invaldate");
            return this;
        }

        public Criteria andInvaldateLessThan(Date value) {
            addCriterion("INVALDATE <", value, "invaldate");
            return this;
        }

        public Criteria andInvaldateLessThanOrEqualTo(Date value) {
            addCriterion("INVALDATE <=", value, "invaldate");
            return this;
        }

        public Criteria andInvaldateIn(List values) {
            addCriterion("INVALDATE in", values, "invaldate");
            return this;
        }

        public Criteria andInvaldateNotIn(List values) {
            addCriterion("INVALDATE not in", values, "invaldate");
            return this;
        }

        public Criteria andInvaldateBetween(Date value1, Date value2) {
            addCriterion("INVALDATE between", value1, value2, "invaldate");
            return this;
        }

        public Criteria andInvaldateNotBetween(Date value1, Date value2) {
            addCriterion("INVALDATE not between", value1, value2, "invaldate");
            return this;
        }

        public Criteria andOperatornameIsNull() {
            addCriterion("OPERATORNAME is null");
            return this;
        }

        public Criteria andOperatornameIsNotNull() {
            addCriterion("OPERATORNAME is not null");
            return this;
        }

        public Criteria andOperatornameEqualTo(String value) {
            addCriterion("OPERATORNAME =", value, "operatorname");
            return this;
        }

        public Criteria andOperatornameNotEqualTo(String value) {
            addCriterion("OPERATORNAME <>", value, "operatorname");
            return this;
        }

        public Criteria andOperatornameGreaterThan(String value) {
            addCriterion("OPERATORNAME >", value, "operatorname");
            return this;
        }

        public Criteria andOperatornameGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATORNAME >=", value, "operatorname");
            return this;
        }

        public Criteria andOperatornameLessThan(String value) {
            addCriterion("OPERATORNAME <", value, "operatorname");
            return this;
        }

        public Criteria andOperatornameLessThanOrEqualTo(String value) {
            addCriterion("OPERATORNAME <=", value, "operatorname");
            return this;
        }

        public Criteria andOperatornameLike(String value) {
            addCriterion("OPERATORNAME like", value, "operatorname");
            return this;
        }

        public Criteria andOperatornameNotLike(String value) {
            addCriterion("OPERATORNAME not like", value, "operatorname");
            return this;
        }

        public Criteria andOperatornameIn(List values) {
            addCriterion("OPERATORNAME in", values, "operatorname");
            return this;
        }

        public Criteria andOperatornameNotIn(List values) {
            addCriterion("OPERATORNAME not in", values, "operatorname");
            return this;
        }

        public Criteria andOperatornameBetween(String value1, String value2) {
            addCriterion("OPERATORNAME between", value1, value2, "operatorname");
            return this;
        }

        public Criteria andOperatornameNotBetween(String value1, String value2) {
            addCriterion("OPERATORNAME not between", value1, value2, "operatorname");
            return this;
        }

        public Criteria andAuthmodeIsNull() {
            addCriterion("AUTHMODE is null");
            return this;
        }

        public Criteria andAuthmodeIsNotNull() {
            addCriterion("AUTHMODE is not null");
            return this;
        }

        public Criteria andAuthmodeEqualTo(String value) {
            addCriterion("AUTHMODE =", value, "authmode");
            return this;
        }

        public Criteria andAuthmodeNotEqualTo(String value) {
            addCriterion("AUTHMODE <>", value, "authmode");
            return this;
        }

        public Criteria andAuthmodeGreaterThan(String value) {
            addCriterion("AUTHMODE >", value, "authmode");
            return this;
        }

        public Criteria andAuthmodeGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHMODE >=", value, "authmode");
            return this;
        }

        public Criteria andAuthmodeLessThan(String value) {
            addCriterion("AUTHMODE <", value, "authmode");
            return this;
        }

        public Criteria andAuthmodeLessThanOrEqualTo(String value) {
            addCriterion("AUTHMODE <=", value, "authmode");
            return this;
        }

        public Criteria andAuthmodeLike(String value) {
            addCriterion("AUTHMODE like", value, "authmode");
            return this;
        }

        public Criteria andAuthmodeNotLike(String value) {
            addCriterion("AUTHMODE not like", value, "authmode");
            return this;
        }

        public Criteria andAuthmodeIn(List values) {
            addCriterion("AUTHMODE in", values, "authmode");
            return this;
        }

        public Criteria andAuthmodeNotIn(List values) {
            addCriterion("AUTHMODE not in", values, "authmode");
            return this;
        }

        public Criteria andAuthmodeBetween(String value1, String value2) {
            addCriterion("AUTHMODE between", value1, value2, "authmode");
            return this;
        }

        public Criteria andAuthmodeNotBetween(String value1, String value2) {
            addCriterion("AUTHMODE not between", value1, value2, "authmode");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("STATUS in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("STATUS not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return this;
        }

        public Criteria andUnlocktimeIsNull() {
            addCriterion("UNLOCKTIME is null");
            return this;
        }

        public Criteria andUnlocktimeIsNotNull() {
            addCriterion("UNLOCKTIME is not null");
            return this;
        }

        public Criteria andUnlocktimeEqualTo(Object value) {
            addCriterion("UNLOCKTIME =", value, "unlocktime");
            return this;
        }

        public Criteria andUnlocktimeNotEqualTo(Object value) {
            addCriterion("UNLOCKTIME <>", value, "unlocktime");
            return this;
        }

        public Criteria andUnlocktimeGreaterThan(Object value) {
            addCriterion("UNLOCKTIME >", value, "unlocktime");
            return this;
        }

        public Criteria andUnlocktimeGreaterThanOrEqualTo(Object value) {
            addCriterion("UNLOCKTIME >=", value, "unlocktime");
            return this;
        }

        public Criteria andUnlocktimeLessThan(Object value) {
            addCriterion("UNLOCKTIME <", value, "unlocktime");
            return this;
        }

        public Criteria andUnlocktimeLessThanOrEqualTo(Object value) {
            addCriterion("UNLOCKTIME <=", value, "unlocktime");
            return this;
        }

        public Criteria andUnlocktimeIn(List values) {
            addCriterion("UNLOCKTIME in", values, "unlocktime");
            return this;
        }

        public Criteria andUnlocktimeNotIn(List values) {
            addCriterion("UNLOCKTIME not in", values, "unlocktime");
            return this;
        }

        public Criteria andUnlocktimeBetween(Object value1, Object value2) {
            addCriterion("UNLOCKTIME between", value1, value2, "unlocktime");
            return this;
        }

        public Criteria andUnlocktimeNotBetween(Object value1, Object value2) {
            addCriterion("UNLOCKTIME not between", value1, value2, "unlocktime");
            return this;
        }

        public Criteria andMenutypeIsNull() {
            addCriterion("MENUTYPE is null");
            return this;
        }

        public Criteria andMenutypeIsNotNull() {
            addCriterion("MENUTYPE is not null");
            return this;
        }

        public Criteria andMenutypeEqualTo(String value) {
            addCriterion("MENUTYPE =", value, "menutype");
            return this;
        }

        public Criteria andMenutypeNotEqualTo(String value) {
            addCriterion("MENUTYPE <>", value, "menutype");
            return this;
        }

        public Criteria andMenutypeGreaterThan(String value) {
            addCriterion("MENUTYPE >", value, "menutype");
            return this;
        }

        public Criteria andMenutypeGreaterThanOrEqualTo(String value) {
            addCriterion("MENUTYPE >=", value, "menutype");
            return this;
        }

        public Criteria andMenutypeLessThan(String value) {
            addCriterion("MENUTYPE <", value, "menutype");
            return this;
        }

        public Criteria andMenutypeLessThanOrEqualTo(String value) {
            addCriterion("MENUTYPE <=", value, "menutype");
            return this;
        }

        public Criteria andMenutypeLike(String value) {
            addCriterion("MENUTYPE like", value, "menutype");
            return this;
        }

        public Criteria andMenutypeNotLike(String value) {
            addCriterion("MENUTYPE not like", value, "menutype");
            return this;
        }

        public Criteria andMenutypeIn(List values) {
            addCriterion("MENUTYPE in", values, "menutype");
            return this;
        }

        public Criteria andMenutypeNotIn(List values) {
            addCriterion("MENUTYPE not in", values, "menutype");
            return this;
        }

        public Criteria andMenutypeBetween(String value1, String value2) {
            addCriterion("MENUTYPE between", value1, value2, "menutype");
            return this;
        }

        public Criteria andMenutypeNotBetween(String value1, String value2) {
            addCriterion("MENUTYPE not between", value1, value2, "menutype");
            return this;
        }

        public Criteria andLastloginIsNull() {
            addCriterion("LASTLOGIN is null");
            return this;
        }

        public Criteria andLastloginIsNotNull() {
            addCriterion("LASTLOGIN is not null");
            return this;
        }

        public Criteria andLastloginEqualTo(Object value) {
            addCriterion("LASTLOGIN =", value, "lastlogin");
            return this;
        }

        public Criteria andLastloginNotEqualTo(Object value) {
            addCriterion("LASTLOGIN <>", value, "lastlogin");
            return this;
        }

        public Criteria andLastloginGreaterThan(Object value) {
            addCriterion("LASTLOGIN >", value, "lastlogin");
            return this;
        }

        public Criteria andLastloginGreaterThanOrEqualTo(Object value) {
            addCriterion("LASTLOGIN >=", value, "lastlogin");
            return this;
        }

        public Criteria andLastloginLessThan(Object value) {
            addCriterion("LASTLOGIN <", value, "lastlogin");
            return this;
        }

        public Criteria andLastloginLessThanOrEqualTo(Object value) {
            addCriterion("LASTLOGIN <=", value, "lastlogin");
            return this;
        }

        public Criteria andLastloginIn(List values) {
            addCriterion("LASTLOGIN in", values, "lastlogin");
            return this;
        }

        public Criteria andLastloginNotIn(List values) {
            addCriterion("LASTLOGIN not in", values, "lastlogin");
            return this;
        }

        public Criteria andLastloginBetween(Object value1, Object value2) {
            addCriterion("LASTLOGIN between", value1, value2, "lastlogin");
            return this;
        }

        public Criteria andLastloginNotBetween(Object value1, Object value2) {
            addCriterion("LASTLOGIN not between", value1, value2, "lastlogin");
            return this;
        }

        public Criteria andErrcountIsNull() {
            addCriterion("ERRCOUNT is null");
            return this;
        }

        public Criteria andErrcountIsNotNull() {
            addCriterion("ERRCOUNT is not null");
            return this;
        }

        public Criteria andErrcountEqualTo(Integer value) {
            addCriterion("ERRCOUNT =", value, "errcount");
            return this;
        }

        public Criteria andErrcountNotEqualTo(Integer value) {
            addCriterion("ERRCOUNT <>", value, "errcount");
            return this;
        }

        public Criteria andErrcountGreaterThan(Integer value) {
            addCriterion("ERRCOUNT >", value, "errcount");
            return this;
        }

        public Criteria andErrcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("ERRCOUNT >=", value, "errcount");
            return this;
        }

        public Criteria andErrcountLessThan(Integer value) {
            addCriterion("ERRCOUNT <", value, "errcount");
            return this;
        }

        public Criteria andErrcountLessThanOrEqualTo(Integer value) {
            addCriterion("ERRCOUNT <=", value, "errcount");
            return this;
        }

        public Criteria andErrcountIn(List values) {
            addCriterion("ERRCOUNT in", values, "errcount");
            return this;
        }

        public Criteria andErrcountNotIn(List values) {
            addCriterion("ERRCOUNT not in", values, "errcount");
            return this;
        }

        public Criteria andErrcountBetween(Integer value1, Integer value2) {
            addCriterion("ERRCOUNT between", value1, value2, "errcount");
            return this;
        }

        public Criteria andErrcountNotBetween(Integer value1, Integer value2) {
            addCriterion("ERRCOUNT not between", value1, value2, "errcount");
            return this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("STARTDATE is null");
            return this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("STARTDATE is not null");
            return this;
        }

        public Criteria andStartdateEqualTo(Date value) {
            addCriterion("STARTDATE =", value, "startdate");
            return this;
        }

        public Criteria andStartdateNotEqualTo(Date value) {
            addCriterion("STARTDATE <>", value, "startdate");
            return this;
        }

        public Criteria andStartdateGreaterThan(Date value) {
            addCriterion("STARTDATE >", value, "startdate");
            return this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
            addCriterion("STARTDATE >=", value, "startdate");
            return this;
        }

        public Criteria andStartdateLessThan(Date value) {
            addCriterion("STARTDATE <", value, "startdate");
            return this;
        }

        public Criteria andStartdateLessThanOrEqualTo(Date value) {
            addCriterion("STARTDATE <=", value, "startdate");
            return this;
        }

        public Criteria andStartdateIn(List values) {
            addCriterion("STARTDATE in", values, "startdate");
            return this;
        }

        public Criteria andStartdateNotIn(List values) {
            addCriterion("STARTDATE not in", values, "startdate");
            return this;
        }

        public Criteria andStartdateBetween(Date value1, Date value2) {
            addCriterion("STARTDATE between", value1, value2, "startdate");
            return this;
        }

        public Criteria andStartdateNotBetween(Date value1, Date value2) {
            addCriterion("STARTDATE not between", value1, value2, "startdate");
            return this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("ENDDATE is null");
            return this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("ENDDATE is not null");
            return this;
        }

        public Criteria andEnddateEqualTo(Date value) {
            addCriterion("ENDDATE =", value, "enddate");
            return this;
        }

        public Criteria andEnddateNotEqualTo(Date value) {
            addCriterion("ENDDATE <>", value, "enddate");
            return this;
        }

        public Criteria andEnddateGreaterThan(Date value) {
            addCriterion("ENDDATE >", value, "enddate");
            return this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(Date value) {
            addCriterion("ENDDATE >=", value, "enddate");
            return this;
        }

        public Criteria andEnddateLessThan(Date value) {
            addCriterion("ENDDATE <", value, "enddate");
            return this;
        }

        public Criteria andEnddateLessThanOrEqualTo(Date value) {
            addCriterion("ENDDATE <=", value, "enddate");
            return this;
        }

        public Criteria andEnddateIn(List values) {
            addCriterion("ENDDATE in", values, "enddate");
            return this;
        }

        public Criteria andEnddateNotIn(List values) {
            addCriterion("ENDDATE not in", values, "enddate");
            return this;
        }

        public Criteria andEnddateBetween(Date value1, Date value2) {
            addCriterion("ENDDATE between", value1, value2, "enddate");
            return this;
        }

        public Criteria andEnddateNotBetween(Date value1, Date value2) {
            addCriterion("ENDDATE not between", value1, value2, "enddate");
            return this;
        }

        public Criteria andValidtimeIsNull() {
            addCriterion("VALIDTIME is null");
            return this;
        }

        public Criteria andValidtimeIsNotNull() {
            addCriterion("VALIDTIME is not null");
            return this;
        }

        public Criteria andValidtimeEqualTo(String value) {
            addCriterion("VALIDTIME =", value, "validtime");
            return this;
        }

        public Criteria andValidtimeNotEqualTo(String value) {
            addCriterion("VALIDTIME <>", value, "validtime");
            return this;
        }

        public Criteria andValidtimeGreaterThan(String value) {
            addCriterion("VALIDTIME >", value, "validtime");
            return this;
        }

        public Criteria andValidtimeGreaterThanOrEqualTo(String value) {
            addCriterion("VALIDTIME >=", value, "validtime");
            return this;
        }

        public Criteria andValidtimeLessThan(String value) {
            addCriterion("VALIDTIME <", value, "validtime");
            return this;
        }

        public Criteria andValidtimeLessThanOrEqualTo(String value) {
            addCriterion("VALIDTIME <=", value, "validtime");
            return this;
        }

        public Criteria andValidtimeLike(String value) {
            addCriterion("VALIDTIME like", value, "validtime");
            return this;
        }

        public Criteria andValidtimeNotLike(String value) {
            addCriterion("VALIDTIME not like", value, "validtime");
            return this;
        }

        public Criteria andValidtimeIn(List values) {
            addCriterion("VALIDTIME in", values, "validtime");
            return this;
        }

        public Criteria andValidtimeNotIn(List values) {
            addCriterion("VALIDTIME not in", values, "validtime");
            return this;
        }

        public Criteria andValidtimeBetween(String value1, String value2) {
            addCriterion("VALIDTIME between", value1, value2, "validtime");
            return this;
        }

        public Criteria andValidtimeNotBetween(String value1, String value2) {
            addCriterion("VALIDTIME not between", value1, value2, "validtime");
            return this;
        }

        public Criteria andMaccodeIsNull() {
            addCriterion("MACCODE is null");
            return this;
        }

        public Criteria andMaccodeIsNotNull() {
            addCriterion("MACCODE is not null");
            return this;
        }

        public Criteria andMaccodeEqualTo(String value) {
            addCriterion("MACCODE =", value, "maccode");
            return this;
        }

        public Criteria andMaccodeNotEqualTo(String value) {
            addCriterion("MACCODE <>", value, "maccode");
            return this;
        }

        public Criteria andMaccodeGreaterThan(String value) {
            addCriterion("MACCODE >", value, "maccode");
            return this;
        }

        public Criteria andMaccodeGreaterThanOrEqualTo(String value) {
            addCriterion("MACCODE >=", value, "maccode");
            return this;
        }

        public Criteria andMaccodeLessThan(String value) {
            addCriterion("MACCODE <", value, "maccode");
            return this;
        }

        public Criteria andMaccodeLessThanOrEqualTo(String value) {
            addCriterion("MACCODE <=", value, "maccode");
            return this;
        }

        public Criteria andMaccodeLike(String value) {
            addCriterion("MACCODE like", value, "maccode");
            return this;
        }

        public Criteria andMaccodeNotLike(String value) {
            addCriterion("MACCODE not like", value, "maccode");
            return this;
        }

        public Criteria andMaccodeIn(List values) {
            addCriterion("MACCODE in", values, "maccode");
            return this;
        }

        public Criteria andMaccodeNotIn(List values) {
            addCriterion("MACCODE not in", values, "maccode");
            return this;
        }

        public Criteria andMaccodeBetween(String value1, String value2) {
            addCriterion("MACCODE between", value1, value2, "maccode");
            return this;
        }

        public Criteria andMaccodeNotBetween(String value1, String value2) {
            addCriterion("MACCODE not between", value1, value2, "maccode");
            return this;
        }

        public Criteria andIpaddressIsNull() {
            addCriterion("IPADDRESS is null");
            return this;
        }

        public Criteria andIpaddressIsNotNull() {
            addCriterion("IPADDRESS is not null");
            return this;
        }

        public Criteria andIpaddressEqualTo(String value) {
            addCriterion("IPADDRESS =", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotEqualTo(String value) {
            addCriterion("IPADDRESS <>", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressGreaterThan(String value) {
            addCriterion("IPADDRESS >", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressGreaterThanOrEqualTo(String value) {
            addCriterion("IPADDRESS >=", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressLessThan(String value) {
            addCriterion("IPADDRESS <", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressLessThanOrEqualTo(String value) {
            addCriterion("IPADDRESS <=", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressLike(String value) {
            addCriterion("IPADDRESS like", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotLike(String value) {
            addCriterion("IPADDRESS not like", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressIn(List values) {
            addCriterion("IPADDRESS in", values, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotIn(List values) {
            addCriterion("IPADDRESS not in", values, "ipaddress");
            return this;
        }

        public Criteria andIpaddressBetween(String value1, String value2) {
            addCriterion("IPADDRESS between", value1, value2, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotBetween(String value1, String value2) {
            addCriterion("IPADDRESS not between", value1, value2, "ipaddress");
            return this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return this;
        }

        public Criteria andEmailIn(List values) {
            addCriterion("EMAIL in", values, "email");
            return this;
        }

        public Criteria andEmailNotIn(List values) {
            addCriterion("EMAIL not in", values, "email");
            return this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return this;
        }

        public Criteria andEmpidIsNull() {
            addCriterion("EMPID is null");
            return this;
        }

        public Criteria andEmpidIsNotNull() {
            addCriterion("EMPID is not null");
            return this;
        }

        public Criteria andEmpidEqualTo(Integer value) {
            addCriterion("EMPID =", value, "empid");
            return this;
        }

        public Criteria andEmpidNotEqualTo(Integer value) {
            addCriterion("EMPID <>", value, "empid");
            return this;
        }

        public Criteria andEmpidGreaterThan(Integer value) {
            addCriterion("EMPID >", value, "empid");
            return this;
        }

        public Criteria andEmpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("EMPID >=", value, "empid");
            return this;
        }

        public Criteria andEmpidLessThan(Integer value) {
            addCriterion("EMPID <", value, "empid");
            return this;
        }

        public Criteria andEmpidLessThanOrEqualTo(Integer value) {
            addCriterion("EMPID <=", value, "empid");
            return this;
        }

        public Criteria andEmpidIn(List values) {
            addCriterion("EMPID in", values, "empid");
            return this;
        }

        public Criteria andEmpidNotIn(List values) {
            addCriterion("EMPID not in", values, "empid");
            return this;
        }

        public Criteria andEmpidBetween(Integer value1, Integer value2) {
            addCriterion("EMPID between", value1, value2, "empid");
            return this;
        }

        public Criteria andEmpidNotBetween(Integer value1, Integer value2) {
            addCriterion("EMPID not between", value1, value2, "empid");
            return this;
        }
    }
}