package com.gotop.dataIssued.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TSendDataExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TSendDataExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public TSendDataExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected TSendDataExample(TSendDataExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_SEND_DATA
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andDsIdIsNull() {
            addCriterion("DS_ID is null");
            return this;
        }

        public Criteria andDsIdIsNotNull() {
            addCriterion("DS_ID is not null");
            return this;
        }

        public Criteria andDsIdEqualTo(Long value) {
            addCriterion("DS_ID =", value, "dsId");
            return this;
        }

        public Criteria andDsIdNotEqualTo(Long value) {
            addCriterion("DS_ID <>", value, "dsId");
            return this;
        }

        public Criteria andDsIdGreaterThan(Long value) {
            addCriterion("DS_ID >", value, "dsId");
            return this;
        }

        public Criteria andDsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DS_ID >=", value, "dsId");
            return this;
        }

        public Criteria andDsIdLessThan(Long value) {
            addCriterion("DS_ID <", value, "dsId");
            return this;
        }

        public Criteria andDsIdLessThanOrEqualTo(Long value) {
            addCriterion("DS_ID <=", value, "dsId");
            return this;
        }

        public Criteria andDsIdIn(List values) {
            addCriterion("DS_ID in", values, "dsId");
            return this;
        }

        public Criteria andDsIdNotIn(List values) {
            addCriterion("DS_ID not in", values, "dsId");
            return this;
        }

        public Criteria andDsIdBetween(Long value1, Long value2) {
            addCriterion("DS_ID between", value1, value2, "dsId");
            return this;
        }

        public Criteria andDsIdNotBetween(Long value1, Long value2) {
            addCriterion("DS_ID not between", value1, value2, "dsId");
            return this;
        }

        public Criteria andSEmpIdIsNull() {
            addCriterion("S_EMP_ID is null");
            return this;
        }

        public Criteria andSEmpIdIsNotNull() {
            addCriterion("S_EMP_ID is not null");
            return this;
        }

        public Criteria andSEmpIdEqualTo(Long value) {
            addCriterion("S_EMP_ID =", value, "sEmpId");
            return this;
        }

        public Criteria andSEmpIdNotEqualTo(Long value) {
            addCriterion("S_EMP_ID <>", value, "sEmpId");
            return this;
        }

        public Criteria andSEmpIdGreaterThan(Long value) {
            addCriterion("S_EMP_ID >", value, "sEmpId");
            return this;
        }

        public Criteria andSEmpIdGreaterThanOrEqualTo(Long value) {
            addCriterion("S_EMP_ID >=", value, "sEmpId");
            return this;
        }

        public Criteria andSEmpIdLessThan(Long value) {
            addCriterion("S_EMP_ID <", value, "sEmpId");
            return this;
        }

        public Criteria andSEmpIdLessThanOrEqualTo(Long value) {
            addCriterion("S_EMP_ID <=", value, "sEmpId");
            return this;
        }

        public Criteria andSEmpIdIn(List values) {
            addCriterion("S_EMP_ID in", values, "sEmpId");
            return this;
        }

        public Criteria andSEmpIdNotIn(List values) {
            addCriterion("S_EMP_ID not in", values, "sEmpId");
            return this;
        }

        public Criteria andSEmpIdBetween(Long value1, Long value2) {
            addCriterion("S_EMP_ID between", value1, value2, "sEmpId");
            return this;
        }

        public Criteria andSEmpIdNotBetween(Long value1, Long value2) {
            addCriterion("S_EMP_ID not between", value1, value2, "sEmpId");
            return this;
        }

        public Criteria andFlowIdIsNull() {
            addCriterion("FLOW_ID is null");
            return this;
        }

        public Criteria andFlowIdIsNotNull() {
            addCriterion("FLOW_ID is not null");
            return this;
        }

        public Criteria andFlowIdEqualTo(String value) {
            addCriterion("FLOW_ID =", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotEqualTo(String value) {
            addCriterion("FLOW_ID <>", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThan(String value) {
            addCriterion("FLOW_ID >", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThanOrEqualTo(String value) {
            addCriterion("FLOW_ID >=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThan(String value) {
            addCriterion("FLOW_ID <", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThanOrEqualTo(String value) {
            addCriterion("FLOW_ID <=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLike(String value) {
            addCriterion("FLOW_ID like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotLike(String value) {
            addCriterion("FLOW_ID not like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdIn(List values) {
            addCriterion("FLOW_ID in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdNotIn(List values) {
            addCriterion("FLOW_ID not in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdBetween(String value1, String value2) {
            addCriterion("FLOW_ID between", value1, value2, "flowId");
            return this;
        }

        public Criteria andFlowIdNotBetween(String value1, String value2) {
            addCriterion("FLOW_ID not between", value1, value2, "flowId");
            return this;
        }

        public Criteria andDataSourceIsNull() {
            addCriterion("DATA_SOURCE is null");
            return this;
        }

        public Criteria andDataSourceIsNotNull() {
            addCriterion("DATA_SOURCE is not null");
            return this;
        }

        public Criteria andDataSourceEqualTo(String value) {
            addCriterion("DATA_SOURCE =", value, "dataSource");
            return this;
        }

        public Criteria andDataSourceNotEqualTo(String value) {
            addCriterion("DATA_SOURCE <>", value, "dataSource");
            return this;
        }

        public Criteria andDataSourceGreaterThan(String value) {
            addCriterion("DATA_SOURCE >", value, "dataSource");
            return this;
        }

        public Criteria andDataSourceGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_SOURCE >=", value, "dataSource");
            return this;
        }

        public Criteria andDataSourceLessThan(String value) {
            addCriterion("DATA_SOURCE <", value, "dataSource");
            return this;
        }

        public Criteria andDataSourceLessThanOrEqualTo(String value) {
            addCriterion("DATA_SOURCE <=", value, "dataSource");
            return this;
        }

        public Criteria andDataSourceLike(String value) {
            addCriterion("DATA_SOURCE like", value, "dataSource");
            return this;
        }

        public Criteria andDataSourceNotLike(String value) {
            addCriterion("DATA_SOURCE not like", value, "dataSource");
            return this;
        }

        public Criteria andDataSourceIn(List values) {
            addCriterion("DATA_SOURCE in", values, "dataSource");
            return this;
        }

        public Criteria andDataSourceNotIn(List values) {
            addCriterion("DATA_SOURCE not in", values, "dataSource");
            return this;
        }

        public Criteria andDataSourceBetween(String value1, String value2) {
            addCriterion("DATA_SOURCE between", value1, value2, "dataSource");
            return this;
        }

        public Criteria andDataSourceNotBetween(String value1, String value2) {
            addCriterion("DATA_SOURCE not between", value1, value2, "dataSource");
            return this;
        }

        public Criteria andDaProIsNull() {
            addCriterion("DA_PRO is null");
            return this;
        }

        public Criteria andDaProIsNotNull() {
            addCriterion("DA_PRO is not null");
            return this;
        }

        public Criteria andDaProEqualTo(String value) {
            addCriterion("DA_PRO =", value, "daPro");
            return this;
        }

        public Criteria andDaProNotEqualTo(String value) {
            addCriterion("DA_PRO <>", value, "daPro");
            return this;
        }

        public Criteria andDaProGreaterThan(String value) {
            addCriterion("DA_PRO >", value, "daPro");
            return this;
        }

        public Criteria andDaProGreaterThanOrEqualTo(String value) {
            addCriterion("DA_PRO >=", value, "daPro");
            return this;
        }

        public Criteria andDaProLessThan(String value) {
            addCriterion("DA_PRO <", value, "daPro");
            return this;
        }

        public Criteria andDaProLessThanOrEqualTo(String value) {
            addCriterion("DA_PRO <=", value, "daPro");
            return this;
        }

        public Criteria andDaProLike(String value) {
            addCriterion("DA_PRO like", value, "daPro");
            return this;
        }

        public Criteria andDaProNotLike(String value) {
            addCriterion("DA_PRO not like", value, "daPro");
            return this;
        }

        public Criteria andDaProIn(List values) {
            addCriterion("DA_PRO in", values, "daPro");
            return this;
        }

        public Criteria andDaProNotIn(List values) {
            addCriterion("DA_PRO not in", values, "daPro");
            return this;
        }

        public Criteria andDaProBetween(String value1, String value2) {
            addCriterion("DA_PRO between", value1, value2, "daPro");
            return this;
        }

        public Criteria andDaProNotBetween(String value1, String value2) {
            addCriterion("DA_PRO not between", value1, value2, "daPro");
            return this;
        }

        public Criteria andDataTypeIsNull() {
            addCriterion("DATA_TYPE is null");
            return this;
        }

        public Criteria andDataTypeIsNotNull() {
            addCriterion("DATA_TYPE is not null");
            return this;
        }

        public Criteria andDataTypeEqualTo(String value) {
            addCriterion("DATA_TYPE =", value, "dataType");
            return this;
        }

        public Criteria andDataTypeNotEqualTo(String value) {
            addCriterion("DATA_TYPE <>", value, "dataType");
            return this;
        }

        public Criteria andDataTypeGreaterThan(String value) {
            addCriterion("DATA_TYPE >", value, "dataType");
            return this;
        }

        public Criteria andDataTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_TYPE >=", value, "dataType");
            return this;
        }

        public Criteria andDataTypeLessThan(String value) {
            addCriterion("DATA_TYPE <", value, "dataType");
            return this;
        }

        public Criteria andDataTypeLessThanOrEqualTo(String value) {
            addCriterion("DATA_TYPE <=", value, "dataType");
            return this;
        }

        public Criteria andDataTypeLike(String value) {
            addCriterion("DATA_TYPE like", value, "dataType");
            return this;
        }

        public Criteria andDataTypeNotLike(String value) {
            addCriterion("DATA_TYPE not like", value, "dataType");
            return this;
        }

        public Criteria andDataTypeIn(List values) {
            addCriterion("DATA_TYPE in", values, "dataType");
            return this;
        }

        public Criteria andDataTypeNotIn(List values) {
            addCriterion("DATA_TYPE not in", values, "dataType");
            return this;
        }

        public Criteria andDataTypeBetween(String value1, String value2) {
            addCriterion("DATA_TYPE between", value1, value2, "dataType");
            return this;
        }

        public Criteria andDataTypeNotBetween(String value1, String value2) {
            addCriterion("DATA_TYPE not between", value1, value2, "dataType");
            return this;
        }

        public Criteria andRvTypeIsNull() {
            addCriterion("RV_TYPE is null");
            return this;
        }

        public Criteria andRvTypeIsNotNull() {
            addCriterion("RV_TYPE is not null");
            return this;
        }

        public Criteria andRvTypeEqualTo(String value) {
            addCriterion("RV_TYPE =", value, "rvType");
            return this;
        }

        public Criteria andRvTypeNotEqualTo(String value) {
            addCriterion("RV_TYPE <>", value, "rvType");
            return this;
        }

        public Criteria andRvTypeGreaterThan(String value) {
            addCriterion("RV_TYPE >", value, "rvType");
            return this;
        }

        public Criteria andRvTypeGreaterThanOrEqualTo(String value) {
            addCriterion("RV_TYPE >=", value, "rvType");
            return this;
        }

        public Criteria andRvTypeLessThan(String value) {
            addCriterion("RV_TYPE <", value, "rvType");
            return this;
        }

        public Criteria andRvTypeLessThanOrEqualTo(String value) {
            addCriterion("RV_TYPE <=", value, "rvType");
            return this;
        }

        public Criteria andRvTypeLike(String value) {
            addCriterion("RV_TYPE like", value, "rvType");
            return this;
        }

        public Criteria andRvTypeNotLike(String value) {
            addCriterion("RV_TYPE not like", value, "rvType");
            return this;
        }

        public Criteria andRvTypeIn(List values) {
            addCriterion("RV_TYPE in", values, "rvType");
            return this;
        }

        public Criteria andRvTypeNotIn(List values) {
            addCriterion("RV_TYPE not in", values, "rvType");
            return this;
        }

        public Criteria andRvTypeBetween(String value1, String value2) {
            addCriterion("RV_TYPE between", value1, value2, "rvType");
            return this;
        }

        public Criteria andRvTypeNotBetween(String value1, String value2) {
            addCriterion("RV_TYPE not between", value1, value2, "rvType");
            return this;
        }

        public Criteria andDsTitleIsNull() {
            addCriterion("DS_TITLE is null");
            return this;
        }

        public Criteria andDsTitleIsNotNull() {
            addCriterion("DS_TITLE is not null");
            return this;
        }

        public Criteria andDsTitleEqualTo(String value) {
            addCriterion("DS_TITLE =", value, "dsTitle");
            return this;
        }

        public Criteria andDsTitleNotEqualTo(String value) {
            addCriterion("DS_TITLE <>", value, "dsTitle");
            return this;
        }

        public Criteria andDsTitleGreaterThan(String value) {
            addCriterion("DS_TITLE >", value, "dsTitle");
            return this;
        }

        public Criteria andDsTitleGreaterThanOrEqualTo(String value) {
            addCriterion("DS_TITLE >=", value, "dsTitle");
            return this;
        }

        public Criteria andDsTitleLessThan(String value) {
            addCriterion("DS_TITLE <", value, "dsTitle");
            return this;
        }

        public Criteria andDsTitleLessThanOrEqualTo(String value) {
            addCriterion("DS_TITLE <=", value, "dsTitle");
            return this;
        }

        public Criteria andDsTitleLike(String value) {
            addCriterion("DS_TITLE like", value, "dsTitle");
            return this;
        }

        public Criteria andDsTitleNotLike(String value) {
            addCriterion("DS_TITLE not like", value, "dsTitle");
            return this;
        }

        public Criteria andDsTitleIn(List values) {
            addCriterion("DS_TITLE in", values, "dsTitle");
            return this;
        }

        public Criteria andDsTitleNotIn(List values) {
            addCriterion("DS_TITLE not in", values, "dsTitle");
            return this;
        }

        public Criteria andDsTitleBetween(String value1, String value2) {
            addCriterion("DS_TITLE between", value1, value2, "dsTitle");
            return this;
        }

        public Criteria andDsTitleNotBetween(String value1, String value2) {
            addCriterion("DS_TITLE not between", value1, value2, "dsTitle");
            return this;
        }

        public Criteria andDsExplIsNull() {
            addCriterion("DS_EXPL is null");
            return this;
        }

        public Criteria andDsExplIsNotNull() {
            addCriterion("DS_EXPL is not null");
            return this;
        }

        public Criteria andDsExplEqualTo(String value) {
            addCriterion("DS_EXPL =", value, "dsExpl");
            return this;
        }

        public Criteria andDsExplNotEqualTo(String value) {
            addCriterion("DS_EXPL <>", value, "dsExpl");
            return this;
        }

        public Criteria andDsExplGreaterThan(String value) {
            addCriterion("DS_EXPL >", value, "dsExpl");
            return this;
        }

        public Criteria andDsExplGreaterThanOrEqualTo(String value) {
            addCriterion("DS_EXPL >=", value, "dsExpl");
            return this;
        }

        public Criteria andDsExplLessThan(String value) {
            addCriterion("DS_EXPL <", value, "dsExpl");
            return this;
        }

        public Criteria andDsExplLessThanOrEqualTo(String value) {
            addCriterion("DS_EXPL <=", value, "dsExpl");
            return this;
        }

        public Criteria andDsExplLike(String value) {
            addCriterion("DS_EXPL like", value, "dsExpl");
            return this;
        }

        public Criteria andDsExplNotLike(String value) {
            addCriterion("DS_EXPL not like", value, "dsExpl");
            return this;
        }

        public Criteria andDsExplIn(List values) {
            addCriterion("DS_EXPL in", values, "dsExpl");
            return this;
        }

        public Criteria andDsExplNotIn(List values) {
            addCriterion("DS_EXPL not in", values, "dsExpl");
            return this;
        }

        public Criteria andDsExplBetween(String value1, String value2) {
            addCriterion("DS_EXPL between", value1, value2, "dsExpl");
            return this;
        }

        public Criteria andDsExplNotBetween(String value1, String value2) {
            addCriterion("DS_EXPL not between", value1, value2, "dsExpl");
            return this;
        }

        public Criteria andTimeLimitIsNull() {
            addCriterion("TIME_LIMIT is null");
            return this;
        }

        public Criteria andTimeLimitIsNotNull() {
            addCriterion("TIME_LIMIT is not null");
            return this;
        }

        public Criteria andTimeLimitEqualTo(String value) {
            addCriterion("TIME_LIMIT =", value, "timeLimit");
            return this;
        }

        public Criteria andTimeLimitNotEqualTo(String value) {
            addCriterion("TIME_LIMIT <>", value, "timeLimit");
            return this;
        }

        public Criteria andTimeLimitGreaterThan(String value) {
            addCriterion("TIME_LIMIT >", value, "timeLimit");
            return this;
        }

        public Criteria andTimeLimitGreaterThanOrEqualTo(String value) {
            addCriterion("TIME_LIMIT >=", value, "timeLimit");
            return this;
        }

        public Criteria andTimeLimitLessThan(String value) {
            addCriterion("TIME_LIMIT <", value, "timeLimit");
            return this;
        }

        public Criteria andTimeLimitLessThanOrEqualTo(String value) {
            addCriterion("TIME_LIMIT <=", value, "timeLimit");
            return this;
        }

        public Criteria andTimeLimitLike(String value) {
            addCriterion("TIME_LIMIT like", value, "timeLimit");
            return this;
        }

        public Criteria andTimeLimitNotLike(String value) {
            addCriterion("TIME_LIMIT not like", value, "timeLimit");
            return this;
        }

        public Criteria andTimeLimitIn(List values) {
            addCriterion("TIME_LIMIT in", values, "timeLimit");
            return this;
        }

        public Criteria andTimeLimitNotIn(List values) {
            addCriterion("TIME_LIMIT not in", values, "timeLimit");
            return this;
        }

        public Criteria andTimeLimitBetween(String value1, String value2) {
            addCriterion("TIME_LIMIT between", value1, value2, "timeLimit");
            return this;
        }

        public Criteria andTimeLimitNotBetween(String value1, String value2) {
            addCriterion("TIME_LIMIT not between", value1, value2, "timeLimit");
            return this;
        }

        public Criteria andDesTimeIsNull() {
            addCriterion("DES_TIME is null");
            return this;
        }

        public Criteria andDesTimeIsNotNull() {
            addCriterion("DES_TIME is not null");
            return this;
        }

        public Criteria andDesTimeEqualTo(String value) {
            addCriterion("DES_TIME =", value, "desTime");
            return this;
        }

        public Criteria andDesTimeNotEqualTo(String value) {
            addCriterion("DES_TIME <>", value, "desTime");
            return this;
        }

        public Criteria andDesTimeGreaterThan(String value) {
            addCriterion("DES_TIME >", value, "desTime");
            return this;
        }

        public Criteria andDesTimeGreaterThanOrEqualTo(String value) {
            addCriterion("DES_TIME >=", value, "desTime");
            return this;
        }

        public Criteria andDesTimeLessThan(String value) {
            addCriterion("DES_TIME <", value, "desTime");
            return this;
        }

        public Criteria andDesTimeLessThanOrEqualTo(String value) {
            addCriterion("DES_TIME <=", value, "desTime");
            return this;
        }

        public Criteria andDesTimeLike(String value) {
            addCriterion("DES_TIME like", value, "desTime");
            return this;
        }

        public Criteria andDesTimeNotLike(String value) {
            addCriterion("DES_TIME not like", value, "desTime");
            return this;
        }

        public Criteria andDesTimeIn(List values) {
            addCriterion("DES_TIME in", values, "desTime");
            return this;
        }

        public Criteria andDesTimeNotIn(List values) {
            addCriterion("DES_TIME not in", values, "desTime");
            return this;
        }

        public Criteria andDesTimeBetween(String value1, String value2) {
            addCriterion("DES_TIME between", value1, value2, "desTime");
            return this;
        }

        public Criteria andDesTimeNotBetween(String value1, String value2) {
            addCriterion("DES_TIME not between", value1, value2, "desTime");
            return this;
        }

        public Criteria andDEmpIdIsNull() {
            addCriterion("D_EMP_ID is null");
            return this;
        }

        public Criteria andDEmpIdIsNotNull() {
            addCriterion("D_EMP_ID is not null");
            return this;
        }

        public Criteria andDEmpIdEqualTo(Long value) {
            addCriterion("D_EMP_ID =", value, "dEmpId");
            return this;
        }

        public Criteria andDEmpIdNotEqualTo(Long value) {
            addCriterion("D_EMP_ID <>", value, "dEmpId");
            return this;
        }

        public Criteria andDEmpIdGreaterThan(Long value) {
            addCriterion("D_EMP_ID >", value, "dEmpId");
            return this;
        }

        public Criteria andDEmpIdGreaterThanOrEqualTo(Long value) {
            addCriterion("D_EMP_ID >=", value, "dEmpId");
            return this;
        }

        public Criteria andDEmpIdLessThan(Long value) {
            addCriterion("D_EMP_ID <", value, "dEmpId");
            return this;
        }

        public Criteria andDEmpIdLessThanOrEqualTo(Long value) {
            addCriterion("D_EMP_ID <=", value, "dEmpId");
            return this;
        }

        public Criteria andDEmpIdIn(List values) {
            addCriterion("D_EMP_ID in", values, "dEmpId");
            return this;
        }

        public Criteria andDEmpIdNotIn(List values) {
            addCriterion("D_EMP_ID not in", values, "dEmpId");
            return this;
        }

        public Criteria andDEmpIdBetween(Long value1, Long value2) {
            addCriterion("D_EMP_ID between", value1, value2, "dEmpId");
            return this;
        }

        public Criteria andDEmpIdNotBetween(Long value1, Long value2) {
            addCriterion("D_EMP_ID not between", value1, value2, "dEmpId");
            return this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateIn(List values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateNotIn(List values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }
    }
}