package com.gotop.dataApply.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TApplyDataExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TApplyDataExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public TApplyDataExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected TApplyDataExample(TApplyDataExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_APPLY_DATA
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andDaIdIsNull() {
            addCriterion("DA_ID is null");
            return this;
        }

        public Criteria andDaIdIsNotNull() {
            addCriterion("DA_ID is not null");
            return this;
        }

        public Criteria andDaIdEqualTo(Long value) {
            addCriterion("DA_ID =", value, "daId");
            return this;
        }

        public Criteria andDaIdNotEqualTo(Long value) {
            addCriterion("DA_ID <>", value, "daId");
            return this;
        }

        public Criteria andDaIdGreaterThan(Long value) {
            addCriterion("DA_ID >", value, "daId");
            return this;
        }

        public Criteria andDaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DA_ID >=", value, "daId");
            return this;
        }

        public Criteria andDaIdLessThan(Long value) {
            addCriterion("DA_ID <", value, "daId");
            return this;
        }

        public Criteria andDaIdLessThanOrEqualTo(Long value) {
            addCriterion("DA_ID <=", value, "daId");
            return this;
        }

        public Criteria andDaIdIn(List values) {
            addCriterion("DA_ID in", values, "daId");
            return this;
        }

        public Criteria andDaIdNotIn(List values) {
            addCriterion("DA_ID not in", values, "daId");
            return this;
        }

        public Criteria andDaIdBetween(Long value1, Long value2) {
            addCriterion("DA_ID between", value1, value2, "daId");
            return this;
        }

        public Criteria andDaIdNotBetween(Long value1, Long value2) {
            addCriterion("DA_ID not between", value1, value2, "daId");
            return this;
        }

        public Criteria andEmpIdIsNull() {
            addCriterion("EMP_ID is null");
            return this;
        }

        public Criteria andEmpIdIsNotNull() {
            addCriterion("EMP_ID is not null");
            return this;
        }

        public Criteria andEmpIdEqualTo(Long value) {
            addCriterion("EMP_ID =", value, "empId");
            return this;
        }

        public Criteria andEmpIdNotEqualTo(Long value) {
            addCriterion("EMP_ID <>", value, "empId");
            return this;
        }

        public Criteria andEmpIdGreaterThan(Long value) {
            addCriterion("EMP_ID >", value, "empId");
            return this;
        }

        public Criteria andEmpIdGreaterThanOrEqualTo(Long value) {
            addCriterion("EMP_ID >=", value, "empId");
            return this;
        }

        public Criteria andEmpIdLessThan(Long value) {
            addCriterion("EMP_ID <", value, "empId");
            return this;
        }

        public Criteria andEmpIdLessThanOrEqualTo(Long value) {
            addCriterion("EMP_ID <=", value, "empId");
            return this;
        }

        public Criteria andEmpIdIn(List values) {
            addCriterion("EMP_ID in", values, "empId");
            return this;
        }

        public Criteria andEmpIdNotIn(List values) {
            addCriterion("EMP_ID not in", values, "empId");
            return this;
        }

        public Criteria andEmpIdBetween(Long value1, Long value2) {
            addCriterion("EMP_ID between", value1, value2, "empId");
            return this;
        }

        public Criteria andEmpIdNotBetween(Long value1, Long value2) {
            addCriterion("EMP_ID not between", value1, value2, "empId");
            return this;
        }

        public Criteria andEmpNameIsNull() {
            addCriterion("EMP_NAME is null");
            return this;
        }

        public Criteria andEmpNameIsNotNull() {
            addCriterion("EMP_NAME is not null");
            return this;
        }

        public Criteria andEmpNameEqualTo(String value) {
            addCriterion("EMP_NAME =", value, "empName");
            return this;
        }

        public Criteria andEmpNameNotEqualTo(String value) {
            addCriterion("EMP_NAME <>", value, "empName");
            return this;
        }

        public Criteria andEmpNameGreaterThan(String value) {
            addCriterion("EMP_NAME >", value, "empName");
            return this;
        }

        public Criteria andEmpNameGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_NAME >=", value, "empName");
            return this;
        }

        public Criteria andEmpNameLessThan(String value) {
            addCriterion("EMP_NAME <", value, "empName");
            return this;
        }

        public Criteria andEmpNameLessThanOrEqualTo(String value) {
            addCriterion("EMP_NAME <=", value, "empName");
            return this;
        }

        public Criteria andEmpNameLike(String value) {
            addCriterion("EMP_NAME like", value, "empName");
            return this;
        }

        public Criteria andEmpNameNotLike(String value) {
            addCriterion("EMP_NAME not like", value, "empName");
            return this;
        }

        public Criteria andEmpNameIn(List values) {
            addCriterion("EMP_NAME in", values, "empName");
            return this;
        }

        public Criteria andEmpNameNotIn(List values) {
            addCriterion("EMP_NAME not in", values, "empName");
            return this;
        }

        public Criteria andEmpNameBetween(String value1, String value2) {
            addCriterion("EMP_NAME between", value1, value2, "empName");
            return this;
        }

        public Criteria andEmpNameNotBetween(String value1, String value2) {
            addCriterion("EMP_NAME not between", value1, value2, "empName");
            return this;
        }

        public Criteria andFlowIdIsNull() {
            addCriterion("FLOW_ID is null");
            return this;
        }

        public Criteria andFlowIdIsNotNull() {
            addCriterion("FLOW_ID is not null");
            return this;
        }

        public Criteria andFlowIdEqualTo(String value) {
            addCriterion("FLOW_ID =", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotEqualTo(String value) {
            addCriterion("FLOW_ID <>", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThan(String value) {
            addCriterion("FLOW_ID >", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThanOrEqualTo(String value) {
            addCriterion("FLOW_ID >=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThan(String value) {
            addCriterion("FLOW_ID <", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThanOrEqualTo(String value) {
            addCriterion("FLOW_ID <=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLike(String value) {
            addCriterion("FLOW_ID like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotLike(String value) {
            addCriterion("FLOW_ID not like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdIn(List values) {
            addCriterion("FLOW_ID in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdNotIn(List values) {
            addCriterion("FLOW_ID not in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdBetween(String value1, String value2) {
            addCriterion("FLOW_ID between", value1, value2, "flowId");
            return this;
        }

        public Criteria andFlowIdNotBetween(String value1, String value2) {
            addCriterion("FLOW_ID not between", value1, value2, "flowId");
            return this;
        }

        public Criteria andDaTitleIsNull() {
            addCriterion("DA_TITLE is null");
            return this;
        }

        public Criteria andDaTitleIsNotNull() {
            addCriterion("DA_TITLE is not null");
            return this;
        }

        public Criteria andDaTitleEqualTo(String value) {
            addCriterion("DA_TITLE =", value, "daTitle");
            return this;
        }

        public Criteria andDaTitleNotEqualTo(String value) {
            addCriterion("DA_TITLE <>", value, "daTitle");
            return this;
        }

        public Criteria andDaTitleGreaterThan(String value) {
            addCriterion("DA_TITLE >", value, "daTitle");
            return this;
        }

        public Criteria andDaTitleGreaterThanOrEqualTo(String value) {
            addCriterion("DA_TITLE >=", value, "daTitle");
            return this;
        }

        public Criteria andDaTitleLessThan(String value) {
            addCriterion("DA_TITLE <", value, "daTitle");
            return this;
        }

        public Criteria andDaTitleLessThanOrEqualTo(String value) {
            addCriterion("DA_TITLE <=", value, "daTitle");
            return this;
        }

        public Criteria andDaTitleLike(String value) {
            addCriterion("DA_TITLE like", value, "daTitle");
            return this;
        }

        public Criteria andDaTitleNotLike(String value) {
            addCriterion("DA_TITLE not like", value, "daTitle");
            return this;
        }

        public Criteria andDaTitleIn(List values) {
            addCriterion("DA_TITLE in", values, "daTitle");
            return this;
        }

        public Criteria andDaTitleNotIn(List values) {
            addCriterion("DA_TITLE not in", values, "daTitle");
            return this;
        }

        public Criteria andDaTitleBetween(String value1, String value2) {
            addCriterion("DA_TITLE between", value1, value2, "daTitle");
            return this;
        }

        public Criteria andDaTitleNotBetween(String value1, String value2) {
            addCriterion("DA_TITLE not between", value1, value2, "daTitle");
            return this;
        }

        public Criteria andPhoneNoIsNull() {
            addCriterion("PHONE_NO is null");
            return this;
        }

        public Criteria andPhoneNoIsNotNull() {
            addCriterion("PHONE_NO is not null");
            return this;
        }

        public Criteria andPhoneNoEqualTo(String value) {
            addCriterion("PHONE_NO =", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoNotEqualTo(String value) {
            addCriterion("PHONE_NO <>", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoGreaterThan(String value) {
            addCriterion("PHONE_NO >", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE_NO >=", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoLessThan(String value) {
            addCriterion("PHONE_NO <", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoLessThanOrEqualTo(String value) {
            addCriterion("PHONE_NO <=", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoLike(String value) {
            addCriterion("PHONE_NO like", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoNotLike(String value) {
            addCriterion("PHONE_NO not like", value, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoIn(List values) {
            addCriterion("PHONE_NO in", values, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoNotIn(List values) {
            addCriterion("PHONE_NO not in", values, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoBetween(String value1, String value2) {
            addCriterion("PHONE_NO between", value1, value2, "phoneNo");
            return this;
        }

        public Criteria andPhoneNoNotBetween(String value1, String value2) {
            addCriterion("PHONE_NO not between", value1, value2, "phoneNo");
            return this;
        }

        public Criteria andDaContentIsNull() {
            addCriterion("DA_CONTENT is null");
            return this;
        }

        public Criteria andDaContentIsNotNull() {
            addCriterion("DA_CONTENT is not null");
            return this;
        }

        public Criteria andDaContentEqualTo(String value) {
            addCriterion("DA_CONTENT =", value, "daContent");
            return this;
        }

        public Criteria andDaContentNotEqualTo(String value) {
            addCriterion("DA_CONTENT <>", value, "daContent");
            return this;
        }

        public Criteria andDaContentGreaterThan(String value) {
            addCriterion("DA_CONTENT >", value, "daContent");
            return this;
        }

        public Criteria andDaContentGreaterThanOrEqualTo(String value) {
            addCriterion("DA_CONTENT >=", value, "daContent");
            return this;
        }

        public Criteria andDaContentLessThan(String value) {
            addCriterion("DA_CONTENT <", value, "daContent");
            return this;
        }

        public Criteria andDaContentLessThanOrEqualTo(String value) {
            addCriterion("DA_CONTENT <=", value, "daContent");
            return this;
        }

        public Criteria andDaContentLike(String value) {
            addCriterion("DA_CONTENT like", value, "daContent");
            return this;
        }

        public Criteria andDaContentNotLike(String value) {
            addCriterion("DA_CONTENT not like", value, "daContent");
            return this;
        }

        public Criteria andDaContentIn(List values) {
            addCriterion("DA_CONTENT in", values, "daContent");
            return this;
        }

        public Criteria andDaContentNotIn(List values) {
            addCriterion("DA_CONTENT not in", values, "daContent");
            return this;
        }

        public Criteria andDaContentBetween(String value1, String value2) {
            addCriterion("DA_CONTENT between", value1, value2, "daContent");
            return this;
        }

        public Criteria andDaContentNotBetween(String value1, String value2) {
            addCriterion("DA_CONTENT not between", value1, value2, "daContent");
            return this;
        }

        public Criteria andDaMatterIsNull() {
            addCriterion("DA_MATTER is null");
            return this;
        }

        public Criteria andDaMatterIsNotNull() {
            addCriterion("DA_MATTER is not null");
            return this;
        }

        public Criteria andDaMatterEqualTo(String value) {
            addCriterion("DA_MATTER =", value, "daMatter");
            return this;
        }

        public Criteria andDaMatterNotEqualTo(String value) {
            addCriterion("DA_MATTER <>", value, "daMatter");
            return this;
        }

        public Criteria andDaMatterGreaterThan(String value) {
            addCriterion("DA_MATTER >", value, "daMatter");
            return this;
        }

        public Criteria andDaMatterGreaterThanOrEqualTo(String value) {
            addCriterion("DA_MATTER >=", value, "daMatter");
            return this;
        }

        public Criteria andDaMatterLessThan(String value) {
            addCriterion("DA_MATTER <", value, "daMatter");
            return this;
        }

        public Criteria andDaMatterLessThanOrEqualTo(String value) {
            addCriterion("DA_MATTER <=", value, "daMatter");
            return this;
        }

        public Criteria andDaMatterLike(String value) {
            addCriterion("DA_MATTER like", value, "daMatter");
            return this;
        }

        public Criteria andDaMatterNotLike(String value) {
            addCriterion("DA_MATTER not like", value, "daMatter");
            return this;
        }

        public Criteria andDaMatterIn(List values) {
            addCriterion("DA_MATTER in", values, "daMatter");
            return this;
        }

        public Criteria andDaMatterNotIn(List values) {
            addCriterion("DA_MATTER not in", values, "daMatter");
            return this;
        }

        public Criteria andDaMatterBetween(String value1, String value2) {
            addCriterion("DA_MATTER between", value1, value2, "daMatter");
            return this;
        }

        public Criteria andDaMatterNotBetween(String value1, String value2) {
            addCriterion("DA_MATTER not between", value1, value2, "daMatter");
            return this;
        }

        public Criteria andDaReasonIsNull() {
            addCriterion("DA_REASON is null");
            return this;
        }

        public Criteria andDaReasonIsNotNull() {
            addCriterion("DA_REASON is not null");
            return this;
        }

        public Criteria andDaReasonEqualTo(String value) {
            addCriterion("DA_REASON =", value, "daReason");
            return this;
        }

        public Criteria andDaReasonNotEqualTo(String value) {
            addCriterion("DA_REASON <>", value, "daReason");
            return this;
        }

        public Criteria andDaReasonGreaterThan(String value) {
            addCriterion("DA_REASON >", value, "daReason");
            return this;
        }

        public Criteria andDaReasonGreaterThanOrEqualTo(String value) {
            addCriterion("DA_REASON >=", value, "daReason");
            return this;
        }

        public Criteria andDaReasonLessThan(String value) {
            addCriterion("DA_REASON <", value, "daReason");
            return this;
        }

        public Criteria andDaReasonLessThanOrEqualTo(String value) {
            addCriterion("DA_REASON <=", value, "daReason");
            return this;
        }

        public Criteria andDaReasonLike(String value) {
            addCriterion("DA_REASON like", value, "daReason");
            return this;
        }

        public Criteria andDaReasonNotLike(String value) {
            addCriterion("DA_REASON not like", value, "daReason");
            return this;
        }

        public Criteria andDaReasonIn(List values) {
            addCriterion("DA_REASON in", values, "daReason");
            return this;
        }

        public Criteria andDaReasonNotIn(List values) {
            addCriterion("DA_REASON not in", values, "daReason");
            return this;
        }

        public Criteria andDaReasonBetween(String value1, String value2) {
            addCriterion("DA_REASON between", value1, value2, "daReason");
            return this;
        }

        public Criteria andDaReasonNotBetween(String value1, String value2) {
            addCriterion("DA_REASON not between", value1, value2, "daReason");
            return this;
        }

        public Criteria andDaTlimitIsNull() {
            addCriterion("DA_TLIMIT is null");
            return this;
        }

        public Criteria andDaTlimitIsNotNull() {
            addCriterion("DA_TLIMIT is not null");
            return this;
        }

        public Criteria andDaTlimitEqualTo(String value) {
            addCriterion("DA_TLIMIT =", value, "daTlimit");
            return this;
        }

        public Criteria andDaTlimitNotEqualTo(String value) {
            addCriterion("DA_TLIMIT <>", value, "daTlimit");
            return this;
        }

        public Criteria andDaTlimitGreaterThan(String value) {
            addCriterion("DA_TLIMIT >", value, "daTlimit");
            return this;
        }

        public Criteria andDaTlimitGreaterThanOrEqualTo(String value) {
            addCriterion("DA_TLIMIT >=", value, "daTlimit");
            return this;
        }

        public Criteria andDaTlimitLessThan(String value) {
            addCriterion("DA_TLIMIT <", value, "daTlimit");
            return this;
        }

        public Criteria andDaTlimitLessThanOrEqualTo(String value) {
            addCriterion("DA_TLIMIT <=", value, "daTlimit");
            return this;
        }

        public Criteria andDaTlimitLike(String value) {
            addCriterion("DA_TLIMIT like", value, "daTlimit");
            return this;
        }

        public Criteria andDaTlimitNotLike(String value) {
            addCriterion("DA_TLIMIT not like", value, "daTlimit");
            return this;
        }

        public Criteria andDaTlimitIn(List values) {
            addCriterion("DA_TLIMIT in", values, "daTlimit");
            return this;
        }

        public Criteria andDaTlimitNotIn(List values) {
            addCriterion("DA_TLIMIT not in", values, "daTlimit");
            return this;
        }

        public Criteria andDaTlimitBetween(String value1, String value2) {
            addCriterion("DA_TLIMIT between", value1, value2, "daTlimit");
            return this;
        }

        public Criteria andDaTlimitNotBetween(String value1, String value2) {
            addCriterion("DA_TLIMIT not between", value1, value2, "daTlimit");
            return this;
        }

        public Criteria andDaFreqIsNull() {
            addCriterion("DA_FREQ is null");
            return this;
        }

        public Criteria andDaFreqIsNotNull() {
            addCriterion("DA_FREQ is not null");
            return this;
        }

        public Criteria andDaFreqEqualTo(String value) {
            addCriterion("DA_FREQ =", value, "daFreq");
            return this;
        }

        public Criteria andDaFreqNotEqualTo(String value) {
            addCriterion("DA_FREQ <>", value, "daFreq");
            return this;
        }

        public Criteria andDaFreqGreaterThan(String value) {
            addCriterion("DA_FREQ >", value, "daFreq");
            return this;
        }

        public Criteria andDaFreqGreaterThanOrEqualTo(String value) {
            addCriterion("DA_FREQ >=", value, "daFreq");
            return this;
        }

        public Criteria andDaFreqLessThan(String value) {
            addCriterion("DA_FREQ <", value, "daFreq");
            return this;
        }

        public Criteria andDaFreqLessThanOrEqualTo(String value) {
            addCriterion("DA_FREQ <=", value, "daFreq");
            return this;
        }

        public Criteria andDaFreqLike(String value) {
            addCriterion("DA_FREQ like", value, "daFreq");
            return this;
        }

        public Criteria andDaFreqNotLike(String value) {
            addCriterion("DA_FREQ not like", value, "daFreq");
            return this;
        }

        public Criteria andDaFreqIn(List values) {
            addCriterion("DA_FREQ in", values, "daFreq");
            return this;
        }

        public Criteria andDaFreqNotIn(List values) {
            addCriterion("DA_FREQ not in", values, "daFreq");
            return this;
        }

        public Criteria andDaFreqBetween(String value1, String value2) {
            addCriterion("DA_FREQ between", value1, value2, "daFreq");
            return this;
        }

        public Criteria andDaFreqNotBetween(String value1, String value2) {
            addCriterion("DA_FREQ not between", value1, value2, "daFreq");
            return this;
        }

        public Criteria andDaReqIsNull() {
            addCriterion("DA_REQ is null");
            return this;
        }

        public Criteria andDaReqIsNotNull() {
            addCriterion("DA_REQ is not null");
            return this;
        }

        public Criteria andDaReqEqualTo(String value) {
            addCriterion("DA_REQ =", value, "daReq");
            return this;
        }

        public Criteria andDaReqNotEqualTo(String value) {
            addCriterion("DA_REQ <>", value, "daReq");
            return this;
        }

        public Criteria andDaReqGreaterThan(String value) {
            addCriterion("DA_REQ >", value, "daReq");
            return this;
        }

        public Criteria andDaReqGreaterThanOrEqualTo(String value) {
            addCriterion("DA_REQ >=", value, "daReq");
            return this;
        }

        public Criteria andDaReqLessThan(String value) {
            addCriterion("DA_REQ <", value, "daReq");
            return this;
        }

        public Criteria andDaReqLessThanOrEqualTo(String value) {
            addCriterion("DA_REQ <=", value, "daReq");
            return this;
        }

        public Criteria andDaReqLike(String value) {
            addCriterion("DA_REQ like", value, "daReq");
            return this;
        }

        public Criteria andDaReqNotLike(String value) {
            addCriterion("DA_REQ not like", value, "daReq");
            return this;
        }

        public Criteria andDaReqIn(List values) {
            addCriterion("DA_REQ in", values, "daReq");
            return this;
        }

        public Criteria andDaReqNotIn(List values) {
            addCriterion("DA_REQ not in", values, "daReq");
            return this;
        }

        public Criteria andDaReqBetween(String value1, String value2) {
            addCriterion("DA_REQ between", value1, value2, "daReq");
            return this;
        }

        public Criteria andDaReqNotBetween(String value1, String value2) {
            addCriterion("DA_REQ not between", value1, value2, "daReq");
            return this;
        }

        public Criteria andDaRangeIsNull() {
            addCriterion("DA_RANGE is null");
            return this;
        }

        public Criteria andDaRangeIsNotNull() {
            addCriterion("DA_RANGE is not null");
            return this;
        }

        public Criteria andDaRangeEqualTo(String value) {
            addCriterion("DA_RANGE =", value, "daRange");
            return this;
        }

        public Criteria andDaRangeNotEqualTo(String value) {
            addCriterion("DA_RANGE <>", value, "daRange");
            return this;
        }

        public Criteria andDaRangeGreaterThan(String value) {
            addCriterion("DA_RANGE >", value, "daRange");
            return this;
        }

        public Criteria andDaRangeGreaterThanOrEqualTo(String value) {
            addCriterion("DA_RANGE >=", value, "daRange");
            return this;
        }

        public Criteria andDaRangeLessThan(String value) {
            addCriterion("DA_RANGE <", value, "daRange");
            return this;
        }

        public Criteria andDaRangeLessThanOrEqualTo(String value) {
            addCriterion("DA_RANGE <=", value, "daRange");
            return this;
        }

        public Criteria andDaRangeLike(String value) {
            addCriterion("DA_RANGE like", value, "daRange");
            return this;
        }

        public Criteria andDaRangeNotLike(String value) {
            addCriterion("DA_RANGE not like", value, "daRange");
            return this;
        }

        public Criteria andDaRangeIn(List values) {
            addCriterion("DA_RANGE in", values, "daRange");
            return this;
        }

        public Criteria andDaRangeNotIn(List values) {
            addCriterion("DA_RANGE not in", values, "daRange");
            return this;
        }

        public Criteria andDaRangeBetween(String value1, String value2) {
            addCriterion("DA_RANGE between", value1, value2, "daRange");
            return this;
        }

        public Criteria andDaRangeNotBetween(String value1, String value2) {
            addCriterion("DA_RANGE not between", value1, value2, "daRange");
            return this;
        }

        public Criteria andIsSdataIsNull() {
            addCriterion("IS_SDATA is null");
            return this;
        }

        public Criteria andIsSdataIsNotNull() {
            addCriterion("IS_SDATA is not null");
            return this;
        }

        public Criteria andIsSdataEqualTo(String value) {
            addCriterion("IS_SDATA =", value, "isSdata");
            return this;
        }

        public Criteria andIsSdataNotEqualTo(String value) {
            addCriterion("IS_SDATA <>", value, "isSdata");
            return this;
        }

        public Criteria andIsSdataGreaterThan(String value) {
            addCriterion("IS_SDATA >", value, "isSdata");
            return this;
        }

        public Criteria andIsSdataGreaterThanOrEqualTo(String value) {
            addCriterion("IS_SDATA >=", value, "isSdata");
            return this;
        }

        public Criteria andIsSdataLessThan(String value) {
            addCriterion("IS_SDATA <", value, "isSdata");
            return this;
        }

        public Criteria andIsSdataLessThanOrEqualTo(String value) {
            addCriterion("IS_SDATA <=", value, "isSdata");
            return this;
        }

        public Criteria andIsSdataLike(String value) {
            addCriterion("IS_SDATA like", value, "isSdata");
            return this;
        }

        public Criteria andIsSdataNotLike(String value) {
            addCriterion("IS_SDATA not like", value, "isSdata");
            return this;
        }

        public Criteria andIsSdataIn(List values) {
            addCriterion("IS_SDATA in", values, "isSdata");
            return this;
        }

        public Criteria andIsSdataNotIn(List values) {
            addCriterion("IS_SDATA not in", values, "isSdata");
            return this;
        }

        public Criteria andIsSdataBetween(String value1, String value2) {
            addCriterion("IS_SDATA between", value1, value2, "isSdata");
            return this;
        }

        public Criteria andIsSdataNotBetween(String value1, String value2) {
            addCriterion("IS_SDATA not between", value1, value2, "isSdata");
            return this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("ORG_ID is null");
            return this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("ORG_ID is not null");
            return this;
        }

        public Criteria andOrgIdEqualTo(Long value) {
            addCriterion("ORG_ID =", value, "orgId");
            return this;
        }

        public Criteria andOrgIdNotEqualTo(Long value) {
            addCriterion("ORG_ID <>", value, "orgId");
            return this;
        }

        public Criteria andOrgIdGreaterThan(Long value) {
            addCriterion("ORG_ID >", value, "orgId");
            return this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ORG_ID >=", value, "orgId");
            return this;
        }

        public Criteria andOrgIdLessThan(Long value) {
            addCriterion("ORG_ID <", value, "orgId");
            return this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(Long value) {
            addCriterion("ORG_ID <=", value, "orgId");
            return this;
        }

        public Criteria andOrgIdIn(List values) {
            addCriterion("ORG_ID in", values, "orgId");
            return this;
        }

        public Criteria andOrgIdNotIn(List values) {
            addCriterion("ORG_ID not in", values, "orgId");
            return this;
        }

        public Criteria andOrgIdBetween(Long value1, Long value2) {
            addCriterion("ORG_ID between", value1, value2, "orgId");
            return this;
        }

        public Criteria andOrgIdNotBetween(Long value1, Long value2) {
            addCriterion("ORG_ID not between", value1, value2, "orgId");
            return this;
        }

        public Criteria andEEmpIdIsNull() {
            addCriterion("E_EMP_ID is null");
            return this;
        }

        public Criteria andEEmpIdIsNotNull() {
            addCriterion("E_EMP_ID is not null");
            return this;
        }

        public Criteria andEEmpIdEqualTo(Long value) {
            addCriterion("E_EMP_ID =", value, "eEmpId");
            return this;
        }

        public Criteria andEEmpIdNotEqualTo(Long value) {
            addCriterion("E_EMP_ID <>", value, "eEmpId");
            return this;
        }

        public Criteria andEEmpIdGreaterThan(Long value) {
            addCriterion("E_EMP_ID >", value, "eEmpId");
            return this;
        }

        public Criteria andEEmpIdGreaterThanOrEqualTo(Long value) {
            addCriterion("E_EMP_ID >=", value, "eEmpId");
            return this;
        }

        public Criteria andEEmpIdLessThan(Long value) {
            addCriterion("E_EMP_ID <", value, "eEmpId");
            return this;
        }

        public Criteria andEEmpIdLessThanOrEqualTo(Long value) {
            addCriterion("E_EMP_ID <=", value, "eEmpId");
            return this;
        }

        public Criteria andEEmpIdIn(List values) {
            addCriterion("E_EMP_ID in", values, "eEmpId");
            return this;
        }

        public Criteria andEEmpIdNotIn(List values) {
            addCriterion("E_EMP_ID not in", values, "eEmpId");
            return this;
        }

        public Criteria andEEmpIdBetween(Long value1, Long value2) {
            addCriterion("E_EMP_ID between", value1, value2, "eEmpId");
            return this;
        }

        public Criteria andEEmpIdNotBetween(Long value1, Long value2) {
            addCriterion("E_EMP_ID not between", value1, value2, "eEmpId");
            return this;
        }

        public Criteria andUseTlimitIsNull() {
            addCriterion("USE_TLIMIT is null");
            return this;
        }

        public Criteria andUseTlimitIsNotNull() {
            addCriterion("USE_TLIMIT is not null");
            return this;
        }

        public Criteria andUseTlimitEqualTo(String value) {
            addCriterion("USE_TLIMIT =", value, "useTlimit");
            return this;
        }

        public Criteria andUseTlimitNotEqualTo(String value) {
            addCriterion("USE_TLIMIT <>", value, "useTlimit");
            return this;
        }

        public Criteria andUseTlimitGreaterThan(String value) {
            addCriterion("USE_TLIMIT >", value, "useTlimit");
            return this;
        }

        public Criteria andUseTlimitGreaterThanOrEqualTo(String value) {
            addCriterion("USE_TLIMIT >=", value, "useTlimit");
            return this;
        }

        public Criteria andUseTlimitLessThan(String value) {
            addCriterion("USE_TLIMIT <", value, "useTlimit");
            return this;
        }

        public Criteria andUseTlimitLessThanOrEqualTo(String value) {
            addCriterion("USE_TLIMIT <=", value, "useTlimit");
            return this;
        }

        public Criteria andUseTlimitLike(String value) {
            addCriterion("USE_TLIMIT like", value, "useTlimit");
            return this;
        }

        public Criteria andUseTlimitNotLike(String value) {
            addCriterion("USE_TLIMIT not like", value, "useTlimit");
            return this;
        }

        public Criteria andUseTlimitIn(List values) {
            addCriterion("USE_TLIMIT in", values, "useTlimit");
            return this;
        }

        public Criteria andUseTlimitNotIn(List values) {
            addCriterion("USE_TLIMIT not in", values, "useTlimit");
            return this;
        }

        public Criteria andUseTlimitBetween(String value1, String value2) {
            addCriterion("USE_TLIMIT between", value1, value2, "useTlimit");
            return this;
        }

        public Criteria andUseTlimitNotBetween(String value1, String value2) {
            addCriterion("USE_TLIMIT not between", value1, value2, "useTlimit");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateIn(List values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateNotIn(List values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return this;
        }

        public Criteria andRiskIsNull() {
            addCriterion("RISK is null");
            return this;
        }

        public Criteria andRiskIsNotNull() {
            addCriterion("RISK is not null");
            return this;
        }

        public Criteria andRiskEqualTo(String value) {
            addCriterion("RISK =", value, "risk");
            return this;
        }

        public Criteria andRiskNotEqualTo(String value) {
            addCriterion("RISK <>", value, "risk");
            return this;
        }

        public Criteria andRiskGreaterThan(String value) {
            addCriterion("RISK >", value, "risk");
            return this;
        }

        public Criteria andRiskGreaterThanOrEqualTo(String value) {
            addCriterion("RISK >=", value, "risk");
            return this;
        }

        public Criteria andRiskLessThan(String value) {
            addCriterion("RISK <", value, "risk");
            return this;
        }

        public Criteria andRiskLessThanOrEqualTo(String value) {
            addCriterion("RISK <=", value, "risk");
            return this;
        }

        public Criteria andRiskLike(String value) {
            addCriterion("RISK like", value, "risk");
            return this;
        }

        public Criteria andRiskNotLike(String value) {
            addCriterion("RISK not like", value, "risk");
            return this;
        }

        public Criteria andRiskIn(List values) {
            addCriterion("RISK in", values, "risk");
            return this;
        }

        public Criteria andRiskNotIn(List values) {
            addCriterion("RISK not in", values, "risk");
            return this;
        }

        public Criteria andRiskBetween(String value1, String value2) {
            addCriterion("RISK between", value1, value2, "risk");
            return this;
        }

        public Criteria andRiskNotBetween(String value1, String value2) {
            addCriterion("RISK not between", value1, value2, "risk");
            return this;
        }

        public Criteria andDaFetchIsNull() {
            addCriterion("DA_FETCH is null");
            return this;
        }

        public Criteria andDaFetchIsNotNull() {
            addCriterion("DA_FETCH is not null");
            return this;
        }

        public Criteria andDaFetchEqualTo(String value) {
            addCriterion("DA_FETCH =", value, "daFetch");
            return this;
        }

        public Criteria andDaFetchNotEqualTo(String value) {
            addCriterion("DA_FETCH <>", value, "daFetch");
            return this;
        }

        public Criteria andDaFetchGreaterThan(String value) {
            addCriterion("DA_FETCH >", value, "daFetch");
            return this;
        }

        public Criteria andDaFetchGreaterThanOrEqualTo(String value) {
            addCriterion("DA_FETCH >=", value, "daFetch");
            return this;
        }

        public Criteria andDaFetchLessThan(String value) {
            addCriterion("DA_FETCH <", value, "daFetch");
            return this;
        }

        public Criteria andDaFetchLessThanOrEqualTo(String value) {
            addCriterion("DA_FETCH <=", value, "daFetch");
            return this;
        }

        public Criteria andDaFetchLike(String value) {
            addCriterion("DA_FETCH like", value, "daFetch");
            return this;
        }

        public Criteria andDaFetchNotLike(String value) {
            addCriterion("DA_FETCH not like", value, "daFetch");
            return this;
        }

        public Criteria andDaFetchIn(List values) {
            addCriterion("DA_FETCH in", values, "daFetch");
            return this;
        }

        public Criteria andDaFetchNotIn(List values) {
            addCriterion("DA_FETCH not in", values, "daFetch");
            return this;
        }

        public Criteria andDaFetchBetween(String value1, String value2) {
            addCriterion("DA_FETCH between", value1, value2, "daFetch");
            return this;
        }

        public Criteria andDaFetchNotBetween(String value1, String value2) {
            addCriterion("DA_FETCH not between", value1, value2, "daFetch");
            return this;
        }
    }
}