package com.gotop.tyjg.stable.dao.impl;

import java.util.HashMap;
import java.util.List;

import org.apache.log4j.Logger;

import com.gotop.tyjg.stable.dao.IOmGroupmemberDAO;
import com.gotop.tyjg.stable.model.OmGroupmemberExample;
import com.gotop.tyjg.stable.model.OmGroupmemberKey;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;


public class OmGroupmemberDAO extends SqlMapClientDao implements IOmGroupmemberDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(OmGroupmemberDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table OM_GROUPMEMBER
     *
     * @abatorgenerated 
     */
    public OmGroupmemberDAO() {
        super();
    }

    /**
     * 插入一条新数据
     * @abatorgenerated
     */
    public void insert(OmGroupmemberKey record) {
        this.insert("OM_GROUPMEMBER_SqlMap.abatorgenerated_insert", record);
    }

    /**
     * 通过查询实例，查询记录
     * @abatorgenerated
     */
    public List selectByExample(OmGroupmemberExample example) {
        List list = queryForList("OM_GROUPMEMBER_SqlMap.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * 通过Map方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByMapAndPage(HashMap example) {
        List list = queryForList("OM_GROUPMEMBER_SqlMap.abatorgenerated_selectByMapAndPage", example);
        return list;
    }

    /**
     * 通过Bean方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByExampleAndPage(OmGroupmemberKey record, OmGroupmemberExample example, Page page) {
         UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
         List list = queryForList("OM_GROUPMEMBER_SqlMap.abatorgenerated_selectByExampleAndPage",parms,page);
        return list;
    }

    /**
     * 通过查询实例，删除数据
     * @abatorgenerated
     */
    public int deleteByExample(OmGroupmemberExample example) {
        int rows = this.delete("OM_GROUPMEMBER_SqlMap.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * 通过主键删除一条记录
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(OmGroupmemberKey key) {
        int rows = this.delete("OM_GROUPMEMBER_SqlMap.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * 通过查询实例，统计总数
     * @abatorgenerated
     */
    public int countByExample(OmGroupmemberExample example) {
        Integer count = (Integer)  queryForObject("OM_GROUPMEMBER_SqlMap.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * 通过查询实例，更新非null字段
     * @abatorgenerated
     */
    public int updateByExampleSelective(OmGroupmemberKey record, OmGroupmemberExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = this.update("OM_GROUPMEMBER_SqlMap.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * 通过查询实例，更新全部字段
     * @abatorgenerated
     */
    public int updateByExample(OmGroupmemberKey record, OmGroupmemberExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = this.update("OM_GROUPMEMBER_SqlMap.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * 分页查询信息
     * @abatorgenerated
     */
    public List selectByDynamic(HashMap map, Page page) throws Exception {
        List list = queryForList("OM_GROUPMEMBER_SqlMap.abatorgenerated_selectByDynamic", map, page);
        return list;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table OM_GROUPMEMBER
     *
     * @abatorgenerated 
     */
    private static class UpdateByExampleParms extends OmGroupmemberExample {
        private Object record;

        public UpdateByExampleParms(Object record, OmGroupmemberExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}